/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package emc.methods.gl;

import emc.enums.modules.enumEMCModules;
import emc.methods.EMCMethodEnum;

/**
 *
 * @author riaan
 */
public enum ServerGLMethods implements EMCMethodEnum {
    //Currency

    INSERT_GLCURRENCY(0, "INSERT_GLCURRENCY"),
    UPDATE_GLCURRENCY(1, "UPDATE_GLCURRENCY"),
    DELETE_GLCURRENCY(2, "DELETE_GLCURRENCY"),
    GETNUMROWS_GLCURRENCY(3, "GETNUMROWS_GLCURRENCY"),
    GETDATA_GLCURRENCY(4, "GETDATA_GLCURRENCY"),
    VALIDATEFIELD_GLCURRENCY(5, "VALIDATEFIELD_GLCURRENCY"),
    //VAT Codes
    INSERT_GLVATCODE(20, "INSERT_GLVATCODE"),
    UPDATE_GLVATCODE(21, "UPDATE_GLVATCODE"),
    DELETE_GLVATCODE(22, "DELETE_GLVATCODE"),
    GETNUMROWS_GLVATCODE(23, "GETNUMROWS_GLVATCODE"),
    GETDATA_GLVATCODE(24, "GETDATA_GLVATCODE"),
    VALIDATEFIELD_GLVATCODE(25, "VALIDATEFIELD_GLVATCODE"),
    //Chart Of Accounts
    INSERT_GLCHARTOFACCOUNTS(40, "INSERT_GLCHARTOFACCOUNTS"),
    UPDATE_GLCHARTOFACCOUNTS(41, "UPDATE_GLCHARTOFACCOUNTS"),
    DELETE_GLCHARTOFACCOUNTS(42, "DELETE_GLCHARTOFACCOUNTS"),
    GETNUMROWS_GLCHARTOFACCOUNTS(43, "GETNUMROWS_GLCHARTOFACCOUNTS"),
    GETDATA_GLCHARTOFACCOUNTS(44, "GETDATA_GLCHARTOFACCOUNTS"),
    VALIDATEFIELD_GLCHARTOFACCOUNTS(45, "VALIDATEFIELD_GLCHARTOFACCOUNTS"),
    PRINT_CHART_OF_ACCOUNTS(46, "PRINT_CHART_OF_ACCOUNTS"),
    //GL Financial Periods
    INSERT_GLFINANCIALPERIODS(60, "INSERT_GLFINANCIALPERIODS"),
    UPDATE_GLFINANCIALPERIODS(61, "UPDATE_GLFINANCIALPERIODS"),
    DELETE_GLFINANCIALPERIODS(62, "DELETE_GLFINANCIALPERIODS"),
    GETNUMROWS_GLFINANCIALPERIODS(63, "GETNUMROWS_GLFINANCIALPERIODS"),
    GETDATA_GLFINANCIALPERIODS(64, "GETDATA_GLFINANCIALPERIODS"),
    VALIDATEFIELD_GLFINANCIALPERIODS(65, "VALIDATEFIELD_GLFINANCIALPERIODS"),
    REFRESH_SUBLEDGERS(66, "REFRESH_SUBLEDGERS"),
    GENERATE_FINANCIAL_PERIODS(67, "GENERATE_FINANCIAL_PERIODS"),
    //GLTransactionPeriodSummary
    INSERT_GLTRANSACTIONPERIODSUMMARY(80, "INSERT_GLTRANSACTIONPERIODSUMMARY"),
    UPDATE_GLTRANSACTIONPERIODSUMMARY(81, "UPDATE_GLTRANSACTIONPERIODSUMMARY"),
    DELETE_GLTRANSACTIONPERIODSUMMARY(82, "DELETE_GLTRANSACTIONPERIODSUMMARY"),
    GETNUMROWS_GLTRANSACTIONPERIODSUMMARY(83, "GETNUMROWS_GLTRANSACTIONPERIODSUMMARY"),
    GETDATA_GLTRANSACTIONPERIODSUMMARY(84, "GETDATA_GLTRANSACTIONPERIODSUMMARY"),
    VALIDATEFIELD_GLTRANSACTIONPERIODSUMMARY(85, "VALIDATEFIELD_GLTRANSACTIONPERIODSUMMARY"),
    GENERATE_OPENING_BALANCES(86, "GENERATE_OPENING_BALANCES"),
    //GLSecurityRules
    INSERT_GLSECURITYRULES(100, "INSERT_GLSECURITYRULES"),
    UPDATE_GLSECURITYRULES(101, "UPDATE_GLSECURITYRULES"),
    DELETE_GLSECURITYRULES(102, "DELETE_GLSECURITYRULES"),
    GETNUMROWS_GLSECURITYRULES(103, "GETNUMROWS_GLSECURITYRULES"),
    GETDATA_GLSECURITYRULES(104, "GETDATA_GLSECURITYRULES"),
    VALIDATEFIELD_GLSECURITYRULES(105, "VALIDATEFIELD_GLSECURITYRULES"),
    //GLAnalysisRules
    INSERT_GLANALYSISRULES(120, "INSERT_GLANALYSISRULES"),
    UPDATE_GLANALYSISRULES(121, "UPDATE_GLANALYSISRULES"),
    DELETE_GLANALYSISRULES(122, "DELETE_GLANALYSISRULES"),
    GETNUMROWS_GLANALYSISRULES(123, "GETNUMROWS_GLANALYSISRULES"),
    GETDATA_GLANALYSISRULES(124, "GETDATA_GLANALYSISRULES"),
    VALIDATEFIELD_GLANALYSISRULES(125, "VALIDATEFIELD_GLANALYSISRULES"),
    //GLAllocationRules
    INSERT_GLALLOCATIONRULES(140, "INSERT_GLALLOCATIONRULES"),
    UPDATE_GLALLOCATIONRULES(141, "UPDATE_GLALLOCATIONRULES"),
    DELETE_GLALLOCATIONRULES(142, "DELETE_GLALLOCATIONRULES"),
    GETNUMROWS_GLALLOCATIONRULES(143, "GETNUMROWS_GLALLOCATIONRULES"),
    GETDATA_GLALLOCATIONRULES(144, "GETDATA_GLALLOCATIONRULES"),
    VALIDATEFIELD_GLALLOCATIONRULES(145, "VALIDATEFIELD_GLALLOCATIONRULES"),
    //GLChartOfAccountsBalances
    INSERT_GLCHARTOFACCOUNTSBALANCES(160, "INSERT_GLCHARTOFACCOUNTSBALANCES"),
    UPDATE_GLCHARTOFACCOUNTSBALANCES(161, "UPDATE_GLCHARTOFACCOUNTSBALANCES"),
    DELETE_GLCHARTOFACCOUNTSBALANCES(162, "DELETE_GLCHARTOFACCOUNTSBALANCES"),
    GETNUMROWS_GLCHARTOFACCOUNTSBALANCES(163, "GETNUMROWS_GLCHARTOFACCOUNTSBALANCES"),
    GETDATA_GLCHARTOFACCOUNTSBALANCES(164, "GETDATA_GLCHARTOFACCOUNTSBALANCES"),
    VALIDATEFIELD_GLCHARTOFACCOUNTSBALANCES(165, "VALIDATEFIELD_GLCHARTOFACCOUNTSBALANCES"),
    //GLChartOfAccountsAnalysisBalances
    INSERT_GLCHARTOFACCOUNTSANALYSISBALANCES(180, "INSERT_GLCHARTOFACCOUNTSANALYSISBALANCES"),
    UPDATE_GLCHARTOFACCOUNTSANALYSISBALANCES(181, "UPDATE_GLCHARTOFACCOUNTSANALYSISBALANCES"),
    DELETE_GLCHARTOFACCOUNTSANALYSISBALANCES(182, "DELETE_GLCHARTOFACCOUNTSANALYSISBALANCES"),
    GETNUMROWS_GLCHARTOFACCOUNTSANALYSISBALANCES(183, "GETNUMROWS_GLCHARTOFACCOUNTSANALYSISBALANCES"),
    GETDATA_GLCHARTOFACCOUNTSANALYSISBALANCES(184, "GETDATA_GLCHARTOFACCOUNTSANALYSISBALANCES"),
    VALIDATEFIELD_GLCHARTOFACCOUNTSANALYSISBALANCES(185, "VALIDATEFIELD_GLCHARTOFACCOUNTSANALYSISBALANCES"),
    //GLJournalMaster
    INSERT_GLJOURNALMASTER(200, "INSERT_GLJOURNALMASTER"),
    UPDATE_GLJOURNALMASTER(201, "UPDATE_GLJOURNALMASTER"),
    DELETE_GLJOURNALMASTER(202, "DELETE_GLJOURNALMASTER"),
    GETNUMROWS_GLJOURNALMASTER(203, "GETNUMROWS_GLJOURNALMASTER"),
    GETDATA_GLJOURNALMASTER(204, "GETDATA_GLJOURNALMASTER"),
    VALIDATEFIELD_GLJOURNALMASTER(205, "VALIDATEFIELD_GLJOURNALMASTER"),
    APPROVE_JOURNAL(206, "APPROVE_JOURNAL"),
    UNAPPROVE_JOURNAL(207, "UNAPPROVE_JOURNAL"),
    POST_JOURNAL(208, "POST_JOURNAL"),
    VALIDATE_JOURNAL(209, "VALIDATE_JOURNAL"),
    GET_JOURNAL_TOTALS(210, "GET_JOURNAL_TOTALS"),
    PRINT_JOURNAL_REPORT(211, "PRINT_JOURNAL_REPORT"),
    //GLJournalLines
    INSERT_GLJOURNALLINES(220, "INSERT_GLJOURNALLINES"),
    UPDATE_GLJOURNALLINES(221, "UPDATE_GLJOURNALLINES"),
    DELETE_GLJOURNALLINES(222, "DELETE_GLJOURNALLINES"),
    GETNUMROWS_GLJOURNALLINES(223, "GETNUMROWS_GLJOURNALLINES"),
    GETDATA_GLJOURNALLINES(224, "GETDATA_GLJOURNALLINES"),
    VALIDATEFIELD_GLJOURNALLINES(225, "VALIDATEFIELD_GLJOURNALLINES"),
    //GLAnalysisCode1
    INSERT_GLANALYSISCODE1(240, "INSERT_GLANALYSISCODE1"),
    UPDATE_GLANALYSISCODE1(241, "UPDATE_GLANALYSISCODE1"),
    DELETE_GLANALYSISCODE1(242, "DELETE_GLANALYSISCODE1"),
    GETNUMROWS_GLANALYSISCODE1(243, "GETNUMROWS_GLANALYSISCODE1"),
    GETDATA_GLANALYSISCODE1(244, "GETDATA_GLANALYSISCODE1"),
    VALIDATEFIELD_GLANALYSISCODE1(245, "VALIDATEFIELD_GLANALYSISCODE1"),
    //GLAnalysisCode2
    INSERT_GLANALYSISCODE2(260, "INSERT_GLANALYSISCODE2"),
    UPDATE_GLANALYSISCODE2(261, "UPDATE_GLANALYSISCODE2"),
    DELETE_GLANALYSISCODE2(262, "DELETE_GLANALYSISCODE2"),
    GETNUMROWS_GLANALYSISCODE2(263, "GETNUMROWS_GLANALYSISCODE2"),
    GETDATA_GLANALYSISCODE2(264, "GETDATA_GLANALYSISCODE2"),
    VALIDATEFIELD_GLANALYSISCODE2(265, "VALIDATEFIELD_GLANALYSISCODE2"),
    //GLAnalysisCode3
    INSERT_GLANALYSISCODE3(280, "INSERT_GLANALYSISCODE3"),
    UPDATE_GLANALYSISCODE3(281, "UPDATE_GLANALYSISCODE3"),
    DELETE_GLANALYSISCODE3(282, "DELETE_GLANALYSISCODE3"),
    GETNUMROWS_GLANALYSISCODE3(283, "GETNUMROWS_GLANALYSISCODE3"),
    GETDATA_GLANALYSISCODE3(284, "GETDATA_GLANALYSISCODE3"),
    VALIDATEFIELD_GLANALYSISCODE3(285, "VALIDATEFIELD_GLANALYSISCODE3"),
    //GLAnalysisCode4
    INSERT_GLANALYSISCODE4(300, "INSERT_GLANALYSISCODE4"),
    UPDATE_GLANALYSISCODE4(301, "UPDATE_GLANALYSISCODE4"),
    DELETE_GLANALYSISCODE4(302, "DELETE_GLANALYSISCODE4"),
    GETNUMROWS_GLANALYSISCODE4(303, "GETNUMROWS_GLANALYSISCODE4"),
    GETDATA_GLANALYSISCODE4(304, "GETDATA_GLANALYSISCODE4"),
    VALIDATEFIELD_GLANALYSISCODE4(305, "VALIDATEFIELD_GLANALYSISCODE4"),
    //GLAnalysisCodeHierarchy
    INSERT_GLANALYSISCODEHIERARCHY(300, "INSERT_GLANALYSISCODEHIERARCHY"),
    UPDATE_GLANALYSISCODEHIERARCHY(301, "UPDATE_GLANALYSISCODEHIERARCHY"),
    DELETE_GLANALYSISCODEHIERARCHY(302, "DELETE_GLANALYSISCODEHIERARCHY"),
    GETNUMROWS_GLANALYSISCODEHIERARCHY(303, "GETNUMROWS_GLANALYSISCODEHIERARCHY"),
    GETDATA_GLANALYSISCODEHIERARCHY(304, "GETDATA_GLANALYSISCODEHIERARCHY"),
    VALIDATEFIELD_GLANALYSISCODEHIERARCHY(305, "VALIDATEFIELD_GLANALYSISCODEHIERARCHY"),
    //GLJournalApprovalGroups
    INSERT_GLJOURNALAPPROVALGROUPS(320, "INSERT_GLJOURNALAPPROVALGROUPS"),
    UPDATE_GLJOURNALAPPROVALGROUPS(321, "UPDATE_GLJOURNALAPPROVALGROUPS"),
    DELETE_GLJOURNALAPPROVALGROUPS(322, "DELETE_GLJOURNALAPPROVALGROUPS"),
    GETNUMROWS_GLJOURNALAPPROVALGROUPS(323, "GETNUMROWS_GLJOURNALAPPROVALGROUPS"),
    GETDATA_GLJOURNALAPPROVALGROUPS(324, "GETDATA_GLJOURNALAPPROVALGROUPS"),
    VALIDATEFIELD_GLJOURNALAPPROVALGROUPS(325, "VALIDATEFIELD_GLJOURNALAPPROVALGROUPS"),
    //GLApprovalGroupEmployees
    INSERT_GLJOURNALAPPROVALGROUPEMPLOYEES(340, "INSERT_GLJOURNALAPPROVALGROUPEMPLOYEES"),
    UPDATE_GLJOURNALAPPROVALGROUPEMPLOYEES(341, "UPDATE_GLJOURNALAPPROVALGROUPEMPLOYEES"),
    DELETE_GLJOURNALAPPROVALGROUPEMPLOYEES(342, "DELETE_GLJOURNALAPPROVALGROUPEMPLOYEES"),
    GETNUMROWS_GLJOURNALAPPROVALGROUPEMPLOYEES(343, "GETNUMROWS_GLJOURNALAPPROVALGROUPEMPLOYEES"),
    GETDATA_GLJOURNALAPPROVALGROUPEMPLOYEES(344, "GETDATA_GLJOURNALAPPROVALGROUPEMPLOYEES"),
    VALIDATEFIELD_GLJOURNALAPPROVALGROUPEMPLOYEES(345, "VALIDATEFIELD_GLJOURNALAPPROVALGROUPEMPLOYEES"),
    //Journal Approval Groups
    INSERT_GLJOURNALAPPROVALGROUPEMPLOYEESDS(360, "INSERT_GLJOURNALAPPROVALGROUPEMPLOYEESDS"),
    UPDATE_GLJOURNALAPPROVALGROUPEMPLOYEESDS(361, "UPDATE_GLJOURNALAPPROVALGROUPEMPLOYEESDS"),
    DELETE_GLJOURNALAPPROVALGROUPEMPLOYEESDS(362, "DELETE_GLJOURNALAPPROVALGROUPEMPLOYEESDS"),
    GETNUMROWS_GLJOURNALAPPROVALGROUPEMPLOYEESDS(363, "GETNUMROWS_GLJOURNALAPPROVALGROUPEMPLOYEESDS"),
    GETDATA_GLJOURNALAPPROVALGROUPEMPLOYEESDS(364, "GETDATA_GLJOURNALAPPROVALGROUPEMPLOYEESDS"),
    VALIDATEFIELD_GLJOURNALAPPROVALGROUPEMPLOYEESDS(365, "VALIDATEFIELD_GLJOURNALAPPROVALGROUPEMPLOYEESDS"),
    //GLAnalysisCode5
    INSERT_GLANALYSISCODE5(380, "INSERT_GLANALYSISCODE5"),
    UPDATE_GLANALYSISCODE5(381, "UPDATE_GLANALYSISCODE5"),
    DELETE_GLANALYSISCODE5(382, "DELETE_GLANALYSISCODE5"),
    GETNUMROWS_GLANALYSISCODE5(383, "GETNUMROWS_GLANALYSISCODE5"),
    GETDATA_GLANALYSISCODE5(384, "GETDATA_GLANALYSISCODE5"),
    VALIDATEFIELD_GLANALYSISCODE5(385, "VALIDATEFIELD_GLANALYSISCODE5"),
    //GLAnalysisCode6
    INSERT_GLANALYSISCODE6(400, "INSERT_GLANALYSISCODE6"),
    UPDATE_GLANALYSISCODE6(401, "UPDATE_GLANALYSISCODE6"),
    DELETE_GLANALYSISCODE6(402, "DELETE_GLANALYSISCODE6"),
    GETNUMROWS_GLANALYSISCODE6(403, "GETNUMROWS_GLANALYSISCODE6"),
    GETDATA_GLANALYSISCODE6(404, "GETDATA_GLANALYSISCODE6"),
    VALIDATEFIELD_GLANALYSISCODE6(405, "VALIDATEFIELD_GLANALYSISCODE6"),
    //GLTransactionsSummary
    INSERT_GLTRANSACTIONSSUMMARY(420, "INSERT_GLTRANSACTIONSSUMMARY"),
    UPDATE_GLTRANSACTIONSSUMMARY(421, "UPDATE_GLTRANSACTIONSSUMMARY"),
    DELETE_GLTRANSACTIONSSUMMARY(422, "DELETE_GLTRANSACTIONSSUMMARY"),
    GETNUMROWS_GLTRANSACTIONSSUMMARY(423, "GETNUMROWS_GLTRANSACTIONSSUMMARY"),
    GETDATA_GLTRANSACTIONSSUMMARY(424, "GETDATA_GLTRANSACTIONSSUMMARY"),
    VALIDATEFIELD_GLTRANSACTIONSSUMMARY(425, "VALIDATEFIELD_GLTRANSACTIONSSUMMARY"),
    //GLAnalysisCodesSuper
    INSERT_GLANALYSISCODESUPER(440, "INSERT_GLANALYSISCODESUPER"),
    UPDATE_GLANALYSISCODESUPER(441, "UPDATE_GLANALYSISCODESUPER"),
    DELETE_GLANALYSISCODESUPER(442, "DELETE_GLANALYSISCODESUPER"),
    GETNUMROWS_GLANALYSISCODESUPER(444, "GETNUMROWS_GLANALYSISCODESUPER"),
    GETDATA_GLANALYSISCODESUPER(445, "GETDATA_GLANALYSISCODESUPER"),
    VALIDATEFIELD_GLANALYSISCODESUPER(446, "VALIDATEFIELD_GLANALYSISCODESUPER"),
    //GLTransactions Detail
    INSERT_GLTRANSACTIONSDETAIL(460, "INSERT_GLTRANSACTIONSDETAIL"),
    UPDATE_GLTRANSACTIONSDETAIL(461, "UPDATE_GLTRANSACTIONSDETAIL"),
    DELETE_GLTRANSACTIONSDETAIL(462, "DELETE_GLTRANSACTIONSDETAIL"),
    GETNUMROWS_GLTRANSACTIONSDETAIL(463, "GETNUMROWS_GLTRANSACTIONSDETAIL"),
    GETDATA_GLTRANSACTIONSDETAIL(464, "GETDATA_GLTRANSACTIONSDETAIL"),
    VALIDATEFIELD_GLTRANSACTIONSDETAIL(465, "VALIDATEFIELD_GLTRANSACTIONSDETAIL"),
    //GLTransactionSuper
    INSERT_GLTRANSACTIONSSUPER(480, "INSERT_GLTRANSACTIONSSUPER"),
    UPDATE_GLTRANSACTIONSSUPER(481, "UPDATE_GLTRANSACTIONSSUPER"),
    DELETE_GLTRANSACTIONSSUPER(482, "DELETE_GLTRANSACTIONSSUPER"),
    GETNUMROWS_GLTRANSACTIONSSUPER(483, "GETNUMROWS_GLTRANSACTIONSSUPER"),
    GETDATA_GLTRANSACTIONSSUPER(484, "GETDATA_GLTRANSACTIONSSUPER"),
    VALIDATEFIELD_GLTRANSACTIONSSUPER(485, "VALIDATEFIELD_GLTRANSACTIONSSUPER"),
    //GLGroupRules
    INSERT_GLGROUPRULES(500, "INSERT_GLGROUPRULES"),
    UPDATE_GLGROUPRULES(501, "UPDATE_GLGROUPRULES"),
    DELETE_GLGROUPRULES(502, "DELETE_GLGROUPRULES"),
    GETNUMROWS_GLGROUPRULES(503, "GETNUMROWS_GLGROUPRULES"),
    GETDATA_GLGROUPRULES(504, "GETDATA_GLGROUPRULES"),
    VALIDATEFIELD_GLGROUPRULES(505, "VALIDATEFIELD_GLGROUPRULES"),
    //GLGroupCompanyAccount
    INSERT_GLGROUPCOMPANYACCOUNT(520, "INSERT_GLGROUPCOMPANYACCOUNT"),
    UPDATE_GLGROUPCOMPANYACCOUNT(521, "UPDATE_GLGROUPCOMPANYACCOUNT"),
    DELETE_GLGROUPCOMPANYACCOUNT(522, "DELETE_GLGROUPCOMPANYACCOUNT"),
    GETNUMROWS_GLGROUPCOMPANYACCOUNT(523, "GETNUMROWS_GLGROUPCOMPANYACCOUNT"),
    GETDATA_GLGROUPCOMPANYACCOUNT(524, "GETDATA_GLGROUPCOMPANYACCOUNT"),
    VALIDATEFIELD_GLGROUPCOMPANYACCOUNT(525, "VALIDATEFIELD_GLGROUPCOMPANYACCOUNT"),
    //GL Consolidation
    DO_GL_CONSOLIDATION(540, "DO_GL_CONSOLIDATION"),
    REGENERATE_GL_SUMMARY_TABLES(541, "REGENERATE_GL_SUMMARY_TABLES"),
    //GLBudgetModel
    INSERT_GLBUDGETMODEL(560, "INSERT_GLBUDGETMODEL"),
    UPDATE_GLBUDGETMODEL(561, "UPDATE_GLBUDGETMODEL"),
    DELETE_GLBUDGETMODEL(562, "DELETE_GLBUDGETMODEL"),
    GETNUMROWS_GLBUDGETMODEL(563, "GETNUMROWS_GLBUDGETMODEL"),
    GETDATA_GLBUDGETMODEL(564, "GETDATA_GLBUDGETMODEL"),
    VALIDATEFIELD_GLBUDGETMODEL(565, "VALIDATEFIELD_GLBUDGETMODEL"),
    //GLBudgetLines
    INSERT_GLBUDGETLINES(580, "INSERT_GLBUDGETLINES"),
    UPDATE_GLBUDGETLINES(581, "UPDATE_GLBUDGETLINES"),
    DELETE_GLBUDGETLINES(582, "DELETE_GLBUDGETLINES"),
    GETNUMROWS_GLBUDGETLINES(583, "GETNUMROWS_GLBUDGETLINES"),
    GETDATA_GLBUDGETLINES(584, "GETDATA_GLBUDGETLINES"),
    VALIDATEFIELD_GLBUDGETLINES(585, "VALIDATEFIELD_GLBUDGETLINES"),
    GET_ACCOUNTS(586, "GET_ACCOUNTS"),
    //GLBudgetPeriod
    INSERT_GLBUDGETPERIOD(600, "INSERT_GLBUDGETPERIOD"),
    UPDATE_GLBUDGETPERIOD(601, "UPDATE_GLBUDGETPERIOD"),
    DELETE_GLBUDGETPERIOD(602, "DELETE_GLBUDGETPERIOD"),
    GETNUMROWS_GLBUDGETPERIOD(603, "GETNUMROWS_GLBUDGETPERIOD"),
    GETDATA_GLBUDGETPERIOD(604, "GETDATA_GLBUDGETPERIOD"),
    VALIDATEFIELD_GLBUDGETPERIOD(605, "VALIDATEFIELD_GLBUDGETPERIOD"),
    SPLIT_AMOUNTS(606, "SPLIT_AMOUNTS"),
    //GLBudgetLinesDS
    INSERT_GLBUDGETLINESDS(800, "INSERT_GLBUDGETLINESDS"),
    UPDATE_GLBUDGETLINESDS(801, "UPDATE_GLBUDGETLINESDS"),
    DELETE_GLBUDGETLINESDS(802, "DELETE_GLBUDGETLINESDS"),
    GETNUMROWS_GLBUDGETLINESDS(803, "GETNUMROWS_GLBUDGETLINESDS"),
    GETDATA_GLBUDGETLINESDS(804, "GETDATA_GLBUDGETLINESDS"),
    VALIDATEFIELD_GLBUDGETLINESDS(805, "VALIDATEFIELD_GLBUDGETLINESDS"),
    //GLTransactionDaySummary
    INSERT_GLTRANSACTIONDAYSUMMARY(1000, "INSERT_GLTRANSACTIONDAYSUMMARY"),
    UPDATE_GLTRANSACTIONDAYSUMMARY(1001, "UPDATE_GLTRANSACTIONDAYSUMMARY"),
    DELETE_GLTRANSACTIONDAYSUMMARY(1002, "DELETE_GLTRANSACTIONDAYSUMMARY"),
    GETNUMROWS_GLTRANSACTIONDAYSUMMARY(1003, "GETNUMROWS_GLTRANSACTIONDAYSUMMARY"),
    GETDATA_GLTRANSACTIONDAYSUMMARY(1004, "GETDATA_GLTRANSACTIONDAYSUMMARY"),
    VALIDATEFIELD_GLTRANSACTIONDAYSUMMARY(1005, "VALIDATEFIELD_GLTRANSACTIONDAYSUMMARY"),
    //GLParameters
    INSERT_GLPARAMETERS(1200, "INSERT_GLPARAMETERS"),
    UPDATE_GLPARAMETERS(1201, "UPDATE_GLPARAMETERS"),
    DELETE_GLPARAMETERS(1202, "DELETE_GLPARAMETERS"),
    GETNUMROWS_GLPARAMETERS(1203, "GETNUMROWS_GLPARAMETERS"),
    GETDATA_GLPARAMETERS(1204, "GETDATA_GLPARAMETERS"),
    VALIDATEFIELD_GLPARAMETERS(1205, "VALIDATEFIELD_GLPARAMETERS"),
    //GL Chart Of Accounts DS
    INSERT_GLCHARTOFACCOUNTSDS(1220, "INSERT_GLCHARTOFACCOUNTSDS"),
    UPDATE_GLCHARTOFACCOUNTSDS(1221, "UPDATE_GLCHARTOFACCOUNTSDS"),
    DELETE_GLCHARTOFACCOUNTSDS(1222, "DELETE_GLCHARTOFACCOUNTSDS"),
    GETNUMROWS_GLCHARTOFACCOUNTSDS(1223, "GETNUMROWS_GLCHARTOFACCOUNTSDS"),
    GETDATA_GLCHARTOFACCOUNTSDS(1224, "GETDATA_GLCHARTOFACCOUNTSDS"),
    VALIDATEFIELD_GLCHARTOFACCOUNTSDS(1225, "VALIDATEFIELD_GLCHARTOFACCOUNTSDS"),
    //GL Journal LinesDS
    INSERT_GLJOURNALLINESDS(1240, "INSERT_GLJOURNALLINESDS"),
    UPDATE_GLJOURNALLINESDS(1241, "UPDATE_GLJOURNALLINESDS"),
    DELETE_GLJOURNALLINESDS(1242, "DELETE_GLJOURNALLINESDS"),
    GETNUMROWS_GLJOURNALLINESDS(1243, "GETNUMROWS_GLJOURNALLINESDS"),
    GETDATA_GLJOURNALLINESDS(1244, "GETDATA_GLJOURNALLINESDS"),
    VALIDATEFIELD_GLJOURNALLINESDS(1245, "VALIDATEFIELD_GLJOURNALLINESDS"),
    //Year-End
    PROCESS_YEAR_END(1260, "PROCESS_YEAR_END");
    //Enum variables
    final int id;
    final String label;

    /** Creates a new instance of ServerCreditorsMethods */
    ServerGLMethods(final int id, final String label) {
        this.id = id;
        this.label = label;
    }

    public int getId() {
        return id;
    }

    @Override
    public String toString() {
        return label;
    }

    public static ServerGLMethods fromString(
            final String str) {
        for (ServerGLMethods e : ServerGLMethods.values()) {
            if (e.toString().equalsIgnoreCase(str)) {
                return e;
            }

        }
        return null;
    }

    public static ServerGLMethods fromId(
            final int id) {
        for (ServerGLMethods e : ServerGLMethods.values()) {
            if (e.id == id) {
                return e;
            }

        }
        return null;
    }

    public enumEMCModules getEMCModule() {
        return enumEMCModules.GENERAL_LEDGER;
    }
}
