/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package emc.methods.trec;

import emc.enums.modules.enumEMCModules;
import emc.methods.EMCMethodEnum;

/**
 *
 * @author wikus
 */
public enum ServerTRECMethods implements EMCMethodEnum {

    //TRECColours
    INSERT_TRECCOLOURS(0, "INSERT_TRECCOLOURS"),
    UPDATE_TRECCOLOURS(1, "UPDATE_TRECCOLOURS"),
    DELETE_TRECCOLOURS(2, "DELETE_TRECCOLOURS"),
    GETNUMROWS_TRECCOLOURS(3, "GETNUMROWS_TRECCOLOURS"),
    GETDATA_TRECCOLOURS(4, "GETDATA_TRECCOLOURS"),
    VALIDATEFIELD_TRECCOLOURS(5, "VALIDATEFIELD_TRECCOLOURS"),
    //TRECForms
    INSERT_TRECFORMS(20, "INSERT_TRECFORMS"),
    UPDATE_TRECFORMS(21, "UPDATE_TRECFORMS"),
    DELETE_TRECFORMS(22, "DELETE_TRECFORMS"),
    GETNUMROWS_TRECFORMS(23, "GETNUMROWS_TRECFORMS"),
    GETDATA_TRECFORMS(24, "GETDATA_TRECFORMS"),
    VALIDATEFIELD_TRECFORMS(25, "VALIDATEFIELD_TRECFORMS"),
    //TRECOdours
    INSERT_TRECODOURS(40, "INSERT_TRECODOURS"),
    UPDATE_TRECODOURS(41, "UPDATE_TRECODOURS"),
    DELETE_TRECODOURS(42, "DELETE_TRECODOURS"),
    GETNUMROWS_TRECODOURS(43, "GETNUMROWS_TRECODOURS"),
    GETDATA_TRECODOURS(44, "GETDATA_TRECODOURS"),
    VALIDATEFIELD_TRECODOURS(45, "VALIDATEFIELD_TRECODOURS"),
    //TRECTrecCardsMaster
    INSERT_TRECTRECCARDSMASTER(60, "INSERT_TRECTRECCARDSMASTER"),
    UPDATE_TRECTRECCARDSMASTER(61, "UPDATE_TRECTRECCARDSMASTER"),
    DELETE_TRECTRECCARDSMASTER(62, "DELETE_TRECTRECCARDSMASTER"),
    GETNUMROWS_TRECTRECCARDSMASTER(63, "GETNUMROWS_TRECTRECCARDSMASTER"),
    GETDATA_TRECTRECCARDSMASTER(64, "GETDATA_TRECTRECCARDSMASTER"),
    VALIDATEFIELD_TRECTRECCARDSMASTER(65, "VALIDATEFIELD_TRECTRECCARDSMASTER"),
    EXPORT_TREC_DATA(66, "EXPORT_TREC_DATA"),
    IMPORT_TREC_DATA(67, "IMPORT_TREC_DATA"),
    //TRECTrecCardsLines
    INSERT_TRECTRECCARDSLINES(80, "INSERT_TRECTRECCARDSLINES"),
    UPDATE_TRECTRECCARDSLINES(81, "UPDATE_TRECTRECCARDSLINES"),
    DELETE_TRECTRECCARDSLINES(82, "DELETE_TRECTRECCARDSLINES"),
    GETNUMROWS_TRECTRECCARDSLINES(83, "GETNUMROWS_TRECTRECCARDSLINES"),
    GETDATA_TRECTRECCARDSLINES(84, "GETDATA_TRECTRECCARDSLINES"),
    VALIDATEFIELD_TRECTRECCARDSLINES(85, "VALIDATEFIELD_TRECTRECCARDSLINES"),
    PRINT_TREC(86, "PRINT_TREC"),
    FIND_PACKING_GROUP(88, "FIND_PACKING_GROUP"),
    PRINT_SINGLE_TREC(89, "PRINT_SINGLE_TREC"),
    UPDATE_LINE_FIELDS(90, "UPDATE_LINE_FIELDS"),
    APPROVE_TREC(91, "APPROVE_TREC"),
    PRINT_SINGLE_TREC_TEMPLATE(92, "PRINT_SINGLE_TREC_TEMPLATE"),
    PRINT_PLACARD(93, "PRINT_PLACARD"),
    //TRECTrecCardsLinesDS
    INSERT_TRECTRECCARDSLINESDS(100, "INSERT_TRECTRECCARDSLINESDS"),
    UPDATE_TRECTRECCARDSLINESDS(101, "UPDATE_TRECTRECCARDSLINESDS"),
    DELETE_TRECTRECCARDSLINESDS(102, "DELETE_TRECTRECCARDSLINESDS"),
    GETNUMROWS_TRECTRECCARDSLINESDS(103, "GETNUMROWS_TRECTRECCARDSLINESDS"),
    GETDATA_TRECTRECCARDSLINESDS(104, "GETDATA_TRECTRECCARDSLINESDS"),
    VALIDATEFIELD_TRECTRECCARDSLINESDS(105, "VALIDATEFIELD_TRECTRECCARDSLINESDS"),
    VALIDATE_PACKING_GROUP(106, "VALIDATE_PACKING_GROUP"),
    //TRECClasses
    INSERT_TRECCLASSES(120, "INSERT_TRECCLASSES"),
    UPDATE_TRECCLASSES(121, "UPDATE_TRECCLASSES"),
    DELETE_TRECCLASSES(122, "DELETE_TRECCLASSES"),
    GETNUMROWS_TRECCLASSES(123, "GETNUMROWS_TRECCLASSES"),
    GETDATA_TRECCLASSES(124, "GETDATA_TRECCLASSES"),
    VALIDATEFIELD_TRECCLASSES(125, "VALIDATEFIELD_TRECCLASSES"),
    //TRECPhraseTypes
    INSERT_TRECPHRASETYPES(140, "INSERT_TRECPHRASETYPES"),
    UPDATE_TRECPHRASETYPES(141, "UPDATE_TRECPHRASETYPES"),
    DELETE_TRECPHRASETYPES(142, "DELETE_TRECPHRASETYPES"),
    GETNUMROWS_TRECPHRASETYPES(143, "GETNUMROWS_TRECPHRASETYPES"),
    GETDATA_TRECPHRASETYPES(144, "GETDATA_TRECPHRASETYPES"),
    VALIDATEFIELD_TRECPHRASETYPES(145, "VALIDATEFIELD_TRECPHRASETYPES"),
    //TRECPhrases
    INSERT_TRECPHRASES(160, "INSERT_TRECPHRASES"),
    UPDATE_TRECPHRASES(161, "UPDATE_TRECPHRASES"),
    DELETE_TRECPHRASES(162, "DELETE_TRECPHRASES"),
    GETNUMROWS_TRECPHRASES(163, "GETNUMROWS_TRECPHRASES"),
    GETDATA_TRECPHRASES(164, "GETDATA_TRECPHRASES"),
    VALIDATEFIELD_TRECPHRASES(165, "VALIDATEFIELD_TRECPHRASES"),
    //TRECTrecTypes
    INSERT_TRECTRECTYPES(180, "INSERT_TRECTRECTYPES"),
    UPDATE_TRECTRECTYPES(181, "UPDATE_TRECTRECTYPES"),
    DELETE_TRECTRECTYPES(182, "DELETE_TRECTRECTYPES"),
    GETNUMROWS_TRECTRECTYPES(183, "GETNUMROWS_TRECTRECTYPES"),
    GETDATA_TRECTRECTYPES(184, "GETDATA_TRECTRECTYPES"),
    VALIDATEFIELD_TRECTRECTYPES(185, "VALIDATEFIELD_TRECTRECTYPES"),
    UPDATE_ENC_PHRASES(186, "UPDATE_ENC_PHRASES"),
    CHECK_TREC_PHRASES(187, "CHECK_TREC_PHRASES"),
    //TRECPhraseCombinations
    INSERT_TRECPHRASECOMBINATIONS(190, "INSERT_TRECPHRASECOMBINATIONS"),
    UPDATE_TRECPHRASECOMBINATIONS(191, "UPDATE_TRECPHRASECOMBINATIONS"),
    DELETE_TRECPHRASECOMBINATIONS(192, "DELETE_TRECPHRASECOMBINATIONS"),
    GETNUMROWS_TRECPHRASECOMBINATIONS(193, "GETNUMROWS_TRECPHRASECOMBINATIONS"),
    GETDATA_TRECPHRASECOMBINATIONS(194, "GETDATA_TRECPHRASECOMBINATIONS"),
    VALIDATEFIELD_TRECPHRASECOMBINATIONS(195, "VALIDATEFIELD_TRECPHRASECOMBINATIONS"),
    UPDATE_ENC_PHRASECOMBINATIONS(196, "UPDATE_ENC_PHRASECOMBINATIONS"),
    //TRECChemicals
    INSERT_TRECCHEMICALS(200, "INSERT_TRECCHEMICALS"),
    UPDATE_TRECCHEMICALS(201, "UPDATE_TRECCHEMICALS"),
    DELETE_TRECCHEMICALS(202, "DELETE_TRECCHEMICALS"),
    GETNUMROWS_TRECCHEMICALS(203, "GETNUMROWS_TRECCHEMICALS"),
    GETDATA_TRECCHEMICALS(204, "GETDATA_TRECCHEMICALS"),
    VALIDATEFIELD_TRECCHEMICALS(205, "VALIDATEFIELD_TRECCHEMICALS"),
    UPDATE_ENC_CHEMICALS(206, "UPDATE_ENC_CHEMICALS"),
    RESTRUCTURE_CHEMICALS(207, "RESTRUCTURE_CHEMICALS"),
    FIX_CHEMICALS(208, "FIX_CHEMICALS"),
    VALIDATE_CHEMICALS_PHRASE(209, "VALIDATE_CHEMICALS_PHRASE"),
    CHECK_TREC_CHEMICALS(210, "CHECK_TREC_CHEMICALS"),
    //TRECParameters
    INSERT_TRECPARAMETERS(220, "INSERT_TRECPARAMETERS"),
    UPDATE_TRECPARAMETERS(221, "UPDATE_TRECPARAMETERS"),
    DELETE_TRECPARAMETERS(222, "DELETE_TRECPARAMETERS"),
    GETNUMROWS_TRECPARAMETERS(223, "GETNUMROWS_TRECPARAMETERS"),
    GETDATA_TRECPARAMETERS(224, "GETDATA_TRECPARAMETERS"),
    VALIDATEFIELD_TRECPARAMETERS(225, "VALIDATEFIELD_TRECPARAMETERS"),
    GET_MAXPHRASES(226,"GET_MAXPHRASES"),
    //TRECLoadCompatibility
    INSERT_TRECLOADCOMPATIBILITY(240, "INSERT_TRECLOADCOMPATIBILITY"),
    UPDATE_TRECLOADCOMPATIBILITY(241, "UPDATE_TRECLOADCOMPATIBILITY"),
    DELETE_TRECLOADCOMPATIBILITY(242, "DELETE_TRECLOADCOMPATIBILITY"),
    GETNUMROWS_TRECLOADCOMPATIBILITY(243, "GETNUMROWS_TRECLOADCOMPATIBILITY"),
    GETDATA_TRECLOADCOMPATIBILITY(244, "GETDATA_TRECLOADCOMPATIBILITY"),
    VALIDATEFIELD_TRECLOADCOMPATIBILITY(245, "VALIDATEFIELD_TRECLOADCOMPATIBILITY"),
    //TRECCargoCheckMaster
    INSERT_TRECCARGOCHECKMASTER(260, "INSERT_TRECCARGOCHECKMASTER"),
    UPDATE_TRECCARGOCHECKMASTER(261, "UPDATE_TRECCARGOCHECKMASTER"),
    DELETE_TRECCARGOCHECKMASTER(262, "DELETE_TRECCARGOCHECKMASTER"),
    GETNUMROWS_TRECCARGOCHECKMASTER(263, "GETNUMROWS_TRECCARGOCHECKMASTER"),
    GETDATA_TRECCARGOCHECKMASTER(264, "GETDATA_TRECCARGOCHECKMASTER"),
    VALIDATEFIELD_TRECCARGOCHECKMASTER(265, "VALIDATEFIELD_TRECCARGOCHECKMASTER"),
    //TRECCargoCheckLines
    INSERT_TRECCARGOCHECKLINES(280, "INSERT_TRECCARGOCHECKLINES"),
    UPDATE_TRECCARGOCHECKLINES(281, "UPDATE_TRECCARGOCHECKLINES"),
    DELETE_TRECCARGOCHECKLINES(282, "DELETE_TRECCARGOCHECKLINES"),
    GETNUMROWS_TRECCARGOCHECKLINES(283, "GETNUMROWS_TRECCARGOCHECKLINES"),
    GETDATA_TRECCARGOCHECKLINES(284, "GETDATA_TRECCARGOCHECKLINES"),
    VALIDATEFIELD_TRECCARGOCHECKLINES(285, "VALIDATEFIELD_TRECCARGOCHECKLINES"),
    //PRINT_CARGO_CHECK_REPORT
    PRINT_CARGO_CHECK_REPORT(286, "PRINT_CARGO_CHECK_REPORT"),
    //TRECCustomerChemicals
    INSERT_TRECCUSTOMERCHEMICALS(300, "INSERT_TRECCUSTOMERCHEMICALS"),
    UPDATE_TRECCUSTOMERCHEMICALS(301, "UPDATE_TRECCUSTOMERCHEMICALS"),
    DELETE_TRECCUSTOMERCHEMICALS(302, "DELETE_TRECCUSTOMERCHEMICALS"),
    GETNUMROWS_TRECCUSTOMERCHEMICALS(303, "GETNUMROWS_TRECCUSTOMERCHEMICALS"),
    GETDATA_TRECCUSTOMERCHEMICALS(304, "GETDATA_TRECCUSTOMERCHEMICALS"),
    VALIDATEFIELD_TRECCUSTOMERCHEMICALS(305, "VALIDATEFIELD_TRECCUSTOMERCHEMICALS"),
    UPDATE_ENC_CUSTOMER_CHEMICALS(306, "UPDATE_ENC_CUSTOMER_CHEMICALS"),
    CREATE_CUSTOMER_CHEMICALS(307, "CREATE_CUSTOMER_CHEMICALS"),
    ENCRYPT_CUSTOMER_CHEMICALS(308, "ENCRYPT_CUSTOMER_CHEMICALS"),
    FETCH_CUSTOMER_CHEMICALS(309, "FETCH_CUSTOMER_CHEMICALS"),
    FETCH_PHRASES_FOR_CHEMICAL(310, "FETCH_PHRASES_FOR_CHEMICAL"),
    RESET_CUSTOMER_CHEMICAL(311, "RESET_CUSTOMER_CHEMICAL"),
    FETCH_PHRASES_FOR_CHEMICAL_NEW(312, "FETCH_PHRASES_FOR_CHEMICAL_NEW"),
    FETCH_E_PHRASES_FOR_CHEMICAL_NEW(313, "FETCH_E_PHRASES_FOR_CHEMICAL_NEW"),
    //TRECWebLogic
    TRECWEBINSFETCHMASTER(321, "TRECWEBINSFETCHMASTER"),
    TRECWEBUPDATECARDSMASTER(322, "TRECWEBUPDATECARDSMASTER"),
    CREATE_UPDATE_BASKET_WEB(323, "CREATE_UPDATE_BASKET_WEB"),
    CREATE_UPDATE_DEBTORS_LINES(324, "CREATE_UPDATE_DEBTORS_LINES"),
    FETCH_TREC_CARDS_LINES(325, "FETCH_TREC_CARDS_LINES"),
    CREATE_DEBTORS_INVOICE(326, "CREATE_DEBTORS_INVOICE"),
    DELETE_BASKET_LINE(327, "DELETE_BASKET_LINE"),
    EMAIL_CUSTOMER_INVOICE(328, "EMAIL_CUSTOMER_INVOICE"),
    UPDATE_BASKET_MASTER(329, "UPDATE_BASKET_MASTER"),
    TRECWEBUPDATECARDLINES(320, "TRECWEBUPDATECARDLINES"),
    UPDATE_DEBTORS_BASKET_LINES(319, "UPDATE_DEBTORS_BASKET_LINES"),
    REMOVE_DEBTORS_BASKET_LINE(318, "REMOVE_DEBTORS_BASKET_LINE"),
    //TREC Web Printer Intergration
    UPDATE_BASKET_LINES_PRINT_QTY(330, "UPDATE_BASKET_LINES_PRINT_QTY"),
    GET_PHRASES_STRING(331, "GET_PHRASES_STRING"),
    GET_TREC_CARD_DATASET(332, "getTrecCardDataset"),
    GET_INVOICE_DATE(333, "GET_INVOICE_DATE"),
      //TRECErgMaster
    INSERT_TRECERGMASTER(341, "INSERT_TRECERGMASTER"),
    UPDATE_TRECERGMASTER(342, "UPDATE_TRECERGMASTER"),
    DELETE_TRECERGMASTER(343, "DELETE_TRECERGMASTER"),
    GETNUMROWS_TRECERGMASTER(344, "GETNUMROWS_TRECERGMASTER"),
    GETDATA_TRECERGMASTER(345, "GETDATA_TRECERGMASTER"),
    VALIDATEFIELD_TRECERGMASTER(346, "VALIDATEFIELD_TRECERGMASTER"),
    // ERGPHRASES Report
    PRINT_ERG_PHRASES(360, "PRINT_ERG_PHRASES"),
    //Get packing group
    GET_PACKING_GROUP(370,"GET_PACKING_GROUP"),
    // TRECPREFERREDSHIPNAME
    INSERT_TRECPREFERREDSHIPNAME(391, "INSERT_TRECPREFERREDSHIPNAME"),
    UPDATE_TRECPREFERREDSHIPNAME(392, "UPDATE_TRECPREFERREDSHIPNAME"),
    DELETE_TRECPREFERREDSHIPNAME(393, "DELETE_TRECPREFERREDSHIPNAME"),
    GETNUMROWS_TRECPREFERREDSHIPNAME(394, "GETNUMROWS_TRECPREFERREDSHIPNAME"),
    GETDATA_TRECPREFERREDSHIPNAME(395, "GETDATA_TRECPREFERREDSHIPNAME"),
    VALIDATEFIELD_TRECPREFERREDSHIPNAME(396, "VALIDATEFIELD_TRECPREFERREDSHIPNAME"),
    GET_PREF_SHIPNAME(397,"ET_PREF_SHIPNAME");
    
    //Enum variables
    final int id;
    final String label;

    /**
     * Creates a new instance of  ServerTRECMethods
     */
    ServerTRECMethods(final int id, final String label) {
        this.id = id;
        this.label = label;
    }

    public int getId() {
        return id;
    }

    @Override
    public String toString() {
        return label;
    }

    public static ServerTRECMethods fromString(final String str) {
        for (ServerTRECMethods e : ServerTRECMethods.values()) {
            if (e.toString().equalsIgnoreCase(str)) {
                return e;
            }
        }
        return null;
    }

    public static ServerTRECMethods fromId(final int id) {
        for (ServerTRECMethods e : ServerTRECMethods.values()) {
            if (e.id == id) {
                return e;
            }
        }
        return null;
    }

    public enumEMCModules getEMCModule() {
        return enumEMCModules.TREC;
    }
}
