/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package emc.methods.sop;

import emc.enums.modules.enumEMCModules;
import emc.methods.EMCMethodEnum;

/**
 *
 * @author wikus
 */
public enum ServerSOPMethods implements EMCMethodEnum {

    //SOPCustomers
    INSERT_SOPCUSTOMERS(0, "INSERT_SOPCUSTOMERS"),
    UPDATE_SOPCUSTOMERS(1, "UPDATE_SOPCUSTOMERS"),
    DELETE_SOPCUSTOMERS(2, "DELETE_SOPCUSTOMERS"),
    GETNUMROWS_SOPCUSTOMERS(3, "GETNUMROWS_SOPCUSTOMERS"),
    GETDATA_SOPCUSTOMERS(4, "GETDATA_SOPCUSTOMERS"),
    VALIDATEFIELD_SOPCUSTOMERS(5, "VALIDATEFIELD_SOPCUSTOMERS"),
    POPULATE_CUSTOMER_FROM_PROSPECT(6, "POPULATE_CUSTOMER_FROM_PROSPECT"),
    GET_CUSTOMER(7, "GET_CUSTOMER"),
    GET_CUSTOMER_ACTIVITY(8, "GET_CUSTOMER_ACTIVITY"),
    GET_ADMIN_TOOL_CUSTOMER(9, "GET_ADMIN_TOOL_CUSTOMER"),
    CREATE_WEB_CUSTOMER(10, "CREATE_WEB_CUSTOMER"),
    FIND_WEB_CUSTOMER(11, "FIND_WEB_CUSTOMER"),
    CREATE_WEB_USER(12,"CREATE_WEB_USER"),
    //SOPCustomerGroup
    INSERT_SOPCUSTOMERGROUP(20, "INSERT_SOPCUSTOMERGROUP"),
    UPDATE_SOPCUSTOMERGROUP(21, "UPDATE_SOPCUSTOMERGROUP"),
    DELETE_SOPCUSTOMERGROUP(22, "DELETE_SOPCUSTOMERGROUP"),
    GETNUMROWS_SOPCUSTOMERGROUP(23, "GETNUMROWS_SOPCUSTOMERGROUP"),
    GETDATA_SOPCUSTOMERGROUP(24, "GETDATA_SOPCUSTOMERGROUP"),
    VALIDATEFIELD_SOPCUSTOMERGROUP(25, "VALIDATEFIELD_SOPCUSTOMERGROUP"),
    //SOPCustomerClassification1
    INSERT_SOPCUSTOMERCLASSIFICATION1(120, "INSERT_SOPCUSTOMERCLASSIFICATION1"),
    UPDATE_SOPCUSTOMERCLASSIFICATION1(121, "UPDATE_SOPCUSTOMERCLASSIFICATION1"),
    DELETE_SOPCUSTOMERCLASSIFICATION1(122, "DELETE_SOPCUSTOMERCLASSIFICATION1"),
    GETNUMROWS_SOPCUSTOMERCLASSIFICATION1(123, "GETNUMROWS_SOPCUSTOMERCLASSIFICATION1"),
    GETDATA_SOPCUSTOMERCLASSIFICATION1(124, "GETDATA_SOPCUSTOMERCLASSIFICATION1"),
    VALIDATEFIELD_SOPCUSTOMERCLASSIFICATION1(125, "VALIDATEFIELD_SOPCUSTOMERCLASSIFICATION1"),
    //SOPCustomerClassification2
    INSERT_SOPCUSTOMERCLASSIFICATION2(140, "INSERT_SOPCUSTOMERCLASSIFICATION2"),
    UPDATE_SOPCUSTOMERCLASSIFICATION2(141, "UPDATE_SOPCUSTOMERCLASSIFICATION2"),
    DELETE_SOPCUSTOMERCLASSIFICATION2(142, "DELETE_SOPCUSTOMERCLASSIFICATION2"),
    GETNUMROWS_SOPCUSTOMERCLASSIFICATION2(143, "GETNUMROWS_SOPCUSTOMERCLASSIFICATION2"),
    GETDATA_SOPCUSTOMERCLASSIFICATION2(144, "GETDATA_SOPCUSTOMERCLASSIFICATION2"),
    VALIDATEFIELD_SOPCUSTOMERCLASSIFICATION2(145, "VALIDATEFIELD_SOPCUSTOMERCLASSIFICATION2"),
    //SOPCustomerClassification3
    INSERT_SOPCUSTOMERCLASSIFICATION3(160, "INSERT_SOPCUSTOMERCLASSIFICATION3"),
    UPDATE_SOPCUSTOMERCLASSIFICATION3(161, "UPDATE_SOPCUSTOMERCLASSIFICATION3"),
    DELETE_SOPCUSTOMERCLASSIFICATION3(162, "DELETE_SOPCUSTOMERCLASSIFICATION3"),
    GETNUMROWS_SOPCUSTOMERCLASSIFICATION3(163, "GETNUMROWS_SOPCUSTOMERCLASSIFICATION3"),
    GETDATA_SOPCUSTOMERCLASSIFICATION3(164, "GETDATA_SOPCUSTOMERCLASSIFICATION3"),
    VALIDATEFIELD_SOPCUSTOMERCLASSIFICATION3(165, "VALIDATEFIELD_SOPCUSTOMERCLASSIFICATION3"),
    //SOPCustomerClassification4
    INSERT_SOPCUSTOMERCLASSIFICATION4(180, "INSERT_SOPCUSTOMERCLASSIFICATION4"),
    UPDATE_SOPCUSTOMERCLASSIFICATION4(181, "UPDATE_SOPCUSTOMERCLASSIFICATION4"),
    DELETE_SOPCUSTOMERCLASSIFICATION4(182, "DELETE_SOPCUSTOMERCLASSIFICATION4"),
    GETNUMROWS_SOPCUSTOMERCLASSIFICATION4(183, "GETNUMROWS_SOPCUSTOMERCLASSIFICATION4"),
    GETDATA_SOPCUSTOMERCLASSIFICATION4(184, "GETDATA_SOPCUSTOMERCLASSIFICATION4"),
    VALIDATEFIELD_SOPCUSTOMERCLASSIFICATION4(185, "VALIDATEFIELD_SOPCUSTOMERCLASSIFICATION4"),
    //SOPCustomerClassification5
    INSERT_SOPCUSTOMERCLASSIFICATION5(200, "INSERT_SOPCUSTOMERCLASSIFICATION5"),
    UPDATE_SOPCUSTOMERCLASSIFICATION5(201, "UPDATE_SOPCUSTOMERCLASSIFICATION5"),
    DELETE_SOPCUSTOMERCLASSIFICATION5(202, "DELETE_SOPCUSTOMERCLASSIFICATION5"),
    GETNUMROWS_SOPCUSTOMERCLASSIFICATION5(203, "GETNUMROWS_SOPCUSTOMERCLASSIFICATION5"),
    GETDATA_SOPCUSTOMERCLASSIFICATION5(204, "GETDATA_SOPCUSTOMERCLASSIFICATION5"),
    VALIDATEFIELD_SOPCUSTOMERCLASSIFICATION5(205, "VALIDATEFIELD_SOPCUSTOMERCLASSIFICATION5"),
    //SOPCustomerClassification6
    INSERT_SOPCUSTOMERCLASSIFICATION6(220, "INSERT_SOPCUSTOMERCLASSIFICATION6"),
    UPDATE_SOPCUSTOMERCLASSIFICATION6(221, "UPDATE_SOPCUSTOMERCLASSIFICATION6"),
    DELETE_SOPCUSTOMERCLASSIFICATION6(222, "DELETE_SOPCUSTOMERCLASSIFICATION6"),
    GETNUMROWS_SOPCUSTOMERCLASSIFICATION6(223, "GETNUMROWS_SOPCUSTOMERCLASSIFICATION6"),
    GETDATA_SOPCUSTOMERCLASSIFICATION6(224, "GETDATA_SOPCUSTOMERCLASSIFICATION6"),
    VALIDATEFIELD_SOPCUSTOMERCLASSIFICATION6(225, "VALIDATEFIELD_SOPCUSTOMERCLASSIFICATION6"),
    //Reports
    PRINT_SOP_OUTSTANDING_ORDERS(240, "PRINT_SOP_OUTSTANDING_ORDERS"),
    PRINT_SOP_OVERDUE_ORDERS(241, "PRINT_SOP_OVERDUE_ORDERS"),
    PRINT_SOP_SALES_ORDERS(242, "PRINT_SOP_SALES_ORDERS"),
    //SOPPriceArangements
    INSERT_SOPPRICEARANGEMENTS(260, "INSERT_SOPPRICEARANGEMENTS"),
    UPDATE_SOPPRICEARANGEMENTS(261, "UPDATE_SOPPRICEARANGEMENTS"),
    DELETE_SOPPRICEARANGEMENTS(262, "DELETE_SOPPRICEARANGEMENTS"),
    GETNUMROWS_SOPPRICEARANGEMENTS(263, "GETNUMROWS_SOPPRICEARANGEMENTS"),
    GETDATA_SOPPRICEARANGEMENTS(264, "GETDATA_SOPPRICEARANGEMENTS"),
    VALIDATEFIELD_SOPPRICEARANGEMENTS(265, "VALIDATEFIELD_SOPPRICEARANGEMENTS"),
    GET_PRICE(266, "GET_PRICE"),
    //SOPPriceArangementsDS
    INSERT_SOPPRICEARANGEMENTSDS(280, "INSERT_SOPPRICEARANGEMENTSDS"),
    UPDATE_SOPPRICEARANGEMENTSDS(281, "UPDATE_SOPPRICEARANGEMENTSDS"),
    DELETE_SOPPRICEARANGEMENTSDS(282, "DELETE_SOPPRICEARANGEMENTSDS"),
    GETNUMROWS_SOPPRICEARANGEMENTSDS(283, "GETNUMROWS_SOPPRICEARANGEMENTSDS"),
    GETDATA_SOPPRICEARANGEMENTSDS(284, "GETDATA_SOPPRICEARANGEMENTSDS"),
    VALIDATEFIELD_SOPPRICEARANGEMENTSDS(285, "VALIDATEFIELD_SOPPRICEARANGEMENTSDS"),
    IMPORT_PRICE_ARANGEMENTS(286, "IMPORT_PRICE_ARANGEMENTS"),
    //SOPParameters
    INSERT_SOPPARAMETERS(300, "INSERT_SOPPARAMETERS"),
    UPDATE_SOPPARAMETERS(301, "UPDATE_SOPPARAMETERS"),
    DELETE_SOPPARAMETERS(302, "DELETE_SOPPARAMETERS"),
    GETNUMROWS_SOPPARAMETERS(303, "GETNUMROWS_SOPPARAMETERS"),
    GETDATA_SOPPARAMETERS(304, "GETDATA_SOPPARAMETERS"),
    VALIDATEFIELD_SOPPARAMETERS(305, "VALIDATEFIELD_SOPPARAMETERS"),
    GET_SOPPARAMETER(306, "GET_SOPPARAMETER"),
    DISABLE_COMMISSION_FIELDS(307, "DISABLE_COMMISSION_FIELDS"),
    //SOPSalesRepGroups
    INSERT_SOPSALESREPGROUPS(320, "INSERT_SOPSALESREPGROUPS"),
    UPDATE_SOPSALESREPGROUPS(321, "UPDATE_SOPSALESREPGROUPS"),
    DELETE_SOPSALESREPGROUPS(322, "DELETE_SOPSALESREPGROUPS"),
    GETNUMROWS_SOPSALESREPGROUPS(323, "GETNUMROWS_SOPSALESREPGROUPS"),
    GETDATA_SOPSALESREPGROUPS(324, "GETDATA_SOPSALESREPGROUPS"),
    VALIDATEFIELD_SOPSALESREPGROUPS(325, "VALIDATEFIELD_SOPSALESREPGROUPS"),
    //SOPSalesRepGroupsDS
    INSERT_SOPSALESREPGROUPSDS(340, "INSERT_SOPSALESREPGROUPSDS"),
    UPDATE_SOPSALESREPGROUPSDS(341, "UPDATE_SOPSALESREPGROUPSDS"),
    DELETE_SOPSALESREPGROUPSDS(342, "DELETE_SOPSALESREPGROUPSDS"),
    GETNUMROWS_SOPSALESREPGROUPSDS(343, "GETNUMROWS_SOPSALESREPGROUPSDS"),
    GETDATA_SOPSALESREPGROUPSDS(344, "GETDATA_SOPSALESREPGROUPSDS"),
    VALIDATEFIELD_SOPSALESREPGROUPSDS(345, "VALIDATEFIELD_SOPSALESREPGROUPSDS"),
    //SOPSalesRepGroupsSetup
    INSERT_SOPSALESREPGROUPSSETUP(360, "INSERT_SOPSALESREPGROUPSSETUP"),
    UPDATE_SOPSALESREPGROUPSSETUP(361, "UPDATE_SOPSALESREPGROUPSSETUP"),
    DELETE_SOPSALESREPGROUPSSETUP(362, "DELETE_SOPSALESREPGROUPSSETUP"),
    GETNUMROWS_SOPSALESREPGROUPSSETUP(363, "GETNUMROWS_SOPSALESREPGROUPSSETUP"),
    GETDATA_SOPSALESREPGROUPSSETUP(364, "GETDATA_SOPSALESREPGROUPSSETUP"),
    VALIDATEFIELD_SOPSALESREPGROUPSSETUP(365, "VALIDATEFIELD_SOPSALESREPGROUPSSETUP"),
    //SOPSalesRepGroupsSetupDS
    INSERT_SOPSALESREPGROUPSETUPDS(380, "INSERT_SOPSALESREPGROUPSETUPDS"),
    UPDATE_SOPSALESREPGROUPSETUPDS(381, "UPDATE_SOPSALESREPGROUPSETUPDS"),
    DELETE_SOPSALESREPGROUPSETUPDS(382, "DELETE_SOPSALESREPGROUPSETUPDS"),
    GETNUMROWS_SOPSALESREPGROUPSETUPDS(383, "GETNUMROWS_SOPSALESREPGROUPSETUPDS"),
    GETDATA_SOPSALESREPGROUPSETUPDS(384, "GETDATA_SOPSALESREPGROUPSETUPDS"),
    VALIDATEFIELD_SOPSALESREPGROUPSETUPDS(385, "VALIDATEFIELD_SOPSALESREPGROUPSETUPDS"),
    //SOPSalesRepCommission
    INSERT_SOPSALESREPCOMMISSION(400, "INSERT_SOPSALESREPCOMMISSION"),
    UPDATE_SOPSALESREPCOMMISSION(401, "UPDATE_SOPSALESREPCOMMISSION"),
    DELETE_SOPSALESREPCOMMISSION(402, "DELETE_SOPSALESREPCOMMISSION"),
    GETNUMROWS_SOPSALESREPCOMMISSION(403, "GETNUMROWS_SOPSALESREPCOMMISSION"),
    GETDATA_SOPSALESREPCOMMISSION(404, "GETDATA_SOPSALESREPCOMMISSION"),
    VALIDATEFIELD_SOPSALESREPCOMMISSION(405, "VALIDATEFIELD_SOPSALESREPCOMMISSION"),
    GET_AVAILABLE_REPS(406, "GET_AVAILABLE_REPS"),
    POPULATE_SALES_REP_COMMISSION(407, "POPULATE_SALES_REP_COMMISSION"),
    MASS_UPDATE_COMMISSION(408, "MASS_UPDATE_COMMISSION"),
    GENERATE_COMMISSION_DATA(409, "GENERATE_COMMISSION_DATA"),
    GET_ALL_FIELD_VALUES(410, "GET_ALL_FIELD_VALUES"),
    VALIDATE_SELECTED_FIELD(411, "VALIDATE_SELECTED_FIELD"),
    SAVE_COMMISSION_WIZZARD(412, "SAVE_COMMISSION_WIZZARD"),
    LOAD_COMMISSION_WIZZARD(413, "LOAD_COMMISSION_WIZZARD"),
    DELETE_COMMISSION_WIZZARD(414, "DELETE_COMMISSION_WIZZARD"),
    FIND_COMMISSION_WIZZARD(415, "FIND_COMMISSION_WIZZARD"),
    VALIDATE_SALES_REP(416, "VALIDATE_SALES_REP"),
    //SOPSalesRepCommissionEnquiry
    INSERT_SOPSALESREPCOMMISSIONENQUIRY(420, "INSERT_SOPSALESREPCOMMISSIONENQUIRY"),
    UPDATE_SOPSALESREPCOMMISSIONENQUIRY(421, "UPDATE_SOPSALESREPCOMMISSIONENQUIRY"),
    DELETE_SOPSALESREPCOMMISSIONENQUIRY(422, "DELETE_SOPSALESREPCOMMISSIONENQUIRY"),
    GETNUMROWS_SOPSALESREPCOMMISSIONENQUIRY(423, "GETNUMROWS_SOPSALESREPCOMMISSIONENQUIRY"),
    GETDATA_SOPSALESREPCOMMISSIONENQUIRY(424, "GETDATA_SOPSALESREPCOMMISSIONENQUIRY"),
    VALIDATEFIELD_SOPSALESREPCOMMISSIONENQUIRY(425, "VALIDATEFIELD_SOPSALESREPCOMMISSIONENQUIRY"),
    //SOPSalesOrderPostLines
    INSERT_SOPSALESORDERPOSTLINES(480, "INSERT_SOPSALESORDERPOSTLINES"),
    UPDATE_SOPSALESORDERPOSTLINES(481, "UPDATE_SOPSALESORDERPOSTLINES"),
    DELETE_SOPSALESORDERPOSTLINES(482, "DELETE_SOPSALESORDERPOSTLINES"),
    GETNUMROWS_SOPSALESORDERPOSTLINES(483, "GETNUMROWS_SOPSALESORDERPOSTLINES"),
    GETDATA_SOPSALESORDERPOSTLINES(484, "GETDATA_SOPSALESORDERPOSTLINES"),
    VALIDATEFIELD_SOPSALESORDERPOSTLINES(485, "VALIDATEFIELD_SOPSALESORDERPOSTLINES"),
    //SOPSalesOrderPostLinesDS
    INSERT_SOPSALESORDERPOSTLINESDS(520, "INSERT_SOPSALESORDERPOSTLINESDS"),
    UPDATE_SOPSALESORDERPOSTLINESDS(521, "UPDATE_SOPSALESORDERPOSTLINESDS"),
    DELETE_SOPSALESORDERPOSTLINESDS(522, "DELETE_SOPSALESORDERPOSTLINESDS"),
    GETNUMROWS_SOPSALESORDERPOSTLINESDS(523, "GETNUMROWS_SOPSALESORDERPOSTLINESDS"),
    GETDATA_SOPSALESORDERPOSTLINESDS(524, "GETDATA_SOPSALESORDERPOSTLINESDS"),
    VALIDATEFIELD_SOPSALESORDERPOSTLINESDS(525, "VALIDATEFIELD_SOPSALESORDERPOSTLINESDS"),
    //SOPSalesOrderPostRegister
    INSERT_SOPSALESORDERPOSTREGISTER(620, "INSERT_SOPSALESORDERPOSTREGISTER"),
    UPDATE_SOPSALESORDERPOSTREGISTER(621, "UPDATE_SOPSALESORDERPOSTREGISTER"),
    DELETE_SOPSALESORDERPOSTREGISTER(622, "DELETE_SOPSALESORDERPOSTREGISTER"),
    GETNUMROWS_SOPSALESORDERPOSTREGISTER(623, "GETNUMROWS_SOPSALESORDERPOSTREGISTER"),
    GETDATA_SOPSALESORDERPOSTREGISTER(624, "GETDATA_SOPSALESORDERPOSTREGISTER"),
    VALIDATEFIELD_SOPSALESORDERPOSTREGISTER(625, "VALIDATEFIELD_SOPSALESORDERPOSTREGISTER"),
    //SOPSalesOrderCancelReason
    INSERT_SOPSALESORDERCANCELREASON(640, "INSERT_SOPSALESORDERCANCELREASON"),
    UPDATE_SOPSALESORDERCANCELREASON(641, "UPDATE_SOPSALESORDERCANCELREASON"),
    DELETE_SOPSALESORDERCANCELREASON(642, "DELETE_SOPSALESORDERCANCELREASON"),
    GETNUMROWS_SOPSALESORDERCANCELREASON(643, "GETNUMROWS_SOPSALESORDERCANCELREASON"),
    GETDATA_SOPSALESORDERCANCELREASON(644, "GETDATA_SOPSALESORDERCANCELREASON"),
    VALIDATEFIELD_SOPSALESORDERCANCELREASON(645, "VALIDATEFIELD_SOPSALESORDERCANCELREASON"),
    VALIDATE_CANCEL_REASON(646, "VALIDATE_CANCEL_REASON"),
    //SOPPriceChangeReason
    INSERT_SOPPRICECHANGEREASON(660, "INSERT_SOPPRICECHANGEREASON"),
    UPDATE_SOPPRICECHANGEREASON(661, "UPDATE_SOPPRICECHANGEREASON"),
    DELETE_SOPPRICECHANGEREASON(662, "DELETE_SOPPRICECHANGEREASON"),
    GETNUMROWS_SOPPRICECHANGEREASON(663, "GETNUMROWS_SOPPRICECHANGEREASON"),
    GETDATA_SOPPRICECHANGEREASON(664, "GETDATA_SOPPRICECHANGEREASON"),
    VALIDATEFIELD_SOPPRICECHANGEREASON(665, "VALIDATEFIELD_SOPPRICECHANGEREASON"),
    //Controll Sheet
    PRINT_SOP_CONTROLL_SHEET(700, "PRINT_SOP_CONTROLL_SHEET"),
    //SOP Discount Setup
    INSERT_SOPDISCOUNTSETUP(720, "INSERT_SOPDISCOUNTSETUP"),
    UPDATE_SOPDISCOUNTSETUP(721, "UPDATE_SOPDISCOUNTSETUP"),
    DELETE_SOPDISCOUNTSETUP(722, "DELETE_SOPDISCOUNTSETUP"),
    GETNUMROWS_SOPDISCOUNTSETUP(723, "GETNUMROWS_SOPDISCOUNTSETUP"),
    GETDATA_SOPDISCOUNTSETUP(724, "GETDATA_SOPDISCOUNTSETUP"),
    VALIDATEFIELD_SOPDISCOUNTSETUP(725, "VALIDATEFIELD_SOPDISCOUNTSETUP"),
    //SOP Discount Setup DS
    INSERT_SOPDISCOUNTSETUPDS(740, "INSERT_SOPDISCOUNTSETUPDS"),
    UPDATE_SOPDISCOUNTSETUPDS(741, "UPDATE_SOPDISCOUNTSETUPDS"),
    DELETE_SOPDISCOUNTSETUPDS(742, "DELETE_SOPDISCOUNTSETUPDS"),
    GETNUMROWS_SOPDISCOUNTSETUPDS(743, "GETNUMROWS_SOPDISCOUNTSETUPDS"),
    GETDATA_SOPDISCOUNTSETUPDS(744, "GETDATA_SOPDISCOUNTSETUPDS"),
    VALIDATEFIELD_SOPDISCOUNTSETUPDS(745, "VALIDATEFIELD_SOPDISCOUNTSETUPDS"),
    //SOPCustomerLabels
    INSERT_SOPCUSTOMERLABELS(880, "INSERT_SOPCUSTOMERLABELS"),
    UPDATE_SOPCUSTOMERLABELS(881, "UPDATE_SOPCUSTOMERLABELS"),
    DELETE_SOPCUSTOMERLABELS(882, "DELETE_SOPCUSTOMERLABELS"),
    GETNUMROWS_SOPCUSTOMERLABELS(883, "GETNUMROWS_SOPCUSTOMERLABELS"),
    GETDATA_SOPCUSTOMERLABELS(884, "GETDATA_SOPCUSTOMERLABELS"),
    VALIDATEFIELD_SOPCUSTOMERLABELS(885, "VALIDATEFIELD_SOPCUSTOMERLABELS"),
    FIND_CUSTOMER_LABLES_FOR_SO(886, "FIND_CUSTOMER_LABLES_FOR_SO"),
    //Blanket Order Status Enquiry DS
    INSERT_SOPBLANKETORDERSTATUSENQUIRYDS(900, "INSERT_SOPBLANKETORDERSTATUSENQUIRYDS"),
    UPDATE_SOPBLANKETORDERSTATUSENQUIRYDS(901, "UPDATE_SOPBLANKETORDERSTATUSENQUIRYDS"),
    DELETE_SOPBLANKETORDERSTATUSENQUIRYDS(902, "DELETE_SOPBLANKETORDERSTATUSENQUIRYDS"),
    GETNUMROWS_SOPBLANKETORDERSTATUSENQUIRYDS(903, "GETNUMROWS_SOPBLANKETORDERSTATUSENQUIRYDS"),
    GETDATA_SOPBLANKETORDERSTATUSENQUIRYDS(904, "GETDATA_SOPBLANKETORDERSTATUSENQUIRYDS"),
    VALIDATEFIELD_SOPBLANKETORDERSTATUSENQUIRYDS(905, "VALIDATEFIELD_SOPBLANKETORDERSTATUSENQUIRYDS"),
    //SOPStatusEnquirySummary
    INSERT_SOPSTATUSENQUIRYSUMMARY(920, "INSERT_SOPSTATUSENQUIRYSUMMARY"),
    UPDATE_SOPSTATUSENQUIRYSUMMARY(921, "UPDATE_SOPSTATUSENQUIRYSUMMARY"),
    DELETE_SOPSTATUSENQUIRYSUMMARY(922, "DELETE_SOPSTATUSENQUIRYSUMMARY"),
    GETNUMROWS_SOPSTATUSENQUIRYSUMMARY(923, "GETNUMROWS_SOPSTATUSENQUIRYSUMMARY"),
    GETDATA_SOPSTATUSENQUIRYSUMMARY(924, "GETDATA_SOPSTATUSENQUIRYSUMMARY"),
    VALIDATEFIELD_SOPSTATUSENQUIRYSUMMARY(925, "VALIDATEFIELD_SOPSTATUSENQUIRYSUMMARY"),
    POPULATE_SALES_STATUS_ENQUIRY(925, "POPULATE_SALES_STATUS_ENQUIRY"),
    //Commission Reports
    PRINT_DETAILED_COMMISSION_REPORT(940, "PRINT_DETAILED_COMMISSION_REPORT"),
    PRINT_COMMISSION_SUMMARY_REPORT(941, "PRINT_COMMISSION_SUMMARY_REPORT"),
    PRINT_COMMISSION_REPORT(942, "PRINT_COMMISSION_REPORT"),
    //Open Orders Report,
    PRINT_OPEN_SALES_ORDERS_REPORT(943, "PRINT_OPEN_SALES_ORDERS_REPORT"),
    PRINT_STOCK_AVAILABLE_FOR_SALE(944, "PRINT_STOCK_AVAILABLE_FOR_SALE"),
    //SOPSalesEnquiry
    INSERT_SOPSALESENQUIRY(1000, "INSERT_SOPSALESENQUIRY"),
    UPDATE_SOPSALESENQUIRY(1001, "UPDATE_SOPSALESENQUIRY"),
    DELETE_SOPSALESENQUIRY(1002, "DELETE_SOPSALESENQUIRY"),
    GETNUMROWS_SOPSALESENQUIRY(1003, "GETNUMROWS_SOPSALESENQUIRY"),
    GETDATA_SOPSALESENQUIRY(1004, "GETDATA_SOPSALESENQUIRY"),
    VALIDATEFIELD_SOPSALESENQUIRY(1005, "VALIDATEFIELD_SOPSALESENQUIRY"),
    PREPARE_SOPSALESENQUIRY(1006, "PREPARE_SOPSALESENQUIRY"),
    POPULATE_SOPSALESENQUIRY(1007, "POPULATE_SOPSALESENQUIRY"),
    CLEANUP_SOPSALESENQUIRY(1008, "CLEANUP_SOPSALESENQUIRY"),
    //SOPPriceAuditTrail
    INSERT_SOPPRICEAUDITTRAIL(1020, "INSERT_SOPPRICEAUDITTRAIL"),
    UPDATE_SOPPRICEAUDITTRAIL(1021, "UPDATE_SOPPRICEAUDITTRAIL"),
    DELETE_SOPPRICEAUDITTRAIL(1022, "DELETE_SOPPRICEAUDITTRAIL"),
    GETNUMROWS_SOPPRICEAUDITTRAIL(1023, "GETNUMROWS_SOPPRICEAUDITTRAIL"),
    GETDATA_SOPPRICEAUDITTRAIL(1024, "GETDATA_SOPPRICEAUDITTRAIL"),
    VALIDATEFIELD_SOPPRICEAUDITTRAIL(1025, "VALIDATEFIELD_SOPPRICEAUDITTRAIL"),
    POPULATE_APPROVAL_HISTORY(1026, "POPULATE_APPROVAL_HISTORY"),
    POPULATE_CHANGE_HISTORY(1027, "POPULATE_CHANGE_HISTORY"),
    //SOPPriceAuditTrailDS
    INSERT_SOPPRICEAUDITTRAILDS(1040, "INSERT_SOPPRICEAUDITTRAILDS"),
    UPDATE_SOPPRICEAUDITTRAILDS(1041, "UPDATE_SOPPRICEAUDITTRAILDS"),
    DELETE_SOPPRICEAUDITTRAILDS(1042, "DELETE_SOPPRICEAUDITTRAILDS"),
    GETNUMROWS_SOPPRICEAUDITTRAILDS(1043, "GETNUMROWS_SOPPRICEAUDITTRAILDS"),
    GETDATA_SOPPRICEAUDITTRAILDS(1044, "GETDATA_SOPPRICEAUDITTRAILDS"),
    VALIDATEFIELD_SOPPRICEAUDITTRAILDS(1045, "VALIDATEFIELD_SOPPRICEAUDITTRAILDS"),
    //SOPCustomewr Lables
    PRINT_CUSTOMER_LABLES(1060, "PRINT_CUSTOMER_LABLES"),
    //Price Audit Trail Reports
    PRINT_PRICE_LIST_AUDIT_TRAIL(1080, "PRINT_PRICE_LIST_AUDIT_TRAIL"),
    PRINT_APPROVAL_AUDIT_TRAIL(1081, "PRINT_APPROVAL_AUDIT_TRAIL"),
    //Order Schedule Report
    PRINT_ORDER_SCHEDULE(1082, "PRINT_ORDER_SCHEDULE"),
    PRINT_ORDER_SCHEDULE_BY_ITEM(1083, "PRINT_ORDER_SCHEDULE_BY_ITEM"),
    PRINT_ROLLING_SALES_REPORT(1084, "PRINT_ROLLING_SALES_REPORT"),
    //SOPSalesOrderChangeDateReason
    INSERT_SOPSALESORDERCHANGEDATEREASON(1100, "INSERT_SOPSALESORDERCHANGEDATEREASON"),
    UPDATE_SOPSALESORDERCHANGEDATEREASON(1101, "UPDATE_SOPSALESORDERCHANGEDATEREASON"),
    DELETE_SOPSALESORDERCHANGEDATEREASON(1102, "DELETE_SOPSALESORDERCHANGEDATEREASON"),
    GETNUMROWS_SOPSALESORDERCHANGEDATEREASON(1103, "GETNUMROWS_SOPSALESORDERCHANGEDATEREASON"),
    GETDATA_SOPSALESORDERCHANGEDATEREASON(1104, "GETDATA_SOPSALESORDERCHANGEDATEREASON"),
    VALIDATEFIELD_SOPSALESORDERCHANGEDATEREASON(1105, "VALIDATEFIELD_SOPSALESORDERCHANGEDATEREASON"),
    //SOPSalesBySizeEnquiry
    INSERT_SOPSALESBYSIZEENQUIRY(1120, "INSERT_SOPSALESBYSIZEENQUIRY"),
    UPDATE_SOPSALESBYSIZEENQUIRY(1121, "UPDATE_SOPSALESBYSIZEENQUIRY"),
    DELETE_SOPSALESBYSIZEENQUIRY(1122, "DELETE_SOPSALESBYSIZEENQUIRY"),
    GETNUMROWS_SOPSALESBYSIZEENQUIRY(1123, "GETNUMROWS_SOPSALESBYSIZEENQUIRY"),
    GETDATA_SOPSALESBYSIZEENQUIRY(1124, "GETDATA_SOPSALESBYSIZEENQUIRY"),
    VALIDATEFIELD_SOPSALESBYSIZEENQUIRY(1125, "VALIDATEFIELD_SOPSALESBYSIZEENQUIRY"),
    POPULATE_SALES_BY_SIZE_ENQUIRY(1126, "POPULATE_SALES_BY_SIZE_ENQUIRY"),
    CLEAR_SALES_BY_SIZE_ENQUIRY(1127, "CLEAR_SALES_BY_SIZE_ENQUIRY"),
    //SOPSalesBySizeEnquiryDS
    INSERT_SOPSALESBYSIZEENQUIRYDS(1140, "INSERT_SOPSALESBYSIZEENQUIRYDS"),
    UPDATE_SOPSALESBYSIZEENQUIRYDS(1141, "UPDATE_SOPSALESBYSIZEENQUIRYDS"),
    DELETE_SOPSALESBYSIZEENQUIRYDS(1142, "DELETE_SOPSALESBYSIZEENQUIRYDS"),
    GETNUMROWS_SOPSALESBYSIZEENQUIRYDS(1143, "GETNUMROWS_SOPSALESBYSIZEENQUIRYDS"),
    GETDATA_SOPSALESBYSIZEENQUIRYDS(1144, "GETDATA_SOPSALESBYSIZEENQUIRYDS"),
    VALIDATEFIELD_SOPSALESBYSIZEENQUIRYDS(1145, "VALIDATEFIELD_SOPSALESBYSIZEENQUIRYDS"),
    //SOPSalesRepCommission
    INSERT_SOPSALESREPCOMMISSIONDS(1180, "INSERT_SOPSALESREPCOMMISSIONDS"),
    UPDATE_SOPSALESREPCOMMISSIONDS(1181, "UPDATE_SOPSALESREPCOMMISSIONDS"),
    DELETE_SOPSALESREPCOMMISSIONDS(1182, "DELETE_SOPSALESREPCOMMISSIONDS"),
    GETNUMROWS_SOPSALESREPCOMMISSIONDS(1183, "GETNUMROWS_SOPSALESREPCOMMISSIONDS"),
    GETDATA_SOPSALESREPCOMMISSIONDS(1184, "GETDATA_SOPSALESREPCOMMISSIONDS"),
    VALIDATEFIELD_SOPSALESREPCOMMISSIONDS(1185, "VALIDATEFIELD_SOPSALESREPCOMMISSIONDS"),
    //SOPCustomerBySalesRep
    PRINT_SOPCUSTOMER_BY_SALES_REP_REPORT(1301, "PRINT_SOPCUSTOMER_BY_SALES_REP_REPORT");
    final int id;
    final String label;

    /**
     * Creates a new instance of ServerSOPMethods
     */
    ServerSOPMethods(final int id, final String label) {
        this.id = id;
        this.label = label;
    }

    public int getId() {
        return id;
    }

    @Override
    public String toString() {
        return label;
    }

    public static ServerSOPMethods fromString(final String str) {
        for (ServerSOPMethods e : ServerSOPMethods.values()) {
            if (e.toString().equalsIgnoreCase(str)) {
                return e;
            }
        }
        return null;
    }

    public static ServerSOPMethods fromId(final int id) {
        for (ServerSOPMethods e : ServerSOPMethods.values()) {
            if (e.id == id) {
                return e;
            }
        }
        return null;
    }

    public enumEMCModules getEMCModule() {
        return enumEMCModules.SOP;
    }
}
