/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package emc.methods.pop;

import emc.enums.modules.enumEMCModules;
import emc.methods.EMCMethodEnum;

/**
 *
 * @author riaan
 */
public enum ServerPOPMethods implements EMCMethodEnum {

    //Suppliers
    INSERT_POPSUPPLIERS(0, "INSERT_POPSUPPLIERS"),
    UPDATE_POPSUPPLIERS(1, "UPDATE_POPSUPPLIERS"),
    DELETE_POPSUPPLIERS(2, "DELETE_POPSUPPLIERS"),
    GETNUMROWS_POPSUPPLIERS(3, "GETNUMROWS_POPSUPPLIERS"),
    GETDATA_POPSUPPLIERS(4, "GETDATA_POPSUPPLIERS"),
    VALIDATEFIELD_POPSUPPLIERS(5, "VALIDATEFIELD_POPSUPPLIERS"),
    //Supplier Groups
    INSERT_POPSUPPLIERGROUP(20, "INSERT_POPSUPPLIERGROUP"),
    UPDATE_POPSUPPLIERGROUP(21, "UPDATE_POPSUPPLIERGROUP"),
    DELETE_POPSUPPLIERGROUP(22, "DELETE_POPSUPPLIERGROUP"),
    GETNUMROWS_POPSUPPLIERGROUP(23, "GETNUMROWS_POPSUPPLIERGROUP"),
    GETDATA_POPSUPPLIERGROUP(24, "GETDATA_POPSUPPLIERGROUP"),
    VALIDATEFIELD_POPSUPPLIERGROUP(25, "VALIDATEFIELD_POPSUPPLIERGROUP"),
    //Price Groups
    INSERT_POPPRICEGROUP(40, "INSERT_POPPRICEGROUP"),
    UPDATE_POPPRICEGROUP(41, "UPDATE_POPPRICEGROUP"),
    DELETE_POPPRICEGROUP(42, "DELETE_POPPRICEGROUP"),
    GETNUMROWS_POPPRICEGROUP(43, "GETNUMROWS_POPPRICEGROUP"),
    GETDATA_POPPRICEGROUP(44, "GETDATA_POPPRICEGROUP"),
    VALIDATEFIELD_POPPRICEGROUP(45, "VALIDATEFIELD_POPPRICEGROUP"),
    //Discount Groups
    INSERT_POPDISCOUNTGROUP(60, "INSERT_POPDISCOUNTGROUP"),
    UPDATE_POPDISCOUNTGROUP(61, "UPDATE_POPDISCOUNTGROUP"),
    DELETE_POPDISCOUNTGROUP(62, "DELETE_POPDISCOUNTGROUP"),
    GETNUMROWS_POPDISCOUNTGROUP(63, "GETNUMROWS_POPDISCOUNTGROUP"),
    GETDATA_POPDISCOUNTGROUP(64, "GETDATA_POPDISCOUNTGROUP"),
    VALIDATEFIELD_POPDISCOUNTGROUP(65, "VALIDATEFIELD_POPDISCOUNTGROUP"),
    //Extra Charge Groups
    INSERT_POPEXTRACHARGEGROUP(80, "INSERT_POPEXTRACHARGEGROUP"),
    UPDATE_POPEXTRACHARGEGROUP(81, "UPDATE_POPEXTRACHARGEGROUP"),
    DELETE_POPEXTRACHARGEGROUP(82, "DELETE_POPEXTRACHARGEGROUP"),
    GETNUMROWS_POPEXTRACHARGEGROUP(83, "GETNUMROWS_POPEXTRACHARGEGROUP"),
    GETDATA_POPEXTRACHARGEGROUP(84, "GETDATA_POPEXTRACHARGEGROUP"),
    VALIDATEFIELD_POPEXTRACHARGEGROUP(85, "VALIDATEFIELD_POPEXTRACHARGEGROUP"),
    //Purchase order master
    INSERT_POPPURCHASEORDERMASTER(140, "INSERT_POPPURCHASEORDERMASTER"),
    UPDATE_POPPURCHASEORDERMASTER(141, "UPDATE_POPPURCHASEORDERMASTER"),
    DELETE_POPPURCHASEORDERMASTER(142, "DELETE_POPPURCHASEORDERMASTER"),
    GETNUMROWS_POPPURCHASEORDERMASTER(143, "GETNUMROWS_POPPURCHASEORDERMASTER"),
    GETDATA_POPPURCHASEORDERMASTER(144, "GETDATA_POPPURCHASEORDERMASTER"),
    VALIDATEFIELD_POPPURCHASEORDERMASTER(145, "VALIDATEFIELD_POPPURCHASEORDERMASTER"),
    APPROVE_PURCHASEORDER(146, "APPROVE_PURCHASEORDER"),
    UNAPPROVE_PURCHASEORDER(147, "UNAPPROVE_PURCHASEORDER"),
    UPDATE_LINES_DATE(148, "UPDATE_LINES_DATE"),
    CHECK_QC(149, "CHECK_QC"),
    //Purchase order lines
    INSERT_POPPURCHASEORDERLINES(160, "INSERT_POPPURCHASEORDERLINES"),
    UPDATE_POPPURCHASEORDERLINES(161, "UPDATE_POPPURCHASEORDERLINES"),
    DELETE_POPPURCHASEORDERLINES(162, "DELETE_POPPURCHASEORDERLINES"),
    GETNUMROWS_POPPURCHASEORDERLINES(163, "GETNUMROWS_POPPURCHASEORDERLINES"),
    GETDATA_POPPURCHASEORDERLINES(164, "GETDATA_POPPURCHASEORDERLINES"),
    VALIDATEFIELD_POPPURCHASEORDERLINES(165, "VALIDATEFIELD_POPPURCHASEORDERLINES"),
    SPLIT_PURCHASE_ORDER_LINE(166, "SPLIT_PURCHASE_ORDER_LINE"),
    //Creditors Supplier Received Journal Lines
    INSERT_POPSUPPLIERRECEIVEDJOURNALLINES(180, "INSERT_POPSUPPLIERRECEIVEDJOURNALLINES"),
    UPDATE_POPSUPPLIERRECEIVEDJOURNALLINES(181, "UPDATE_POPSUPPLIERRECEIVEDJOURNALLINES"),
    DELETE_POPSUPPLIERRECEIVEDJOURNALLINES(182, "DELETE_POPSUPPLIERRECEIVEDJOURNALLINES"),
    GETNUMROWS_POPSUPPLIERRECEIVEDJOURNALLINES(183, "GETNUMROWS_POPSUPPLIERRECEIVEDJOURNALLINES"),
    GETDATA_POPSUPPLIERRECEIVEDJOURNALLINES(184, "GETDATA_POPSUPPLIERRECEIVEDJOURNALLINES"),
    VALIDATEFIELD_POPSUPPLIERRECEIVEDJOURNALLINES(185, "VALIDATEFIELD_POPSUPPLIERRECEIVEDJOURNALLINES"),
    //Creditors Supplier Received Journal Master
    INSERT_POPSUPPLIERRECEIVEDJOURNALMASTER(200, "INSERT_POPSUPPLIERRECEIVEDJOURNALMASTER"),
    UPDATE_POPSUPPLIERRECEIVEDJOURNALMASTER(201, "UPDATE_POPSUPPLIERRECEIVEDJOURNALMASTER"),
    DELETE_POPSUPPLIERRECEIVEDJOURNALMASTER(202, "DELETE_POPSUPPLIERRECEIVEDJOURNALMASTER"),
    GETNUMROWS_POPSUPPLIERRECEIVEDJOURNALMASTER(203, "GETNUMROWS_POPSUPPLIERRECEIVEDJOURNALMASTER"),
    GETDATA_POPSUPPLIERRECEIVEDJOURNALMASTER(204, "GETDATA_POPSUPPLIERRECEIVEDJOURNALMASTER"),
    VALIDATEFIELD_POPSUPPLIERRECEIVEDJOURNALMASTER(205, "VALIDATEFIELD_POPSUPPLIERRECEIVEDJOURNALMASTER"),
    //Creditors Purchase Post Master
    INSERT_POPPURCHASEPOSTMASTER(220, "INSERT_POPPURCHASEPOSTMASTER"),
    UPDATE_POPPURCHASEPOSTMASTER(221, "UPDATE_POPPURCHASEPOSTMASTER"),
    DELETE_POPPURCHASEPOSTMASTER(222, "DELETE_POPPURCHASEPOSTMASTER"),
    GETNUMROWS_POPPURCHASEPOSTMASTER(223, "GETNUMROWS_POPPURCHASEPOSTMASTER"),
    GETDATA_POPPURCHASEPOSTMASTER(224, "GETDATA_POPPURCHASEPOSTMASTER"),
    VALIDATEFIELD_POPPURCHASEPOSTMASTER(225, "VALIDATEFIELD_POPPURCHASEPOSTMASTER"),
    CREATE_POST(225, "CREATE_POST"),
    GENERATE_POST_REPORT(226, "GENERATE_POST_REPORT"),
    RECEIVE_PURCHASEORDER(227, "RECEIVE_PURCHASEORDER"),
    POST_PURCHASEORDER(228, "POST_PURCHASEORDER"),
    RELEASE_PO(229, "RELEASE_PO"),
    CHECK_SERIAL_BATCH(230, "CHECK_SERIAL_BATCH"),
    POST_BLANKETORDER(231, "POST_BLANKETORDER"),
    PRINT_LABELS(232, "PRINT_LABELS"),
    CHECH_NUMLABELS(233, "CHECH_NUMLABELS"),
    RETURN_TO_SUPPLIER(234, "RETURN_TO_SUPPLIER"),
    PRINT_FG_BOX_LABELS(236, "PRINT_FG_BOX_LABELS"),
    PRINT_CRATE_LABELS(237, "PRINT_CRATE_LABELS"),
    //Creditors Purchase Post Lines
    INSERT_POPPURCHASEPOSTLINES(240, "INSERT_POPPURCHASEPOSTLINES"),
    UPDATE_POPPURCHASEPOSTLINES(241, "UPDATE_POPPURCHASEPOSTLINES"),
    DELETE_POPPURCHASEPOSTLINES(242, "DELETE_POPPURCHASEPOSTLINES"),
    GETNUMROWS_POPPURCHASEPOSTLINES(243, "GETNUMROWS_POPPURCHASEPOSTLINES"),
    GETDATA_POPPURCHASEPOSTLINES(244, "GETDATA_POPPURCHASEPOSTLINES"),
    VALIDATEFIELD_POPPURCHASEPOSTLINES(245, "VALIDATEFIELD_POPPURCHASEPOSTLINES"),
    //Creditors Purchase Post Setup Table
    INSERT_POPPURCHASEPOSTSETUPTABLE(260, "INSERT_POPPURCHASEPOSTSETUPTABLE"),
    UPDATE_POPPURCHASEPOSTSETUPTABLE(261, "UPDATE_POPPURCHASEPOSTSETUPTABLE"),
    DELETE_POPPURCHASEPOSTSETUPTABLE(262, "DELETE_POPPURCHASEPOSTSETUPTABLE"),
    GETNUMROWS_POPPURCHASEPOSTSETUPTABLE(263, "GETNUMROWS_POPPURCHASEPOSTSETUPTABLE"),
    GETDATA_POPPURCHASEPOSTSETUPTABLE(264, "GETDATA_POPPURCHASEPOSTSETUPTABLE"),
    VALIDATEFIELD_POPPURCHASEPOSTSETUPTABLE(265, "VALIDATEFIELD_POPPURCHASEPOSTSETUPTABLE"),
    //Creditors Purchase Post Master DS
    INSERT_POPPURCHASEPOSTMASTERDS(280, "INSERT_POPPURCHASEPOSTMASTERDS"),
    UPDATE_POPPURCHASEPOSTMASTERDS(281, "UPDATE_POPPURCHASEPOSTMASTERDS"),
    DELETE_POPPURCHASEPOSTMASTERDS(282, "DELETE_POPPURCHASEPOSTMASTERDS"),
    GETNUMROWS_POPPURCHASEPOSTMASTERDS(283, "GETNUMROWS_POPPURCHASEPOSTMASTERDS"),
    GETDATA_POPPURCHASEPOSTMASTERDS(284, "GETDATA_POPPURCHASEPOSTMASTERDS"),
    VALIDATEFIELD_POPPURCHASEPOSTMASTERDS(285, "VALIDATEFIELD_POPPURCHASEPOSTMASTERDS"),
    //CreditorsPurchaseOrderApprovalGroups
    INSERT_POPPURCHASEORDERAPPROVALGROUPS(300, "INSERT_POPPURCHASEORDERAPPROVALGROUPS"),
    UPDATE_POPPURCHASEORDERAPPROVALGROUPS(301, "UPDATE_POPPURCHASEORDERAPPROVALGROUPS"),
    DELETE_POPPURCHASEORDERAPPROVALGROUPS(302, "DELETE_POPPURCHASEORDERAPPROVALGROUPS"),
    GETNUMROWS_POPPURCHASEORDERAPPROVALGROUPS(303, "GETNUMROWS_POPPURCHASEORDERAPPROVALGROUPS"),
    GETDATA_POPPURCHASEORDERAPPROVALGROUPS(304, "GETDATA_POPPURCHASEORDERAPPROVALGROUPS"),
    VALIDATEFIELD_POPPURCHASEORDERAPPROVALGROUPS(305, "VALIDATEFIELD_POPPURCHASEORDERAPPROVALGROUPS"),
    //CreditorsPurchaseOrderApprovalGroupEmployees
    INSERT_POPPURCHASEORDERAPPROVALGROUPEMPLOYEES(320, "INSERT_POPPURCHASEORDERAPPROVALGROUPEMPLOYEESDS"),
    UPDATE_POPPURCHASEORDERAPPROVALGROUPEMPLOYEES(321, "UPDATE_POPPURCHASEORDERAPPROVALGROUPEMPLOYEESDS"),
    DELETE_POPPURCHASEORDERAPPROVALGROUPEMPLOYEES(322, "DELETE_POPPURCHASEORDERAPPROVALGROUPEMPLOYEESDS"),
    GETNUMROWS_POPPURCHASEORDERAPPROVALGROUPEMPLOYEES(323, "GETNUMROWS_POPPURCHASEORDERAPPROVALGROUPEMPLOYEESDS"),
    GETDATA_POPPURCHASEORDERAPPROVALGROUPEMPLOYEES(324, "GETDATA_POPPURCHASEORDERAPPROVALGROUPEMPLOYEESDS"),
    VALIDATEFIELD_POPPURCHASEORDERAPPROVALGROUPEMPLOYEES(325, "VALIDATEFIELD_POPPURCHASEORDERAPPROVALGROUPEMPLOYEESDS"),
    //CreditorsDeliveryTerms
    INSERT_POPDELIVERYTERMS(340, "INSERT_POPDELIVERYTERMS"),
    UPDATE_POPDELIVERYTERMS(341, "UPDATE_POPDELIVERYTERMS"),
    DELETE_POPDELIVERYTERMS(342, "DELETE_POPDELIVERYTERMS"),
    GETNUMROWS_POPDELIVERYTERMS(343, "GETNUMROWS_POPDELIVERYTERMS"),
    GETDATA_POPDELIVERYTERMS(344, "GETDATA_POPDELIVERYTERMS"),
    VALIDATEFIELD_POPDELIVERYTERMS(345, "VALIDATEFIELD_POPDELIVERYTERMS"),
    //CreditorsDeliveryModes
    INSERT_POPDELIVERYMODES(360, "INSERT_POPDELIVERYMODES"),
    UPDATE_POPDELIVERYMODES(361, "UPDATE_POPDELIVERYMODES"),
    DELETE_POPDELIVERYMODES(362, "DELETE_POPDELIVERYMODES"),
    GETNUMROWS_POPDELIVERYMODES(363, "GETNUMROWS_POPDELIVERYMODES"),
    GETDATA_POPDELIVERYMODES(364, "GETDATA_POPDELIVERYMODES"),
    VALIDATEFIELD_POPDELIVERYMODES(365, "VALIDATEFIELD_POPDELIVERYMODES"),
    //CreditorsPurchaseOrderLinesDS
    INSERT_POPPURCHASEORDERLINESDS(380, "INSERT_POPPURCHASEORDERLINESDS"),
    UPDATE_POPPURCHASEORDERLINESDS(381, "UPDATE_POPPURCHASEORDERLINESDS"),
    DELETE_POPPURCHASEORDERLINESDS(382, "DELETE_POPPURCHASEORDERLINESDS"),
    GETNUMROWS_POPPURCHASEORDERLINESDS(383, "GETNUMROWS_POPPURCHASEORDERLINESDS"),
    GETDATA_POPPURCHASEORDERLINESDS(384, "GETDATA_POPPURCHASEORDERLINESDS"),
    VALIDATEFIELD_POPPURCHASEORDERLINESDS(385, "VALIDATEFIELD_POPPURCHASEORDERLINESDS"),
    //CreditorsPurchasePostLinesDS
    INSERT_POPPURCHASEPOSTLINESDS(400, "INSERT_POPPURCHASEPOSTLINESDS"),
    UPDATE_POPPURCHASEPOSTLINESDS(401, "UPDATE_POPPURCHASEPOSTLINESDS"),
    DELETE_POPPURCHASEPOSTLINESDS(402, "DELETE_POPPURCHASEPOSTLINESDS"),
    GETNUMROWS_POPPURCHASEPOSTLINESDS(403, "GETNUMROWS_POPPURCHASEPOSTLINESDS"),
    GETDATA_POPPURCHASEPOSTLINESDS(404, "GETDATA_POPPURCHASEPOSTLINESDS"),
    VALIDATEFIELD_POPPURCHASEPOSTLINESDS(405, "VALIDATEFIELD_POPPURCHASEPOSTLINESDS"),
    //CreditorsSupplierReceivedJournalLinesDS
    INSERT_POPSUPPLIERRECEIVEDJOURNALLINESDS(420, "INSERT_POPSUPPLIERRECEIVEDJOURNALLINESDS"),
    UPDATE_POPSUPPLIERRECEIVEDJOURNALLINESDS(421, "UPDATE_POPSUPPLIERRECEIVEDJOURNALLINESDS"),
    DELETE_POPSUPPLIERRECEIVEDJOURNALLINESDS(422, "DELETE_POPSUPPLIERRECEIVEDJOURNALLINESDS"),
    GETNUMROWS_POPSUPPLIERRECEIVEDJOURNALLINESDS(423, "GETNUMROWS_POPSUPPLIERRECEIVEDJOURNALLINESDS"),
    GETDATA_POPSUPPLIERRECEIVEDJOURNALLINESDS(424, "GETDATA_POPSUPPLIERRECEIVEDJOURNALLINESDS"),
    VALIDATEFIELD_POPSUPPLIERRECEIVEDJOURNALLINESDS(425, "VALIDATEFIELD_POPSUPPLIERRECEIVEDJOURNALLINESDS"),
    //Enum variables
    //CreditorsQualityTestType
    INSERT_POPQUALITYTESTTYPE(440, "INSERT_POPQUALITYTESTTYPE"),
    UPDATE_POPQUALITYTESTTYPE(441, "UPDATE_POPQUALITYTESTTYPE"),
    DELETE_POPQUALITYTESTTYPE(442, "DELETE_POPQUALITYTESTTYPE"),
    GETNUMROWS_POPQUALITYTESTTYPE(443, "GETNUMROWS_POPQUALITYTESTTYPE"),
    GETDATA_POPQUALITYTESTTYPE(444, "GETDATA_POPQUALITYTESTTYPE"),
    VALIDATEFIELD_POPQUALITYTESTTYPE(445, "VALIDATEFIELD_POPQUALITYTESTTYPE"),
    //CreditorsParameters
    INSERT_POPPARAMETERS(460, "INSERT_POPPARAMETERS"),
    UPDATE_POPPARAMETERS(461, "UPDATE_POPPARAMETERS"),
    DELETE_POPPARAMETERS(462, "DELETE_POPPARAMETERS"),
    GETNUMROWS_POPPARAMETERS(463, "GETNUMROWS_POPPARAMETERS"),
    GETDATA_POPPARAMETERS(464, "GETDATA_POPPARAMETERS"),
    VALIDATEFIELD_POPPARAMETERS(465, "VALIDATEFIELD_POPPARAMETERS"),
    GET_PLANNED_RELEASE_ITEM_FIELD(466, "GET_PLANNED_RELEASE_ITEM_FIELD"),
    //POP Outstanding PO Report 
    PRINT_OUTSTANDINGPOREPORT(480, "PRINT_OUTSTANDINGPOREPORT"),
    //POP Goods Received Report
    PRINT_GOODSRECEIVEDREPORT(481, "PRINT_GOODSRECEIVEDREPORT"),
    PRINT_PRICEVARIANCE(482, "PRINT_PRICEVARIANCE"),
    PRINT_GOODSRETURNEDREPORT(483, "PRINT_GOODSRETURNEDREPORT"),
    //Goods received report
    GENERATE_GOODS_RECEIVED_REPORT(484, "GENERATE_GOODS_RECEIVED_REPORT"),
    //Services Received
    PRINT_SERVICES_RECEIVED_REPORT(485, "PRINT_SERVICES_RECEIVED_REPORT"),
    PRINT_GOODS_RECEIVE_REPORT(486, "PRINT_GOODS_RECEIVE_REPORT"),
    //Cancelling Purchase Orders
    CANCEL_PURCHASEORDER(500, "CANCEL_PURCHASEORDER"),
    CANCEL_PURCHASEORDERLINE(501, "CANCEL_PURCHASEORDERLINE"),
    PRINT_CANCELLED_PO(502, "PRINT_CANCELLED_PO"),
    //CostChangeReason
    INSERT_POPCOSTCHANGEREASON(520, "INSERT_POPCOSTCHANGEREASON"),
    UPDATE_POPCOSTCHANGEREASON(521, "UPDATE_POPCOSTCHANGEREASON"),
    DELETE_POPCOSTCHANGEREASON(522, "DELETE_POPCOSTCHANGEREASON"),
    GETNUMROWS_POPCOSTCHANGEREASON(523, "GETNUMROWS_POPCOSTCHANGEREASON"),
    GETDATA_POPCOSTCHANGEREASON(524, "GETDATA_POPCOSTCHANGEREASON"),
    VALIDATEFIELD_POPCOSTCHANGEREASON(525, "VALIDATEFIELD_POPCOSTCHANGEREASON"),
    //CostChangeSummaryDS
    INSERT_COSTCHANGESUMMARYDS(540, "INSERT_COSTCHANGESUMMARYDS"),
    UPDATE_COSTCHANGESUMMARYDS(541, "UPDATE_COSTCHANGESUMMARYDS"),
    DELETE_COSTCHANGESUMMARYDS(542, "DELETE_COSTCHANGESUMMARYDS"),
    GETNUMROWS_COSTCHANGESUMMARYDS(543, "GETNUMROWS_COSTCHANGESUMMARYDS"),
    GETDATA_COSTCHANGESUMMARYDS(544, "GETDATA_COSTCHANGESUMMARYDS"),
    VALIDATEFIELD_COSTCHANGESUMMARYDS(545, "VALIDATEFIELD_COSTCHANGESUMMARYDS"),
    //POPCancelledPurchaseOrderLinesDS
    INSERT_POPCANCELLEDPURCHASEORDERLINESDS(560, "INSERT_POPCANCELLEDPURCHASEORDERLINESDS"),
    UPDATE_POPCANCELLEDPURCHASEORDERLINESDS(561, "UPDATE_POPCANCELLEDPURCHASEORDERLINESDS"),
    DELETE_POPCANCELLEDPURCHASEORDERLINESDS(562, "DELETE_POPCANCELLEDPURCHASEORDERLINESDS"),
    GETNUMROWS_POPCANCELLEDPURCHASEORDERLINESDS(563, "GETNUMROWS_POPCANCELLEDPURCHASEORDERLINESDS"),
    GETDATA_POPCANCELLEDPURCHASEORDERLINESDS(564, "GETDATA_POPCANCELLEDPURCHASEORDERLINESDS"),
    VALIDATEFIELD_POPCANCELLEDPURCHASEORDERLINESDS(565, "VALIDATEFIELD_POPCANCELLEDPURCHASEORDERLINESDS"),
    //POPCancelledPurchaseOrderMaster
    INSERT_POPCANCELLEDPURCHASEORDERMASTER(580, "INSERT_POPCANCELLEDPURCHASEORDERMASTER"),
    UPDATE_POPCANCELLEDPURCHASEORDERMASTER(581, "UPDATE_POPCANCELLEDPURCHASEORDERMASTER"),
    DELETE_POPCANCELLEDPURCHASEORDERMASTER(582, "DELETE_POPCANCELLEDPURCHASEORDERMASTER"),
    GETNUMROWS_POPCANCELLEDPURCHASEORDERMASTER(583, "GETNUMROWS_POPCANCELLEDPURCHASEORDERMASTER"),
    GETDATA_POPCANCELLEDPURCHASEORDERMASTER(584, "GETDATA_POPCANCELLEDPURCHASEORDERMASTER"),
    VALIDATEFIELD_POPCANCELLEDPURCHASEORDERMASTER(585, "VALIDATEFIELD_POPCANCELLEDPURCHASEORDERMASTER"),
    //POPGRNReprintTemp
    INSERT_POPGRNREPRINTTEMP(600, "INSERT_POPGRNREPRINTTEMP"),
    UPDATE_POPGRNREPRINTTEMP(601, "UPDATE_POPGRNREPRINTTEMP"),
    DELETE_POPGRNREPRINTTEMP(602, "DELETE_POPGRNREPRINTTEMP"),
    GETNUMROWS_POPGRNREPRINTTEMP(603, "GETNUMROWS_POPGRNREPRINTTEMP"),
    GETDATA_POPGRNREPRINTTEMP(604, "GETDATA_POPGRNREPRINTTEMP"),
    VALIDATEFIELD_POPGRNREPRINTTEMP(605, "VALIDATEFIELD_POPGRNREPRINTTEMP"),
    //POPGRNReprintTempDS
    INSERT_POPGRNREPRINTTEMPDS(620, "INSERT_POPGRNREPRINTTEMPDS"),
    UPDATE_POPGRNREPRINTTEMPDS(621, "UPDATE_POPGRNREPRINTTEMPDS"),
    DELETE_POPGRNREPRINTTEMPDS(622, "DELETE_POPGRNREPRINTTEMPDS"),
    GETNUMROWS_POPGRNREPRINTTEMPDS(623, "GETNUMROWS_POPGRNREPRINTTEMPDS"),
    GETDATA_POPGRNREPRINTTEMPDS(624, "GETDATA_POPGRNREPRINTTEMPDS"),
    VALIDATEFIELD_POPGRNREPRINTTEMPDS(625, "VALIDATEFIELD_POPGRNREPRINTTEMPDS"),
    REPRINT_LABLES(626, "REPRINT_LABLES"),
    //POPGoodsReturnReason
    INSERT_POPGOODSRETURNREASON(640, "INSERT_POPGOODSRETURNREASON"),
    UPDATE_POPGOODSRETURNREASON(641, "UPDATE_POPGOODSRETURNREASON"),
    DELETE_POPGOODSRETURNREASON(642, "DELETE_POPGOODSRETURNREASON"),
    GETNUMROWS_POPGOODSRETURNREASON(643, "GETNUMROWS_POPGOODSRETURNREASON"),
    GETDATA_POPGOODSRETURNREASON(644, "GETDATA_POPGOODSRETURNREASON"),
    VALIDATEFIELD_POPGOODSRETURNREASON(645, "VALIDATEFIELD_POPGOODSRETURNREASON"),
    //Mill Purchases
    PRINT_MILL_PURCHASE_REPORT(660, "PRINT_MILL_PURCHASE_REPORT"),
    //POPPlannedPurchaseOrders
    INSERT_POPPLANNEDPURCHASEORDERS(680, "INSERT_POPPLANNEDPURCHASEORDERS"),
    UPDATE_POPPLANNEDPURCHASEORDERS(681, "UPDATE_POPPLANNEDPURCHASEORDERS"),
    DELETE_POPPLANNEDPURCHASEORDERS(682, "DELETE_POPPLANNEDPURCHASEORDERS"),
    GETNUMROWS_POPPLANNEDPURCHASEORDERS(683, "GETNUMROWS_POPPLANNEDPURCHASEORDERS"),
    GETDATA_POPPLANNEDPURCHASEORDERS(684, "GETDATA_POPPLANNEDPURCHASEORDERS"),
    VALIDATEFIELD_POPPLANNEDPURCHASEORDERS(685, "VALIDATEFIELD_POPPLANNEDPURCHASEORDERS"),
    FIRM_PLANNED_PURCHASE_ORDER(686, "FIRM_PLANNED_PURCHASE_ORDER"),
    RELEASE_PLANNED_PURCHASE_ORDER(687, "RELEASE_PLANNED_PURCHASE_ORDER"),
    FIND_DEFAULT_ITEM_VALUES(688, "FIND_DEFAULT_ITEM_VALUES"),
    //POPPlannedPurchaseOrdersDS
    INSERT_POPPLANNEDPURCHASEORDERSDS(700, "INSERT_POPPLANNEDPURCHASEORDERSDS"),
    UPDATE_POPPLANNEDPURCHASEORDERSDS(701, "UPDATE_POPPLANNEDPURCHASEORDERSDS"),
    DELETE_POPPLANNEDPURCHASEORDERSDS(702, "DELETE_POPPLANNEDPURCHASEORDERSDS"),
    GETNUMROWS_POPPLANNEDPURCHASEORDERSDS(703, "GETNUMROWS_POPPLANNEDPURCHASEORDERSDS"),
    GETDATA_POPPLANNEDPURCHASEORDERSDS(704, "GETDATA_POPPLANNEDPURCHASEORDERSDS"),
    VALIDATEFIELD_POPPLANNEDPURCHASEORDERSDS(705, "VALIDATEFIELD_POPPLANNEDPURCHASEORDERSDS"),
    //POP Price Arrangements
    INSERT_POPPRICEARRANGEMENTS(720, "INSERT_POPPRICEARRANGEMENTS"),
    UPDATE_POPPRICEARRANGEMENTS(721, "UPDATE_POPPRICEARRANGEMENTS"),
    DELETE_POPPRICEARRANGEMENTS(722, "DELETE_POPPRICEARRANGEMENTS"),
    GETNUMROWS_POPPRICEARRANGEMENTS(723, "GETNUMROWS_POPPRICEARRANGEMENTS"),
    GETDATA_POPPRICEARRANGEMENTS(724, "GETDATA_POPPRICEARRANGEMENTS"),
    VALIDATEFIELD_POPPRICEARRANGEMENTS(725, "VALIDATEFIELD_POPPRICEARRANGEMENTS"),
    //POP Price Arrangements DS
    INSERT_POPPRICEARRANGEMENTDS(740, "INSERT_POPPRICEARRANGEMENTDS"),
    UPDATE_POPPRICEARRANGEMENTDS(741, "UPDATE_POPPRICEARRANGEMENTDS"),
    DELETE_POPPRICEARRANGEMENTDS(742, "DELETE_POPPRICEARRANGEMENTDS"),
    GETNUMROWS_POPPRICEARRANGEMENTDS(743, "GETNUMROWS_POPPRICEARRANGEMENTDS"),
    GETDATA_POPPRICEARRANGEMENTDS(744, "GETDATA_POPPRICEARRANGEMENTDS"),
    VALIDATEFIELD_POPPRICEARRANGEMENTDS(745, "VALIDATEFIELD_POPPRICEARRANGEMENTDS");
    final int id;
    final String label;

    /** Creates a new instance of ServerPOPMethods */
    ServerPOPMethods(final int id, final String label) {
        this.id = id;
        this.label = label;
    }

    public int getId() {
        return id;
    }

    @Override
    public String toString() {
        return label;
    }

    public static ServerPOPMethods fromString(final String str) {
        for (ServerPOPMethods e : ServerPOPMethods.values()) {
            if (e.toString().equalsIgnoreCase(str)) {
                return e;
            }
        }
        return null;
    }

    public static ServerPOPMethods fromId(final int id) {
        for (ServerPOPMethods e : ServerPOPMethods.values()) {
            if (e.id == id) {
                return e;
            }
        }
        return null;
    }

    public enumEMCModules getEMCModule() {
        return enumEMCModules.POP;
    }
}   
