/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package emc.methods.inventory;

import emc.enums.modules.enumEMCModules;
import emc.methods.EMCMethodEnum;

/**
 *
 * @author riaan
 */
public enum ServerInventoryMethods implements EMCMethodEnum {

    //Item Master
    INSERT_INVENTORYITEMMASTER(0, "INSERT_INVENTORYITEMMASTER"),
    UPDATE_INVENTORYITEMMASTER(1, "UPDATE_INVENTORYITEMMASTER"),
    DELETE_INVENTORYITEMMASTER(2, "DELETE_INVENTORYITEMMASTER"),
    GETNUMROWS_INVENTORYITEMMASTER(3, "GETNUMROWS_INVENTORYITEMMASTER"),
    GETDATA_INVENTORYITEMMASTER(4, "GETDATA_INVENTORYITEMMASTER"),
    VALIDATEFIELD_INVENTORYITEMMASTER(5, "VALIDATEFIELD_INVENTORYITEMMASTER"),
    GENERATE_ITEM_DIM_COMBINATIONS(6, "GENERATE_ITEM_DIM_COMBINATIONS"),
    POPULATE_NEW_ITEM(7, "POPULATE_NEW_ITEM"),
    FIND_ITEM(8, "FIND_ITEM"),
    //InventoryDimension2Group
    INSERT_INVENTORYDIMENSION2GROUP(20, "INSERT_INVENTORYDIMENSION2GROUP"),
    UPDATE_INVENTORYDIMENSION2GROUP(21, "UPDATE_INVENTORYDIMENSION2GROUP"),
    DELETE_INVENTORYDIMENSION2GROUP(22, "DELETE_INVENTORYDIMENSION2GROUP"),
    GETNUMROWS_INVENTORYDIMENSION2GROUP(23, "GETNUMROWS_INVENTORYDIMENSION2GROUP"),
    GETDATA_INVENTORYDIMENSION2GROUP(24, "GETDATA_INVENTORYDIMENSION2GROUP"),
    VALIDATEFIELD_INVENTORYDIMENSION2GROUP(25, "VALIDATEFIELD_INVENTORYDIMENSION2GROUP"),
    //Costing Groups
    INSERT_INVENTORYCOSTINGGROUP(40, "INSERT_INVENTORYCOSTINGGROUP"),
    UPDATE_INVENTORYCOSTINGGROUP(41, "UPDATE_INVENTORYCOSTINGGROUP"),
    DELETE_INVENTORYCOSTINGGROUP(42, "DELETE_INVENTORYCOSTINGGROUP"),
    GETNUMROWS_INVENTORYCOSTINGGROUP(43, "GETNUMROWS_INVENTORYCOSTINGGROUP"),
    GETDATA_INVENTORYCOSTINGGROUP(44, "GETDATA_INVENTORYCOSTINGGROUP"),
    VALIDATEFIELD_INVENTORYCOSTINGGROUP(45, "VALIDATEFIELD_INVENTORYCOSTINGGROUP"),
    FIX_COST_ROUTINE(46, "FIX_COST_ROUTINE"),
    FIX_TRANS_ROUTINE(47, "FIX_TRANS_ROUTINE"),
    //Brand Groups
    INSERT_INVENTORYBRANDGROUP(60, "INSERT_INVENTORYBRANDGROUP"),
    UPDATE_INVENTORYBRANDGROUP(61, "UPDATE_INVENTORYBRANDGROUP"),
    DELETE_INVENTORYBRANDGROUP(62, "DELETE_INVENTORYBRANDGROUP"),
    GETNUMROWS_INVENTORYBRANDGROUP(63, "GETNUMROWS_INVENTORYBRANDGROUP"),
    GETDATA_INVENTORYBRANDGROUP(64, "GETDATA_INVENTORYBRANDGROUP"),
    VALIDATEFIELD_INVENTORYBRANDGROUP(65, "VALIDATEFIELD_INVENTORYBRANDGROUP"),
    //Item Ranges
    INSERT_INVENTORYITEMRANGE(80, "INSERT_INVENTORYITEMRANGE"),
    UPDATE_INVENTORYITEMRANGE(81, "UPDATE_INVENTORYITEMRANGE"),
    DELETE_INVENTORYITEMRANGE(82, "DELETE_INVENTORYITEMRANGE"),
    GETNUMROWS_INVENTORYITEMRANGE(83, "GETNUMROWS_INVENTORYITEMRANGE"),
    GETDATA_INVENTORYITEMRANGE(84, "GETDATA_INVENTORYITEMRANGE"),
    VALIDATEFIELD_INVENTORYITEMRANGE(85, "VALIDATEFIELD_INVENTORYITEMRANGE"),
    //Inventory Warehouse
    INSERT_INVENTORYWAREHOUSE(100, "INSERT_INVENTORYWAREHOUSE"),
    UPDATE_INVENTORYWAREHOUSE(101, "UPDATE_INVENTORYWAREHOUSE"),
    DELETE_INVENTORYWAREHOUSE(102, "DELETE_INVENTORYWAREHOUSE"),
    GETNUMROWS_INVENTORYWAREHOUSE(103, "GETNUMROWS_INVENTORYWAREHOUSE"),
    GETDATA_INVENTORYWAREHOUSE(104, "GETDATA_INVENTORYWAREHOUSE"),
    VALIDATEFIELD_INVENTORYWAREHOUSE(105, "VALIDATEFIELD_INVENTORYWAREHOUSE"),
    POPULATE_SYSTEM_LOCATIONS(106, "POPULATE_SYSTEM_LOCATIONS"),
    //Inventory Barcodes
    INSERT_INVENTORYBARCODES(120, "INSERT_INVENTORYBARCODES"),
    UPDATE_INVENTORYBARCODES(121, "UPDATE_INVENTORYBARCODES"),
    DELETE_INVENTORYBARCODES(122, "DELETE_INVENTORYBARCODES"),
    GETNUMROWS_INVENTORYBARCODES(123, "GETNUMROWS_INVENTORYBARCODES"),
    GETDATA_INVENTORYBARCODES(124, "GETDATA_INVENTORYBARCODES"),
    VALIDATEFIELD_INVENTORYBARCODES(125, "VALIDATEFIELD_INVENTORYBARCODES"),
    //Inventory Dimension 1
    INSERT_INVENTORYDIMENSION1(140, "INSERT_INVENTORYDIMENSION1"),
    UPDATE_INVENTORYDIMENSION1(141, "UPDATE_INVENTORYDIMENSION1"),
    DELETE_INVENTORYDIMENSION1(142, "DELETE_INVENTORYDIMENSION1"),
    GETNUMROWS_INVENTORYDIMENSION1(143, "GETNUMROWS_INVENTORYDIMENSION1"),
    GETDATA_INVENTORYDIMENSION1(144, "GETDATA_INVENTORYDIMENSION1"),
    VALIDATEFIELD_INVENTORYDIMENSION1(145, "VALIDATEFIELD_INVENTORYDIMENSION1"),
    SET_SORT_CODE_DIMENSION1(146, "SET_SORT_CODE_DIMENSION1"),
    //Inventory Dimension 2
    INSERT_INVENTORYDIMENSION2(160, "INSERT_INVENTORYDIMENSION2"),
    UPDATE_INVENTORYDIMENSION2(161, "UPDATE_INVENTORYDIMENSION2"),
    DELETE_INVENTORYDIMENSION2(162, "DELETE_INVENTORYDIMENSION2"),
    GETNUMROWS_INVENTORYDIMENSION2(163, "GETNUMROWS_INVENTORYDIMENSION2"),
    GETDATA_INVENTORYDIMENSION2(164, "GETDATA_INVENTORYDIMENSION2"),
    VALIDATEFIELD_INVENTORYDIMENSION2(165, "VALIDATEFIELD_INVENTORYDIMENSION2"),
    //Inventory Dimension 3
    INSERT_INVENTORYDIMENSION3(180, "INSERT_INVENTORYDIMENSION3"),
    UPDATE_INVENTORYDIMENSION3(181, "UPDATE_INVENTORYDIMENSION3"),
    DELETE_INVENTORYDIMENSION3(182, "DELETE_INVENTORYDIMENSION3"),
    GETNUMROWS_INVENTORYDIMENSION3(183, "GETNUMROWS_INVENTORYDIMENSION3"),
    GETDATA_INVENTORYDIMENSION3(184, "GETDATA_INVENTORYDIMENSION3"),
    VALIDATEFIELD_INVENTORYDIMENSION3(185, "VALIDATEFIELD_INVENTORYDIMENSION3"),
    SET_SORT_CODE_DIMENSION3(186, "SET_SORT_CODE_DIMENSION3"),
    //Inventory Item Dimension Combinations
    INSERT_INVENTORYITEMDIMENSIONCOMBINATIONS(200, "INSERT_INVENTORYITEMDIMENSIONCOMBINATIONS"),
    UPDATE_INVENTORYITEMDIMENSIONCOMBINATIONS(201, "UPDATE_INVENTORYITEMDIMENSIONCOMBINATIONS"),
    DELETE_INVENTORYITEMDIMENSIONCOMBINATIONS(202, "DELETE_INVENTORYITEMDIMENSIONCOMBINATIONS"),
    GETNUMROWS_INVENTORYITEMDIMENSIONCOMBINATIONS(203, "GETNUMROWS_INVENTORYITEMDIMENSIONCOMBINATIONS"),
    GETDATA_INVENTORYITEMDIMENSIONCOMBINATIONS(204, "GETDATA_INVENTORYITEMDIMENSIONCOMBINATIONS"),
    VALIDATEFIELD_INVENTORYITEMDIMENSIONCOMBINATIONS(205, "VALIDATEFIELD_INVENTORYITEMDIMENSIONCOMBINATIONS"),
    CHECK_COMBINATIONS_EXIST(206, "CHECK_COMBINATIONS_EXIST"),
    PRINT_ITEM_DIMENSION_REPORT(207, "PRINT_ITEM_DIMENSION_REPORT"),
    CHECK_DIMENSION_IN_USE(208, "CHECK_DIMENSION_IN_USE"),
    //Inventory Item Dimension Group
    INSERT_INVENTORYITEMDIMENSIONGROUP(220, "INSERT_INVENTORYITEMDIMENSIONGROUP"),
    UPDATE_INVENTORYITEMDIMENSIONGROUP(221, "UPDATE_INVENTORYITEMDIMENSIONGROUP"),
    DELETE_INVENTORYITEMDIMENSIONGROUP(222, "DELETE_INVENTORYITEMDIMENSIONGROUP"),
    GETNUMROWS_INVENTORYITEMDIMENSIONGROUP(223, "GETNUMROWS_INVENTORYITEMDIMENSIONGROUP"),
    GETDATA_INVENTORYITEMDIMENSIONGROUP(224, "GETDATA_INVENTORYITEMDIMENSIONGROUP"),
    VALIDATEFIELD_INVENTORYITEMDIMENSIONGROUP(225, "VALIDATEFIELD_INVENTORYITEMDIMENSIONGROUP"),
    //Inventory Item Batch
    INSERT_INVENTORYITEMBATCH(240, "INSERT_INVENTORYITEMBATCH"),
    UPDATE_INVENTORYITEMBATCH(241, "UPDATE_INVENTORYITEMBATCH"),
    DELETE_INVENTORYITEMBATCH(242, "DELETE_INVENTORYITEMBATCH"),
    GETNUMROWS_INVENTORYITEMBATCH(243, "GETNUMROWS_INVENTORYITEMBATCH"),
    GETDATA_INVENTORYITEMBATCH(244, "GETDATA_INVENTORYITEMBATCH"),
    VALIDATEFIELD_INVENTORYITEMBATCH(245, "VALIDATEFIELD_INVENTORYITEMBATCH"),
    //InventoryItemSerial
    INSERT_INVENTORYITEMSERIAL(260, "INSERT_INVENTORYITEMSERIAL"),
    UPDATE_INVENTORYITEMSERIAL(261, "UPDATE_INVENTORYITEMSERIAL"),
    DELETE_INVENTORYITEMSERIAL(262, "DELETE_INVENTORYITEMSERIAL"),
    GETNUMROWS_INVENTORYITEMSERIAL(263, "GETNUMROWS_INVENTORYITEMSERIAL"),
    GETDATA_INVENTORYITEMSERIAL(264, "GETDATA_INVENTORYITEMSERIAL"),
    VALIDATEFIELD_INVENTORYITEMSERIAL(265, "VALIDATEFIELD_INVENTORYITEMSERIAL"),
    //Inventory Journal Master
    INSERT_INVENTORYJOURNALMASTER(340, "INSERT_INVENTORYJOURNALMASTER"),
    UPDATE_INVENTORYJOURNALMASTER(341, "UPDATE_INVENTORYJOURNALMASTER"),
    DELETE_INVENTORYJOURNALMASTER(342, "DELETE_INVENTORYJOURNALMASTER"),
    GETNUMROWS_INVENTORYJOURNALMASTER(343, "GETNUMROWS_INVENTORYJOURNALMASTER"),
    GETDATA_INVENTORYJOURNALMASTER(344, "GETDATA_INVENTORYJOURNALMASTER"),
    VALIDATEFIELD_INVENTORYJOURNALMASTER(345, "VALIDATEFIELD_INVENTORYJOURNALMASTER"),
    APPROVE_JOURNAL(346, "APPROVE_JOURNAL"),
    VALIDATE_INVENTORYJOURNAL(347, "VALIDATE_INVENTORYJOURNAL"),
    POST_INVENTORYJOURNAL(348, "POST_INVENTORYJOURNAL"),
    PRINT_STOCK_JOURNALS(349, "PRINT_STOCK_JOURNALS"),
    UNAPPROVE_JOURNAL(350, "UNAPPROVE_JOURNAL"),
    GENERATE_STOCKTAKE(351, "GENERATE_STOCKTAKE"),
    GENERATE_TRANSFER_JOURNAL(352, "GENERATE_TRANSFER_JOURNAL"),
    POST_INVENTORYJOURNAL_FROM_NUMBER(353, "POST_INVENTORYJOURNAL_FROM_NUMBER"),
    //InventoryJournalLines
    INSERT_INVENTORYJOURNALLINES(360, "INSERT_INVENTORYJOURNALLINES"),
    UPDATE_INVENTORYJOURNALLINES(361, "UPDATE_INVENTORYJOURNALLINES"),
    DELETE_INVENTORYJOURNALLINES(362, "DELETE_INVENTORYJOURNALLINES"),
    GETNUMROWS_INVENTORYJOURNALLINES(363, "GETNUMROWS_INVENTORYJOURNALLINES"),
    GETDATA_INVENTORYJOURNALLINES(364, "GETDATA_INVENTORYJOURNALLINES"),
    VALIDATEFIELD_INVENTORYJOURNALLINES(365, "VALIDATEFIELD_INVENTORYJOURNALLINES"),
    MASS_UPDATE_LINE_DATE(366, "MASS_UPDATE_LINE_DATE"),
    GENERATE_REGISTRATION(367, "GENERATE_REGISTRATION"),
    //Inventory Dimension 3 Group
    INSERT_INVENTORYDIMENSION3GROUP(380, "INSERT_INVENTORYDIMENSION3GROUP"),
    UPDATE_INVENTORYDIMENSION3GROUP(381, "UPDATE_INVENTORYDIMENSION3GROUP"),
    DELETE_INVENTORYDIMENSION3GROUP(382, "DELETE_INVENTORYDIMENSION3GROUP"),
    GETNUMROWS_INVENTORYDIMENSION3GROUP(383, "GETNUMROWS_INVENTORYDIMENSION3GROUP"),
    GETDATA_INVENTORYDIMENSION3GROUP(384, "GETDATA_INVENTORYDIMENSION3GROUP"),
    VALIDATEFIELD_INVENTORYDIMENSION3GROUP(385, "VALIDATEFIELD_INVENTORYDIMENSION3GROUP"),
    //Inventory Dimension 1 Group
    INSERT_INVENTORYDIMENSION1GROUP(400, "INSERT_INVENTORYDIMENSION1GROUP"),
    UPDATE_INVENTORYDIMENSION1GROUP(401, "UPDATE_INVENTORYDIMENSION1GROUP"),
    DELETE_INVENTORYDIMENSION1GROUP(402, "DELETE_INVENTORYDIMENSION1GROUP"),
    GETNUMROWS_INVENTORYDIMENSION1GROUP(403, "GETNUMROWS_INVENTORYDIMENSION1GROUP"),
    GETDATA_INVENTORYDIMENSION1GROUP(404, "GETDATA_INVENTORYDIMENSION1GROUP"),
    VALIDATEFIELD_INVENTORYDIMENSION1GROUP(405, "VALIDATEFIELD_INVENTORYDIMENSION1GROUP"),
    //Inventory Dimension 2 Group Setup
    INSERT_INVENTORYDIMENSION2GROUPSETUP(420, "INSERT_INVENTORYDIMENSION2GROUPSETUP"),
    UPDATE_INVENTORYDIMENSION2GROUPSETUP(421, "UPDATE_INVENTORYDIMENSION2GROUPSETUP"),
    DELETE_INVENTORYDIMENSION2GROUPSETUP(422, "DELETE_INVENTORYDIMENSION2GROUPSETUP"),
    GETNUMROWS_INVENTORYDIMENSION2GROUPSETUP(423, "GETNUMROWS_INVENTORYDIMENSION2GROUPSETUP"),
    GETDATA_INVENTORYDIMENSION2GROUPSETUP(424, "GETDATA_INVENTORYDIMENSION2GROUPSETUP"),
    VALIDATEFIELD_INVENTORYDIMENSION2GROUPSETUP(425, "VALIDATEFIELD_INVENTORYDIMENSION2GROUPSETUP"),
    //Inventory Dimension 1 Group Setup
    INSERT_INVENTORYDIMENSION1GROUPSETUP(420, "INSERT_INVENTORYDIMENSION1GROUPSETUP"),
    UPDATE_INVENTORYDIMENSION1GROUPSETUP(421, "UPDATE_INVENTORYDIMENSION1GROUPSETUP"),
    DELETE_INVENTORYDIMENSION1GROUPSETUP(422, "DELETE_INVENTORYDIMENSION1GROUPSETUP"),
    GETNUMROWS_INVENTORYDIMENSION1GROUPSETUP(423, "GETNUMROWS_INVENTORYDIMENSION1GROUPSETUP"),
    GETDATA_INVENTORYDIMENSION1GROUPSETUP(424, "GETDATA_INVENTORYDIMENSION1GROUPSETUP"),
    VALIDATEFIELD_INVENTORYDIMENSION1GROUPSETUP(425, "VALIDATEFIELD_INVENTORYDIMENSION1GROUPSETUP"),
    //Inventory Dimension 3 Group Setup
    INSERT_INVENTORYDIMENSION3GROUPSETUP(440, "INSERT_INVENTORYDIMENSION3GROUPSETUP"),
    UPDATE_INVENTORYDIMENSION3GROUPSETUP(441, "UPDATE_INVENTORYDIMENSION3GROUPSETUP"),
    DELETE_INVENTORYDIMENSION3GROUPSETUP(442, "DELETE_INVENTORYDIMENSION3GROUPSETUP"),
    GETNUMROWS_INVENTORYDIMENSION3GROUPSETUP(443, "GETNUMROWS_INVENTORYDIMENSION3GROUPSETUP"),
    GETDATA_INVENTORYDIMENSION3GROUPSETUP(444, "GETDATA_INVENTORYDIMENSION3GROUPSETUP"),
    VALIDATEFIELD_INVENTORYDIMENSION3GROUPSETUP(445, "VALIDATEFIELD_INVENTORYDIMENSION3GROUPSETUP"),
    //Inventory Item Dimension 1 Setup
    INSERT_INVENTORYITEMDIMENSION1SETUP(460, "INSERT_INVENTORYITEMDIMENSION1SETUP"),
    UPDATE_INVENTORYITEMDIMENSION1SETUP(461, "UPDATE_INVENTORYITEMDIMENSION1SETUP"),
    DELETE_INVENTORYITEMDIMENSION1SETUP(462, "DELETE_INVENTORYITEMDIMENSION1SETUP"),
    GETNUMROWS_INVENTORYITEMDIMENSION1SETUP(463, "GETNUMROWS_INVENTORYITEMDIMENSION1SETUP"),
    GETDATA_INVENTORYITEMDIMENSION1SETUP(464, "GETDATA_INVENTORYITEMDIMENSION1SETUP"),
    VALIDATEFIELD_INVENTORYITEMDIMENSION1SETUP(465, "VALIDATEFIELD_INVENTORYITEMDIMENSION1SETUP"),
    //Inventory Item Dimension 2 Setup
    INSERT_INVENTORYITEMDIMENSION2SETUP(480, "INSERT_INVENTORYITEMDIMENSION2SETUP"),
    UPDATE_INVENTORYITEMDIMENSION2SETUP(481, "UPDATE_INVENTORYITEMDIMENSION2SETUP"),
    DELETE_INVENTORYITEMDIMENSION2SETUP(482, "DELETE_INVENTORYITEMDIMENSION2SETUP"),
    GETNUMROWS_INVENTORYITEMDIMENSION2SETUP(483, "GETNUMROWS_INVENTORYITEMDIMENSION2SETUP"),
    GETDATA_INVENTORYITEMDIMENSION2SETUP(484, "GETDATA_INVENTORYITEMDIMENSION2SETUP"),
    VALIDATEFIELD_INVENTORYITEMDIMENSION2SETUP(485, "VALIDATEFIELD_INVENTORYITEMDIMENSION2SETUP"),
    //Inventory Item Dimension 3 Setup
    INSERT_INVENTORYITEMDIMENSION3SETUP(500, "INSERT_INVENTORYITEMDIMENSION3SETUP"),
    UPDATE_INVENTORYITEMDIMENSION3SETUP(501, "UPDATE_INVENTORYITEMDIMENSION3SETUP"),
    DELETE_INVENTORYITEMDIMENSION3SETUP(502, "DELETE_INVENTORYITEMDIMENSION3SETUP"),
    GETNUMROWS_INVENTORYITEMDIMENSION3SETUP(503, "GETNUMROWS_INVENTORYITEMDIMENSION3SETUP"),
    GETDATA_INVENTORYITEMDIMENSION3SETUP(504, "GETDATA_INVENTORYITEMDIMENSION3SETUP"),
    VALIDATEFIELD_INVENTORYITEMDIMENSION3SETUP(505, "VALIDATEFIELD_INVENTORYITEMDIMENSION3SETUP"),
    //Inventory Item Dimension Combinations DS
    INSERT_INVENTORYITEMDIMENSIONCOMBINATIONSDS(520, "INSERT_INVENTORYITEMDIMENSIONCOMBINATIONSDS"),
    UPDATE_INVENTORYITEMDIMENSIONCOMBINATIONSDS(521, "UPDATE_INVENTORYITEMDIMENSIONCOMBINATIONSDS"),
    DELETE_INVENTORYITEMDIMENSIONCOMBINATIONSDS(522, "DELETE_INVENTORYITEMDIMENSIONCOMBINATIONSDS"),
    GETNUMROWS_INVENTORYITEMDIMENSIONCOMBINATIONSDS(523, "GETNUMROWS_INVENTORYITEMDIMENSIONCOMBINATIONSDS"),
    GETDATA_INVENTORYITEMDIMENSIONCOMBINATIONSDS(524, "GETDATA_INVENTORYITEMDIMENSIONCOMBINATIONSDS"),
    VALIDATEFIELD_INVENTORYITEMDIMENSIONCOMBINATIONSDS(525, "VALIDATEFIELD_INVENTORYITEMDIMENSIONCOMBINATIONSDS"),
    //Inventory Item Classification1
    INSERT_INVENTORYITEMCLASSIFICATION1(540, "INSERT_INVENTORYITEMCLASSIFICATION1"),
    UPDATE_INVENTORYITEMCLASSIFICATION1(541, "UPDATE_INVENTORYITEMCLASSIFICATION1"),
    DELETE_INVENTORYITEMCLASSIFICATION1(542, "DELETE_INVENTORYITEMCLASSIFICATION1"),
    GETNUMROWS_INVENTORYITEMCLASSIFICATION1(543, "GETNUMROWS_INVENTORYITEMCLASSIFICATION1"),
    GETDATA_INVENTORYITEMCLASSIFICATION1(544, "GETDATA_INVENTORYITEMCLASSIFICATION1"),
    VALIDATEFIELD_INVENTORYITEMCLASSIFICATION1(545, "VALIDATEFIELD_INVENTORYITEMCLASSIFICATION1"),
    //Inventory Dimension 1 GroupSetup DS
    INSERT_INVENTORYDIMENSION1GROUPSETUPDS(560, "INSERT_INVENTORYDIMENSION1GROUPSETUPDS"),
    UPDATE_INVENTORYDIMENSION1GROUPSETUPDS(561, "UPDATE_INVENTORYDIMENSION1GROUPSETUPDS"),
    DELETE_INVENTORYDIMENSION1GROUPSETUPDS(562, "DELETE_INVENTORYDIMENSION1GROUPSETUPDS"),
    GETNUMROWS_INVENTORYDIMENSION1GROUPSETUPDS(563, "GETNUMROWS_INVENTORYDIMENSION1GROUPSETUPDS"),
    GETDATA_INVENTORYDIMENSION1GROUPSETUPDS(564, "GETDATA_INVENTORYDIMENSION1GROUPSETUPDS"),
    VALIDATEFIELD_INVENTORYDIMENSION1GROUPSETUPDS(565, "VALIDATEFIELD_INVENTORYDIMENSION1GROUPSETUPDS"),
    //Inventory Dimension 2 Group Setup DS
    INSERT_INVENTORYDIMENSION2GROUPSETUPDS(580, "INSERT_INVENTORYDIMENSION2GROUPSETUPDS"),
    UPDATE_INVENTORYDIMENSION2GROUPSETUPDS(581, "UPDATE_INVENTORYDIMENSION2GROUPSETUPDS"),
    DELETE_INVENTORYDIMENSION2GROUPSETUPDS(582, "DELETE_INVENTORYDIMENSION2GROUPSETUPDS"),
    GETNUMROWS_INVENTORYDIMENSION2GROUPSETUPDS(583, "GETNUMROWS_INVENTORYDIMENSION2GROUPSETUPDS"),
    GETDATA_INVENTORYDIMENSION2GROUPSETUPDS(584, "GETDATA_INVENTORYDIMENSION2GROUPSETUPDS"),
    VALIDATEFIELD_INVENTORYDIMENSION2GROUPSETUPDS(585, "VALIDATEFIELD_INVENTORYDIMENSION2GROUPSETUPDS"),
    //Inventory Dimension 3 Group Setup DS
    INSERT_INVENTORYDIMENSION3GROUPSETUPDS(580, "INSERT_INVENTORYDIMENSION3GROUPSETUPDS"),
    UPDATE_INVENTORYDIMENSION3GROUPSETUPDS(581, "UPDATE_INVENTORYDIMENSION3GROUPSETUPDS"),
    DELETE_INVENTORYDIMENSION3GROUPSETUPDS(582, "DELETE_INVENTORYDIMENSION3GROUPSETUPDS"),
    GETNUMROWS_INVENTORYDIMENSION3GROUPSETUPDS(583, "GETNUMROWS_INVENTORYDIMENSION3GROUPSETUPDS"),
    GETDATA_INVENTORYDIMENSION3GROUPSETUPDS(584, "GETDATA_INVENTORYDIMENSION3GROUPSETUPDS"),
    VALIDATEFIELD_INVENTORYDIMENSION3GROUPSETUPDS(585, "VALIDATEFIELD_INVENTORYDIMENSION3GROUPSETUPDS"),
    //Inventory Item Dimension 1 Setup DS
    INSERT_INVENTORYITEMDIMENSION1SETUPDS(600, "INSERT_INVENTORYITEMDIMENSION1SETUPDS"),
    UPDATE_INVENTORYITEMDIMENSION1SETUPDS(601, "UPDATE_INVENTORYITEMDIMENSION1SETUPDS"),
    DELETE_INVENTORYITEMDIMENSION1SETUPDS(602, "DELETE_INVENTORYITEMDIMENSION1SETUPDS"),
    GETNUMROWS_INVENTORYITEMDIMENSION1SETUPDS(603, "GETNUMROWS_INVENTORYITEMDIMENSION1SETUPDS"),
    GETDATA_INVENTORYITEMDIMENSION1SETUPDS(604, "GETDATA_INVENTORYITEMDIMENSION1SETUPDS"),
    VALIDATEFIELD_INVENTORYITEMDIMENSION1SETUPDS(605, "VALIDATEFIELD_INVENTORYITEMDIMENSION1SETUPDS"),
    //Inventory Item Dimension 2 Setup DS
    INSERT_INVENTORYITEMDIMENSION2SETUPDS(620, "INSERT_INVENTORYITEMDIMENSION2SETUPDS"),
    UPDATE_INVENTORYITEMDIMENSION2SETUPDS(621, "UPDATE_INVENTORYITEMDIMENSION2SETUPDS"),
    DELETE_INVENTORYITEMDIMENSION2SETUPDS(622, "DELETE_INVENTORYITEMDIMENSION2SETUPDS"),
    GETNUMROWS_INVENTORYITEMDIMENSION2SETUPDS(623, "GETNUMROWS_INVENTORYITEMDIMENSION2SETUPDS"),
    GETDATA_INVENTORYITEMDIMENSION2SETUPDS(624, "GETDATA_INVENTORYITEMDIMENSION2SETUPDS"),
    VALIDATEFIELD_INVENTORYITEMDIMENSION2SETUPDS(625, "VALIDATEFIELD_INVENTORYITEMDIMENSION2SETUPDS"),
    //Inventory Item Dimension 3 Setup DS
    INSERT_INVENTORYITEMDIMENSION3SETUPDS(640, "INSERT_INVENTORYITEMDIMENSION3SETUPDS"),
    UPDATE_INVENTORYITEMDIMENSION3SETUPDS(641, "UPDATE_INVENTORYITEMDIMENSION3SETUPDS"),
    DELETE_INVENTORYITEMDIMENSION3SETUPDS(642, "DELETE_INVENTORYITEMDIMENSION3SETUPDS"),
    GETNUMROWS_INVENTORYITEMDIMENSION3SETUPDS(643, "GETNUMROWS_INVENTORYITEMDIMENSION3SETUPDS"),
    GETDATA_INVENTORYITEMDIMENSION3SETUPDS(644, "GETDATA_INVENTORYITEMDIMENSION3SETUPDS"),
    VALIDATEFIELD_INVENTORYITEMDIMENSION3SETUPDS(645, "VALIDATEFIELD_INVENTORYITEMDIMENSION3SETUPDS"),
    REMOVE_INACTIVE(646, "REMOVE_INACTIVE"),
    //InventoryItemGroup
    INSERT_INVENTORYITEMGROUP(660, "INSERT_INVENTORYITEMGROUP"),
    UPDATE_INVENTORYITEMGROUP(661, "UPDATE_INVENTORYITEMGROUP"),
    DELETE_INVENTORYITEMGROUP(662, "DELETE_INVENTORYITEMGROUP"),
    GETNUMROWS_INVENTORYITEMGROUP(663, "GETNUMROWS_INVENTORYITEMGROUP"),
    GETDATA_INVENTORYITEMGROUP(664, "GETDATA_INVENTORYITEMGROUP"),
    VALIDATEFIELD_INVENTORYITEMGROUP(665, "VALIDATEFIELD_INVENTORYITEMGROUP"),
    //InventoryItemReference
    INSERT_INVENTORYITEMREFERENCE(680, "INSERT_INVENTORYITEMREFERENCE"),
    UPDATE_INVENTORYITEMREFERENCE(681, "UPDATE_INVENTORYITEMREFERENCE"),
    DELETE_INVENTORYITEMREFERENCE(682, "DELETE_INVENTORYITEMREFERENCE"),
    GETNUMROWS_INVENTORYITEMREFERENCE(683, "GETNUMROWS_INVENTORYITEMREFERENCE"),
    GETDATA_INVENTORYITEMREFERENCE(684, "GETDATA_INVENTORYITEMREFERENCE"),
    VALIDATEFIELD_INVENTORYITEMREFERENCE(685, "VALIDATEFIELD_INVENTORYITEMREFERENCE"),
    //InventoryItemClassification2
    INSERT_INVENTORYITEMCLASSIFICATION2(700, "INSERT_INVENTORYITEMCLASSIFICATION2"),
    UPDATE_INVENTORYITEMCLASSIFICATION2(701, "UPDATE_INVENTORYITEMCLASSIFICATION2"),
    DELETE_INVENTORYITEMCLASSIFICATION2(702, "DELETE_INVENTORYITEMCLASSIFICATION2"),
    GETNUMROWS_INVENTORYITEMCLASSIFICATION2(703, "GETNUMROWS_INVENTORYITEMCLASSIFICATION2"),
    GETDATA_INVENTORYITEMCLASSIFICATION2(704, "GETDATA_INVENTORYITEMCLASSIFICATION2"),
    VALIDATEFIELD_INVENTORYITEMCLASSIFICATION2(705, "VALIDATEFIELD_INVENTORYITEMCLASSIFICATION2"),
    //InventoryItemClassification3
    INSERT_INVENTORYITEMCLASSIFICATION3(720, "INSERT_INVENTORYITEMCLASSIFICATION3"),
    UPDATE_INVENTORYITEMCLASSIFICATION3(721, "UPDATE_INVENTORYITEMCLASSIFICATION3"),
    DELETE_INVENTORYITEMCLASSIFICATION3(722, "DELETE_INVENTORYITEMCLASSIFICATION3"),
    GETNUMROWS_INVENTORYITEMCLASSIFICATION3(723, "GETNUMROWS_INVENTORYITEMCLASSIFICATION3"),
    GETDATA_INVENTORYITEMCLASSIFICATION3(724, "GETDATA_INVENTORYITEMCLASSIFICATION3"),
    VALIDATEFIELD_INVENTORYITEMCLASSIFICATION3(725, "VALIDATEFIELD_INVENTORYITEMCLASSIFICATION3"),
    //InventoryItemClassification4
    INSERT_INVENTORYITEMCLASSIFICATION4(740, "INSERT_INVENTORYITEMCLASSIFICATION4"),
    UPDATE_INVENTORYITEMCLASSIFICATION4(741, "UPDATE_INVENTORYITEMCLASSIFICATION4"),
    DELETE_INVENTORYITEMCLASSIFICATION4(742, "DELETE_INVENTORYITEMCLASSIFICATION4"),
    GETNUMROWS_INVENTORYITEMCLASSIFICATION4(743, "GETNUMROWS_INVENTORYITEMCLASSIFICATION4"),
    GETDATA_INVENTORYITEMCLASSIFICATION4(744, "GETDATA_INVENTORYITEMCLASSIFICATION4"),
    VALIDATEFIELD_INVENTORYITEMCLASSIFICATION4(745, "VALIDATEFIELD_INVENTORYITEMCLASSIFICATION4"),
    //InventoryItemClassification5
    INSERT_INVENTORYITEMCLASSIFICATION5(760, "INSERT_INVENTORYITEMCLASSIFICATION5"),
    UPDATE_INVENTORYITEMCLASSIFICATION5(761, "UPDATE_INVENTORYITEMCLASSIFICATION5"),
    DELETE_INVENTORYITEMCLASSIFICATION5(762, "DELETE_INVENTORYITEMCLASSIFICATION5"),
    GETNUMROWS_INVENTORYITEMCLASSIFICATION5(763, "GETNUMROWS_INVENTORYITEMCLASSIFICATION5"),
    GETDATA_INVENTORYITEMCLASSIFICATION5(764, "GETDATA_INVENTORYITEMCLASSIFICATION5"),
    VALIDATEFIELD_INVENTORYITEMCLASSIFICATION5(765, "VALIDATEFIELD_INVENTORYITEMCLASSIFICATION5"),
    //InventoryItemClassification6
    INSERT_INVENTORYITEMCLASSIFICATION6(780, "INSERT_INVENTORYITEMCLASSIFICATION6"),
    UPDATE_INVENTORYITEMCLASSIFICATION6(781, "UPDATE_INVENTORYITEMCLASSIFICATION6"),
    DELETE_INVENTORYITEMCLASSIFICATION6(782, "DELETE_INVENTORYITEMCLASSIFICATION6"),
    GETNUMROWS_INVENTORYITEMCLASSIFICATION6(783, "GETNUMROWS_INVENTORYITEMCLASSIFICATION6"),
    GETDATA_INVENTORYITEMCLASSIFICATION6(784, "GETDATA_INVENTORYITEMCLASSIFICATION6"),
    VALIDATEFIELD_INVENTORYITEMCLASSIFICATION6(785, "VALIDATEFIELD_INVENTORYITEMCLASSIFICATION6"),
    //InventoryReferenceType
    INSERT_INVENTORYREFERENCETYPE(800, "INSERT_INVENTORYREFERENCETYPE"),
    UPDATE_INVENTORYREFERENCETYPE(801, "UPDATE_INVENTORYREFERENCETYPE"),
    DELETE_INVENTORYREFERENCETYPE(802, "DELETE_INVENTORYREFERENCETYPE"),
    GETNUMROWS_INVENTORYREFERENCETYPE(803, "GETNUMROWS_INVENTORYREFERENCETYPE"),
    GETDATA_INVENTORYREFERENCETYPE(804, "GETDATA_INVENTORYREFERENCETYPE"),
    VALIDATEFIELD_INVENTORYREFERENCETYPE(805, "VALIDATEFIELD_INVENTORYREFERENCETYPE"),
    //InventoryReference
    INSERT_INVENTORYREFERENCE(820, "INSERT_INVENTORYREFERENCE"),
    UPDATE_INVENTORYREFERENCE(821, "UPDATE_INVENTORYREFERENCE"),
    DELETE_INVENTORYREFERENCE(822, "DELETE_INVENTORYREFERENCE"),
    GETNUMROWS_INVENTORYREFERENCE(823, "GETNUMROWS_INVENTORYREFERENCE"),
    GETDATA_INVENTORYREFERENCE(824, "GETDATA_INVENTORYREFERENCE"),
    VALIDATEFIELD_INVENTORYREFERENCE(825, "VALIDATEFIELD_INVENTORYREFERENCE"),
    IMPORT_REFERENCES(826, "IMPORT_REFERENCES"),
    //InventorySummary
    INSERT_INVENTORYSUMMARY(840, "INSERT_INVENTORYSUMMARY"),
    UPDATE_INVENTORYSUMMARY(841, "UPDATE_INVENTORYSUMMARY"),
    DELETE_INVENTORYSUMMARY(842, "DELETE_INVENTORYSUMMARY"),
    GETNUMROWS_INVENTORYSUMMARY(843, "GETNUMROWS_INVENTORYSUMMARY"),
    GETDATA_INVENTORYSUMMARY(844, "GETDATA_INVENTORYSUMMARY"),
    VALIDATEFIELD_INVENTORYSUMMARY(845, "VALIDATEFIELD_INVENTORYSUMMARY"),
    PRINT_SUMMARY(846, "PRINT_SUMMARY"),
    PRINT_BELOW_MINIMUM(847, "PRINT_BELOW_MINIMUM"),
    PRINT_STOCK_USAGE(848, "PRINT_STOCK_USAGE"),
    FIX_BLANKET_ORDER_SUMMARIES(849, "FIX_BLANKET_ORDER_SUMMARIES"),
    //InventoryTransactionsDS
    INSERT_INVENTORYTRANSACTIONSDS(860, "INSERT_INVENTORYTRANSACTIONSDS"),
    UPDATE_INVENTORYTRANSACTIONSDS(861, "UPDATE_INVENTORYTRANSACTIONSDS"),
    DELETE_INVENTORYTRANSACTIONSDS(862, "DELETE_INVENTORYTRANSACTIONSDS"),
    GETNUMROWS_INVENTORYTRANSACTIONSDS(863, "GETNUMROWS_INVENTORYTRANSACTIONSDS"),
    GETDATA_INVENTORYTRANSACTIONSDS(864, "GETDATA_INVENTORYTRANSACTIONSDS"),
    VALIDATEFIELD_INVENTORYTRANSACTIONSDS(865, "VALIDATEFIELD_INVENTORYTRANSACTIONSDS"),
    //InventorySummaryDS
    INSERT_INVENTORYSUMMARYDS(880, "INSERT_INVENTORYSUMMARYDS"),
    UPDATE_INVENTORYSUMMARYDS(881, "UPDATE_INVENTORYSUMMARYDS"),
    DELETE_INVENTORYSUMMARYDS(882, "DELETE_INVENTORYSUMMARYDS"),
    GETNUMROWS_INVENTORYSUMMARYDS(883, "GETNUMROWS_INVENTORYSUMMARYDS"),
    GETDATA_INVENTORYSUMMARYDS(884, "GETDATA_INVENTORYSUMMARYDS"),
    VALIDATEFIELD_INVENTORYSUMMARYDS(885, "VALIDATEFIELD_INVENTORYSUMMARYDS"),
    //InventoryItemDimension1SetupFormDS
    INSERT_INVENTORYITEMDIMENSION1SETUPFORMDS(900, "INSERT_INVENTORYITEMDIMENSION1SETUPFORMDS"),
    UPDATE_INVENTORYITEMDIMENSION1SETUPFORMDS(901, "UPDATE_INVENTORYITEMDIMENSION1SETUPFORMDS"),
    DELETE_INVENTORYITEMDIMENSION1SETUPFORMDS(902, "DELETE_INVENTORYITEMDIMENSION1SETUPFORMDS"),
    GETNUMROWS_INVENTORYITEMDIMENSION1SETUPFORMDS(903, "GETNUMROWS_INVENTORYITEMDIMENSION1SETUPFORMDS"),
    GETDATA_INVENTORYITEMDIMENSION1SETUPFORMDS(904, "GETDATA_INVENTORYITEMDIMENSION1SETUPFORMDS"),
    VALIDATEFIELD_INVENTORYITEMDIMENSION1SETUPFORMDS(905, "VALIDATEFIELD_INVENTORYITEMDIMENSION1SETUPFORMDS"),
    //InventoryItemDimension2SetupFormDS
    INSERT_INVENTORYITEMDIMENSION2SETUPFORMDS(920, "INSERT_INVENTORYITEMDIMENSION2SETUPFORMDS"),
    UPDATE_INVENTORYITEMDIMENSION2SETUPFORMDS(921, "UPDATE_INVENTORYITEMDIMENSION2SETUPFORMDS"),
    DELETE_INVENTORYITEMDIMENSION2SETUPFORMDS(922, "DELETE_INVENTORYITEMDIMENSION2SETUPFORMDS"),
    GETNUMROWS_INVENTORYITEMDIMENSION2SETUPFORMDS(923, "GETNUMROWS_INVENTORYITEMDIMENSION2SETUPFORMDS"),
    GETDATA_INVENTORYITEMDIMENSION2SETUPFORMDS(924, "GETDATA_INVENTORYITEMDIMENSION2SETUPFORMDS"),
    VALIDATEFIELD_INVENTORYITEMDIMENSION2SETUPFORMDS(925, "VALIDATEFIELD_INVENTORYITEMDIMENSION2SETUPFORMDS"),
    //InventoryItemDimension3SetupFormDS
    INSERT_INVENTORYITEMDIMENSION3SETUPFORMDS(940, "INSERT_INVENTORYITEMDIMENSION3SETUPFORMDS"),
    UPDATE_INVENTORYITEMDIMENSION3SETUPFORMDS(941, "UPDATE_INVENTORYITEMDIMENSION3SETUPFORMDS"),
    DELETE_INVENTORYITEMDIMENSION3SETUPFORMDS(942, "DELETE_INVENTORYITEMDIMENSION3SETUPFORMDS"),
    GETNUMROWS_INVENTORYITEMDIMENSION3SETUPFORMDS(943, "GETNUMROWS_INVENTORYITEMDIMENSION3SETUPFORMDS"),
    GETDATA_INVENTORYITEMDIMENSION3SETUPFORMDS(944, "GETDATA_INVENTORYITEMDIMENSION3SETUPFORMDS"),
    VALIDATEFIELD_INVENTORYITEMDIMENSION3SETUPFORMDS(945, "VALIDATEFIELD_INVENTORYITEMDIMENSION3SETUPFORMDS"),
    //InventoryItemAccessGroup
    INSERT_INVENTORYITEMACCESSGROUP(960, "INSERT_INVENTORYITEMACCESSGROUP"),
    UPDATE_INVENTORYITEMACCESSGROUP(961, "UPDATE_INVENTORYITEMACCESSGROUP"),
    DELETE_INVENTORYITEMACCESSGROUP(962, "DELETE_INVENTORYITEMACCESSGROUP"),
    GETNUMROWS_INVENTORYITEMACCESSGROUP(963, "GETNUMROWS_INVENTORYITEMACCESSGROUP"),
    GETDATA_INVENTORYITEMACCESSGROUP(964, "GETDATA_INVENTORYITEMACCESSGROUP"),
    VALIDATEFIELD_INVENTORYITEMACCESSGROUP(965, "VALIDATEFIELD_INVENTORYITEMACCESSGROUP"),
    //InventoryItemAccessGroupEmployees
    INSERT_INVENTORYITEMACCESSGROUPEMPLOYEES(980, "INSERT_INVENTORYITEMACCESSGROUPEMPLOYEESDS"),
    UPDATE_INVENTORYITEMACCESSGROUPEMPLOYEES(981, "UPDATE_INVENTORYITEMACCESSGROUPEMPLOYEESDS"),
    DELETE_INVENTORYITEMACCESSGROUPEMPLOYEES(982, "DELETE_INVENTORYITEMACCESSGROUPEMPLOYEESDS"),
    GETNUMROWS_INVENTORYITEMACCESSGROUPEMPLOYEES(983, "GETNUMROWS_INVENTORYITEMACCESSGROUPEMPLOYEESDS"),
    GETDATA_INVENTORYITEMACCESSGROUPEMPLOYEES(984, "GETDATA_INVENTORYITEMACCESSGROUPEMPLOYEESDS"),
    VALIDATEFIELD_INVENTORYITEMACCESSGROUPEMPLOYEES(985, "VALIDATEFIELD_INVENTORYITEMACCESSGROUPEMPLOYEESDS"),
    //Inventory Journal Lines DS
    INSERT_INVENTORYJOURNALLINESDS(1000, "INSERT_INVENTORYJOURNALLINESDS"),
    UPDATE_INVENTORYJOURNALLINESDS(1001, "UPDATE_INVENTORYJOURNALLINESDS"),
    DELETE_INVENTORYJOURNALLINESDS(1002, "DELETE_INVENTORYJOURNALLINESDS"),
    GETNUMROWS_INVENTORYJOURNALLINESDS(1003, "GETNUMROWS_INVENTORYJOURNALLINESDS"),
    GETDATA_INVENTORYJOURNALLINESDS(1004, "GETDATA_INVENTORYJOURNALLINESDS"),
    VALIDATEFIELD_INVENTORYJOURNALLINESDS(1005, "VALIDATEFIELD_INVENTORYJOURNALLINESDS"),
    //InventoryColourDesignMaster
    INSERT_INVENTORYCOLOURDESIGNMASTER(1020, "INSERT_INVENTORYCOLOURDESIGNMASTER"),
    UPDATE_INVENTORYCOLOURDESIGNMASTER(1021, "UPDATE_INVENTORYCOLOURDESIGNMASTER"),
    DELETE_INVENTORYCOLOURDESIGNMASTER(1022, "DELETE_INVENTORYCOLOURDESIGNMASTER"),
    GETNUMROWS_INVENTORYCOLOURDESIGNMASTER(1023, "GETNUMROWS_INVENTORYCOLOURDESIGNMASTER"),
    GETDATA_INVENTORYCOLOURDESIGNMASTER(1024, "GETDATA_INVENTORYCOLOURDESIGNMASTER"),
    VALIDATEFIELD_INVENTORYCOLOURDESIGNMASTER(1025, "VALIDATEFIELD_INVENTORYCOLOURDESIGNMASTER"),
    //InventoryItemMasterLookupDS
    INSERT_INVENTORYITEMMASTERLOOKUPDS(1040, "INSERT_INVENTORYITEMMASTERLOOKUPDS"),
    UPDATE_INVENTORYITEMMASTERLOOKUPDS(1041, "UPDATE_INVENTORYITEMMASTERLOOKUPDS"),
    DELETE_INVENTORYITEMMASTERLOOKUPDS(1042, "DELETE_INVENTORYITEMMASTERLOOKUPDS"),
    GETNUMROWS_INVENTORYITEMMASTERLOOKUPDS(1043, "GETNUMROWS_INVENTORYITEMMASTERLOOKUPDS"),
    GETDATA_INVENTORYITEMMASTERLOOKUPDS(1044, "GETDATA_INVENTORYITEMMASTERLOOKUPDS"),
    VALIDATEFIELD_INVENTORYITEMMASTERLOOKUPDS(1045, "VALIDATEFIELD_INVENTORYITEMMASTERLOOKUPDS"),
    //Inventory Classification Hierarchy
    INSERT_INVENTORYCLASSIFICATIONHIERARCHY(1060, "INSERT_INVENTORYCLASSIFICATIONHIERARCHY"),
    UPDATE_INVENTORYCLASSIFICATIONHIERARCHY(1061, "UPDATE_INVENTORYCLASSIFICATIONHIERARCHY"),
    DELETE_INVENTORYCLASSIFICATIONHIERARCHY(1062, "DELETE_INVENTORYCLASSIFICATIONHIERARCHY"),
    GETNUMROWS_INVENTORYCLASSIFICATIONHIERARCHY(1063, "GETNUMROWS_INVENTORYCLASSIFICATIONHIERARCHY"),
    GETDATA_INVENTORYCLASSIFICATIONHIERARCHY(1064, "GETDATA_INVENTORYCLASSIFICATIONHIERARCHY"),
    VALIDATEFIELD_INVENTORYCLASSIFICATIONHIERARCHY(1065, "VALIDATEFIELD_INVENTORYCLASSIFICATIONHIERARCHY"),
    //Inventory Item Classification
    INSERT_INVENTORYITEMCLASSIFICATION(1080, "INSERT_INVENTORYITEMCLASSIFICATION"),
    UPDATE_INVENTORYITEMCLASSIFICATION(1081, "UPDATE_INVENTORYITEMCLASSIFICATION"),
    DELETE_INVENTORYITEMCLASSIFICATION(1082, "DELETE_INVENTORYITEMCLASSIFICATION"),
    GETNUMROWS_INVENTORYITEMCLASSIFICATION(1083, "GETNUMROWS_INVENTORYITEMCLASSIFICATION"),
    GETDATA_INVENTORYITEMCLASSIFICATION(1084, "GETDATA_INVENTORYITEMCLASSIFICATION"),
    VALIDATEFIELD_INVENTORYITEMCLASSIFICATION(1085, "VALIDATEFIELD_INVENTORYITEMCLASSIFICATION"),
    //Inventory Journal Master DS
    INSERT_INVENTORYJOURNALMASTERDS(1100, "INSERT_INVENTORYJOURNALMASTERDS"),
    UPDATE_INVENTORYJOURNALMASTERDS(1101, "UPDATE_INVENTORYJOURNALMASTERDS"),
    DELETE_INVENTORYJOURNALMASTERDS(1102, "DELETE_INVENTORYJOURNALMASTERDS"),
    GETNUMROWS_INVENTORYJOURNALMASTERDS(1103, "GETNUMROWS_INVENTORYJOURNALMASTERDS"),
    GETDATA_INVENTORYJOURNALMASTERDS(1104, "GETDATA_INVENTORYJOURNALMASTERDS"),
    VALIDATEFIELD_INVENTORYJOURNALMASTERDS(1105, "VALIDATEFIELD_INVENTORYJOURNALMASTERDS"),
    //InventoryParameters
    INSERT_INVENTORYPARAMETERS(1120, "INSERT_INVENTORYPARAMETERS"),
    UPDATE_INVENTORYPARAMETERS(1121, "UPDATE_INVENTORYPARAMETERS"),
    DELETE_INVENTORYPARAMETERS(1122, "DELETE_INVENTORYPARAMETERS"),
    GETNUMROWS_INVENTORYPARAMETERS(1123, "GETNUMROWS_INVENTORYPARAMETERS"),
    GETDATA_INVENTORYPARAMETERS(1124, "GETDATA_INVENTORYPARAMETERS"),
    VALIDATEFIELD_INVENTORYPARAMETERS(1125, "VALIDATEFIELD_INVENTORYPARAMETERS"),
    GET_INVENTORY_PARAMETERS(1126, "GET_INVENTORY_PARAMETERS"),
    //InventoryTransactions
    INSERT_INVENTORYTRANSACTIONS(1140, "INSERT_INVENTORYTRANSACTIONS"),
    UPDATE_INVENTORYTRANSACTIONS(1141, "UPDATE_INVENTORYTRANSACTIONS"),
    DELETE_INVENTORYTRANSACTIONS(1142, "DELETE_INVENTORYTRANSACTIONS"),
    GETNUMROWS_INVENTORYTRANSACTIONS(1143, "GETNUMROWS_INVENTORYTRANSACTIONS"),
    GETDATA_INVENTORYTRANSACTIONS(1144, "GETDATA_INVENTORYTRANSACTIONS"),
    VALIDATEFIELD_INVENTORYTRANSACTIONS(1145, "VALIDATEFIELD_INVENTORYTRANSACTIONS"),
    //InventoryItemMasterDS
    INSERT_INVENTORYITEMMASTERDS(1160, "INSERT_INVENTORYITEMMASTERDS"),
    UPDATE_INVENTORYITEMMASTERDS(1161, "UPDATE_INVENTORYITEMMASTERDS"),
    DELETE_INVENTORYITEMMASTERDS(1162, "DELETE_INVENTORYITEMMASTERDS"),
    GETNUMROWS_INVENTORYITEMMASTERDS(1163, "GETNUMROWS_INVENTORYITEMMASTERDS"),
    GETDATA_INVENTORYITEMMASTERDS(1164, "GETDATA_INVENTORYITEMMASTERDS"),
    VALIDATEFIELD_INVENTORYITEMMASTERDS(1165, "VALIDATEFIELD_INVENTORYITEMMASTERDS"),
    //InventoryReferenceDS
    INSERT_INVENTORYREFERENCEDS(1180, "INSERT_INVENTORYREFERENCEDS"),
    UPDATE_INVENTORYREFERENCEDS(1181, "UPDATE_INVENTORYREFERENCEDS"),
    DELETE_INVENTORYREFERENCEDS(1182, "DELETE_INVENTORYREFERENCEDS"),
    GETNUMROWS_INVENTORYREFERENCEDS(1183, "GETNUMROWS_INVENTORYREFERENCEDS"),
    GETDATA_INVENTORYREFERENCEDS(1184, "GETDATA_INVENTORYREFERENCEDS"),
    VALIDATEFIELD_INVENTORYREFERENCEDS(1185, "VALIDATEFIELD_INVENTORYREFERENCEDS"),
    //InventorySupplierReference
    INSERT_INVENTORYSUPPLIERREFERENCE(2000, "INSERT_INVENTORYSUPPLIERREFERENCE"),
    UPDATE_INVENTORYSUPPLIERREFERENCE(2001, "UPDATE_INVENTORYSUPPLIERREFERENCE"),
    DELETE_INVENTORYSUPPLIERREFERENCE(2002, "DELETE_INVENTORYSUPPLIERREFERENCE"),
    GETNUMROWS_INVENTORYSUPPLIERREFERENCE(2003, "GETNUMROWS_INVENTORYSUPPLIERREFERENCE"),
    GETDATA_INVENTORYSUPPLIERREFERENCE(2004, "GETDATA_INVENTORYSUPPLIERREFERENCE"),
    VALIDATEFIELD_INVENTORYSUPPLIERREFERENCE(2005, "VALIDATEFIELD_INVENTORYSUPPLIERREFERENCE"),
    //InventorySupplierReferenceDS
    INSERT_INVENTORYSUPPLIERREFERENCEDS(2020, "INSERT_INVENTORYSUPPLIERREFERENCEDS"),
    UPDATE_INVENTORYSUPPLIERREFERENCEDS(2021, "UPDATE_INVENTORYSUPPLIERREFERENCEDS"),
    DELETE_INVENTORYSUPPLIERREFERENCEDS(2022, "DELETE_INVENTORYSUPPLIERREFERENCEDS"),
    GETNUMROWS_INVENTORYSUPPLIERREFERENCEDS(2023, "GETNUMROWS_INVENTORYSUPPLIERREFERENCEDS"),
    GETDATA_INVENTORYSUPPLIERREFERENCEDS(2024, "GETDATA_INVENTORYSUPPLIERREFERENCEDS"),
    VALIDATEFIELD_INVENTORYSUPPLIERREFERENCEDS(2025, "VALIDATEFIELD_INVENTORYSUPPLIERREFERENCEDS"),
    //InventoryBarcodesDS
    INSERT_INVENTORYBARCODESDS(2040, "INSERT_INVENTORYBARCODESDS"),
    UPDATE_INVENTORYBARCODESDS(2041, "UPDATE_INVENTORYBARCODESDS"),
    DELETE_INVENTORYBARCODESDS(2042, "DELETE_INVENTORYBARCODESDS"),
    GETNUMROWS_INVENTORYBARCODESDS(2043, "GETNUMROWS_INVENTORYBARCODESDS"),
    GETDATA_INVENTORYBARCODESDS(2044, "GETDATA_INVENTORYBARCODESDS"),
    VALIDATEFIELD_INVENTORYBARCODESDS(2045, "VALIDATEFIELD_INVENTORYBARCODESDS"),
    //RemoveSerialBatch
    INSERT_INVENTORYREMOVESERIALBATCH(2060, "INSERT_INVENTORYREMOVESERIALBATCH"),
    UPDATE_INVENTORYREMOVESERIALBATCH(2061, "UPDATE_INVENTORYREMOVESERIALBATCH"),
    DELETE_INVENTORYREMOVESERIALBATCH(2062, "DELETE_INVENTORYREMOVESERIALBATCH"),
    GETNUMROWS_INVENTORYREMOVESERIALBATCH(2063, "GETNUMROWS_INVENTORYREMOVESERIALBATCH"),
    GETDATA_INVENTORYREMOVESERIALBATCH(2064, "GETDATA_INVENTORYREMOVESERIALBATCH"),
    VALIDATEFIELD_INVENTORYREMOVESERIALBATCH(2065, "VALIDATEFIELD_INVENTORYREMOVESERIALBATCH"),
    POPULATE_TABLE(2066, "POPULATE_TABLE"),
    CHECK_REMOVED_REG(2067, "CHECK_REMOVED_REG"),
    CHECK_REMOVED_REG_ALL(2069, "CHECK_REMOVE_REG_ALL"),
    DELETE_POST_DATA(2070, "DELETE_POST_DATA"),
    //InventorySerialBatch
    INSERT_INVENTORYSERIALBATCH(2080, "INSERT_INVENTORYSERIALBATCH"),
    UPDATE_INVENTORYSERIALBATCH(2081, "UPDATE_INVENTORYSERIALBATCH"),
    DELETE_INVENTORYSERIALBATCH(2082, "DELETE_INVENTORYSERIALBATCH"),
    GETNUMROWS_INVENTORYSERIALBATCH(2083, "GETNUMROWS_INVENTORYSERIALBATCH"),
    GETDATA_INVENTORYSERIALBATCH(2084, "GETDATA_INVENTORYSERIALBATCH"),
    VALIDATEFIELD_INVENTORYSERIALBATCH(2085, "VALIDATEFIELD_INVENTORYSERIALBATCH"),
    //Inventory Requirements Planning
    INSERT_INVENTORYREQUIREMENTSPLANNING(3000, "INSERT_INVENTORYREQUIREMENTSPLANNING"),
    UPDATE_INVENTORYREQUIREMENTSPLANNING(3001, "UPDATE_INVENTORYREQUIREMENTSPLANNING"),
    DELETE_INVENTORYREQUIREMENTSPLANNING(3002, "DELETE_INVENTORYREQUIREMENTSPLANNING"),
    GETNUMROWS_INVENTORYREQUIREMENTSPLANNING(3003, "GETNUMROWS_INVENTORYREQUIREMENTSPLANNING"),
    GETDATA_INVENTORYREQUIREMENTSPLANNING(3004, "GETDATA_INVENTORYREQUIREMENTSPLANNING"),
    VALIDATEFIELD_INVENTORYREQUIREMENTSPLANNING(3005, "VALIDATEFIELD_INVENTORYREQUIREMENTSPLANNING"),
    CLEAR_TABLE_FOR_REPOPULATION(3006, "CLEAR_TABLE_FOR_REPOPULATION"),
    GET_FORECAST_ITEMS(3007, "GET_FORECAST_ITEMS"),
    REPOPULATE_WITH_FORECAST(3008, "REPOPULATE_WITH_FORECAST"),
    GET_SALES_ITEMS(3009, "GET_SALES_ITEMS"),
    REPOPULATE_WITH_SALES(3010, "REPOPULATE_WITH_SALES"),
    GET_PLANNED_PURCHASING_ITEMS(3011, "GET_PLANNED_PURCHASING_ITEMS"),
    REPOPULATE_WITH_PLANNED_PURCHASING(3012, "REPOPULATE_WITH_PLANNED_PURCHASING"),
    GET_PURCHASING_ITEMS(3013, "GET_PURCHASING_ITEMS"),
    REPOPULATE_WITH_PURCHASING(3014, "REPOPULATE_WITH_PURCHASING"),
    GET_PLANNED_PRODUCTION_ITEMS(3015, "GET_PLANNED_PRODUCTION_ITEMS"),
    REPOPULATE_WITH_PLANNED_PPRODUCTION(3016, "REPOPULATE_WITH_PLANNED_PPRODUCTION"),
    GET_PRODUCTION_ITEMS(3017, "GET_PRODUCTION_ITEMS"),
    REPOPULATE_WITH_PRODUCTION(3018, "REPOPULATE_WITH_PRODUCTION"),
    UPDATE_EXPLODED_REQUIREMENTS(3019, "UPDATE_EXPLODED_REQUIREMENTS"),
    CLEAN_UP_REQUIREMENTS(2999, "CLEAN_UP_REQUIREMENTS"),
    //InventoryPallet
    INSERT_INVENTORYPALLET(3020, "INSERT_INVENTORYPALLET"),
    UPDATE_INVENTORYPALLET(3021, "UPDATE_INVENTORYPALLET"),
    DELETE_INVENTORYPALLET(3022, "DELETE_INVENTORYPALLET"),
    GETNUMROWS_INVENTORYPALLET(3023, "GETNUMROWS_INVENTORYPALLET"),
    GETDATA_INVENTORYPALLET(3024, "GETDATA_INVENTORYPALLET"),
    VALIDATEFIELD_INVENTORYPALLET(3025, "VALIDATEFIELD_INVENTORYPALLET"),
    //InventoryLocation
    INSERT_INVENTORYLOCATION(3040, "INSERT_INVENTORYLOCATION"),
    UPDATE_INVENTORYLOCATION(3041, "UPDATE_INVENTORYLOCATION"),
    DELETE_INVENTORYLOCATION(3042, "DELETE_INVENTORYLOCATION"),
    GETNUMROWS_INVENTORYLOCATION(3043, "GETNUMROWS_INVENTORYLOCATION"),
    GETDATA_INVENTORYLOCATION(3044, "GETDATA_INVENTORYLOCATION"),
    VALIDATEFIELD_INVENTORYLOCATION(3045, "VALIDATEFIELD_INVENTORYLOCATION"),
    //InventoryMoveStockMaster
    INSERT_INVENTORYMOVESTOCKMASTER(3080, "INSERT_INVENTORYMOVESTOCKMASTER"),
    UPDATE_INVENTORYMOVESTOCKMASTER(3081, "UPDATE_INVENTORYMOVESTOCKMASTER"),
    DELETE_INVENTORYMOVESTOCKMASTER(3082, "DELETE_INVENTORYMOVESTOCKMASTER"),
    GETNUMROWS_INVENTORYMOVESTOCKMASTER(3083, "GETNUMROWS_INVENTORYMOVESTOCKMASTER"),
    GETDATA_INVENTORYMOVESTOCKMASTER(3084, "GETDATA_INVENTORYMOVESTOCKMASTER"),
    VALIDATEFIELD_INVENTORYMOVESTOCKMASTER(3085, "VALIDATEFIELD_INVENTORYMOVESTOCKMASTER"),
    MOVE_STOCK(3086, "MOVE_STOCK"),
    POPULATE_MOVE_STOCK(3087, "POPULATE_MOVE_STOCK"),
    POPULATE_MOVE_RESERVED_STOCK(3088, "POPULATE_MOVE_RESERVED_STOCK"),
    MOVE_RESERVED_STOCK(3089, "MOVE_RESERVED_STOCK"),
    //InventoryMoveStockMasterDS
    INSERT_INVENTORYMOVESTOCKMASTERDS(3100, "INSERT_INVENTORYMOVESTOCKMASTERDS"),
    UPDATE_INVENTORYMOVESTOCKMASTERDS(3101, "UPDATE_INVENTORYMOVESTOCKMASTERDS"),
    DELETE_INVENTORYMOVESTOCKMASTERDS(3102, "DELETE_INVENTORYMOVESTOCKMASTERDS"),
    GETNUMROWS_INVENTORYMOVESTOCKMASTERDS(3103, "GETNUMROWS_INVENTORYMOVESTOCKMASTERDS"),
    GETDATA_INVENTORYMOVESTOCKMASTERDS(3104, "GETDATA_INVENTORYMOVESTOCKMASTERDS"),
    VALIDATEFIELD_INVENTORYMOVESTOCKMASTERDS(3105, "VALIDATEFIELD_INVENTORYMOVESTOCKMASTERDS"),
    //InventoryMoveStockLines
    INSERT_INVENTORYMOVESTOCKLINES(3120, "INSERT_INVENTORYMOVESTOCKLINES"),
    UPDATE_INVENTORYMOVESTOCKLINES(3121, "UPDATE_INVENTORYMOVESTOCKLINES"),
    DELETE_INVENTORYMOVESTOCKLINES(3122, "DELETE_INVENTORYMOVESTOCKLINES"),
    GETNUMROWS_INVENTORYMOVESTOCKLINES(3123, "GETNUMROWS_INVENTORYMOVESTOCKLINES"),
    GETDATA_INVENTORYMOVESTOCKLINES(3124, "GETDATA_INVENTORYMOVESTOCKLINES"),
    VALIDATEFIELD_INVENTORYMOVESTOCKLINES(3125, "VALIDATEFIELD_INVENTORYMOVESTOCKLINES"),
    //InventoryMoveStockSummary
    INSERT_INVENTORYMOVESTOCKSUMMARY(3140, "INSERT_INVENTORYMOVESTOCKSUMMARY"),
    UPDATE_INVENTORYMOVESTOCKSUMMARY(3141, "UPDATE_INVENTORYMOVESTOCKSUMMARY"),
    DELETE_INVENTORYMOVESTOCKSUMMARY(3142, "DELETE_INVENTORYMOVESTOCKSUMMARY"),
    GETNUMROWS_INVENTORYMOVESTOCKSUMMARY(3143, "GETNUMROWS_INVENTORYMOVESTOCKSUMMARY"),
    GETDATA_INVENTORYMOVESTOCKSUMMARY(3144, "GETDATA_INVENTORYMOVESTOCKSUMMARY"),
    VALIDATEFIELD_INVENTORYMOVESTOCKSUMMARY(3145, "VALIDATEFIELD_INVENTORYMOVESTOCKSUMMARY"),
    //InventoryMoveStockSummaryDS
    INSERT_INVENTORYMOVESTOCKSUMMARYDS(3160, "INSERT_INVENTORYMOVESTOCKSUMMARYDS"),
    UPDATE_INVENTORYMOVESTOCKSUMMARYDS(3161, "UPDATE_INVENTORYMOVESTOCKSUMMARYDS"),
    DELETE_INVENTORYMOVESTOCKSUMMARYDS(3162, "DELETE_INVENTORYMOVESTOCKSUMMARYDS"),
    GETNUMROWS_INVENTORYMOVESTOCKSUMMARYDS(3163, "GETNUMROWS_INVENTORYMOVESTOCKSUMMARYDS"),
    GETDATA_INVENTORYMOVESTOCKSUMMARYDS(3164, "GETDATA_INVENTORYMOVESTOCKSUMMARYDS"),
    VALIDATEFIELD_INVENTORYMOVESTOCKSUMMARYDS(3165, "VALIDATEFIELD_INVENTORYMOVESTOCKSUMMARYDS"),
   
  
   
    //InventoryRegister
    INSERT_INVENTORYREGISTER(3420, "INSERT_INVENTORYREGISTER"),
    UPDATE_INVENTORYREGISTER(3421, "UPDATE_INVENTORYREGISTER"),
    DELETE_INVENTORYREGISTER(3422, "DELETE_INVENTORYREGISTER"),
    GETNUMROWS_INVENTORYREGISTER(3423, "GETNUMROWS_INVENTORYREGISTER"),
    GETDATA_INVENTORYREGISTER(3424, "GETDATA_INVENTORYREGISTER"),
    VALIDATEFIELD_INVENTORYREGISTER(3425, "VALIDATEFIELD_INVENTORYREGISTER"),
    GET_REGISTER_COLUMNS(3426, "GET_REGISTER_COLUMNS"),
    //InventoryRemoveRegister
    INSERT_INVENTORYREMOVEREGISTER(3440, "INSERT_INVENTORYREMOVEREGISTER"),
    UPDATE_INVENTORYREMOVEREGISTER(3441, "UPDATE_INVENTORYREMOVEREGISTER"),
    DELETE_INVENTORYREMOVEREGISTER(3442, "DELETE_INVENTORYREMOVEREGISTER"),
    GETNUMROWS_INVENTORYREMOVEREGISTER(3443, "GETNUMROWS_INVENTORYREMOVEREGISTER"),
    GETDATA_INVENTORYREMOVEREGISTER(3444, "GETDATA_INVENTORYREMOVEREGISTER"),
    VALIDATEFIELD_INVENTORYREMOVEREGISTER(3445, "VALIDATEFIELD_INVENTORYREMOVEREGISTER"),
    //Inventory Additional Dimensions DS
    INSERT_INVENTORYADDITIONALDIMENSIONSDS(3460, "INSERT_INVENTORYADDITIONALDIMENSIONSDS"),
    UPDATE_INVENTORYADDITIONALDIMENSIONSDS(3461, "UPDATE_INVENTORYADDITIONALDIMENSIONSDS"),
    DELETE_INVENTORYADDITIONALDIMENSIONSDS(3462, "DELETE_INVENTORYADDITIONALDIMENSIONSDS"),
    GETNUMROWS_INVENTORYADDITIONALDIMENSIONSDS(3463, "GETNUMROWS_INVENTORYADDITIONALDIMENSIONSDS"),
    GETDATA_INVENTORYADDITIONALDIMENSIONSDS(3464, "GETDATA_INVENTORYADDITIONALDIMENSIONSDS"),
    VALIDATEFIELD_INVENTORYADDITIONALDIMENSIONSDS(3465, "VALIDATEFIELD_INVENTORYADDITIONALDIMENSIONSDS"),
    //Inventory Additional Dimensions
    INSERT_INVENTORYADDITIONALDIMENSIONS(3466, "INSERT_INVENTORYADDITIONALDIMENSIONS"),
    UPDATE_INVENTORYADDITIONALDIMENSIONS(3467, "UPDATE_INVENTORYADDITIONALDIMENSIONS"),
    DELETE_INVENTORYADDITIONALDIMENSIONS(3468, "DELETE_INVENTORYADDITIONALDIMENSIONS"),
    GETNUMROWS_INVENTORYADDITIONALDIMENSIONS(3469, "GETNUMROWS_INVENTORYADDITIONALDIMENSIONS"),
    GETDATA_INVENTORYADDITIONALDIMENSIONS(3470, "GETDATA_INVENTORYADDITIONALDIMENSIONS"),
    VALIDATEFIELD_INVENTORYADDITIONALDIMENSIONS(3471, "VALIDATEFIELD_INVENTORYADDITIONALDIMENSIONS"),
  
    //Stock Valuation Report
    PRINT_STOCK_VALUATION_REPORT(3520, "PRINT_STOCK_VALUATION_REPORT"),
    //Stock By Location Report
    PRINT_STOCK_BY_LOCATION_REPORT(3540, "PRINT_STOCK_BY_LOCATION_REPORT"),
    PRINT_MOVEMENT_JOURNAL_SUMMARY(3541, "PRINT_MOVEMENT_JOURNAL_SUMMARY"),
    PRINT_MOVEMENT_JOURNAL_DETAIL(3542, "PRINT_MOVEMENT_JOURNAL_DETAIL"),
    //AgeBins
    INSERT_INVENTORYAGEBINS(3560, "INSERT_INVENTORYAGEBINS"),
    UPDATE_INVENTORYAGEBINS(3561, "UPDATE_INVENTORYAGEBINS"),
    DELETE_INVENTORYAGEBINS(3562, "DELETE_INVENTORYAGEBINS"),
    GETNUMROWS_INVENTORYAGEBINS(3563, "GETNUMROWS_INVENTORYAGEBINS"),
    GETDATA_INVENTORYAGEBINS(3564, "GETDATA_INVENTORYAGEBINS"),
    VALIDATEFIELD_INVENTORYAGEBINS(3565, "VALIDATEFIELD_INVENTORYAGEBINS"),
    PRINT_INVENTAGEING(3566, "PRINT_INVENTAGEING"),
    GET_BIN_LABELS(3567, "GET_BIN_LABELS"),
    PRINT_INVENTAGEING_DETAIL(3568, "PRINT_INVENTAGEING_DETAIL"),
    PRINT_INVENTAGEING_FULL_DETAIL(3569, "PRINT_INVENTAGEING_FULL_DETAIL"),
    //InventoryStockSettlement
    INSERT_INVENTORYSTOCKSETTLEMENT(3580, "INSERT_INVENTORYSTOCKSETTLEMENT"),
    UPDATE_INVENTORYSTOCKSETTLEMENT(3581, "UPDATE_INVENTORYSTOCKSETTLEMENT"),
    DELETE_INVENTORYSTOCKSETTLEMENT(3582, "DELETE_INVENTORYSTOCKSETTLEMENT"),
    GETNUMROWS_INVENTORYSTOCKSETTLEMENT(3583, "GETNUMROWS_INVENTORYSTOCKSETTLEMENT"),
    GETDATA_INVENTORYSTOCKSETTLEMENT(3584, "GETDATA_INVENTORYSTOCKSETTLEMENT"),
    VALIDATEFIELD_INVENTORYSTOCKSETTLEMENT(3585, "VALIDATEFIELD_INVENTORYSTOCKSETTLEMENT"),
    RUN_STOCKSETTLEMENT(3586, "RUN_STOCKSETTLEMENT"),
    ROLL_BACK_STOCKSETTLEMENT(3587, "ROLL_BACK_STOCKSETTLEMENT"),
    SET_CLOSE_DATE_NULL(3588, "SET_CLOSE_DATE_NULL"),
    //InventoryStockSettlementHistory
    INSERT_INVENTORYSTOCKSETTLEMENTHISTORY(3600, "INSERT_INVENTORYSTOCKSETTLEMENTHISTORY"),
    UPDATE_INVENTORYSTOCKSETTLEMENTHISTORY(3601, "UPDATE_INVENTORYSTOCKSETTLEMENTHISTORY"),
    DELETE_INVENTORYSTOCKSETTLEMENTHISTORY(3602, "DELETE_INVENTORYSTOCKSETTLEMENTHISTORY"),
    GETNUMROWS_INVENTORYSTOCKSETTLEMENTHISTORY(3603, "GETNUMROWS_INVENTORYSTOCKSETTLEMENTHISTORY"),
    GETDATA_INVENTORYSTOCKSETTLEMENTHISTORY(3604, "GETDATA_INVENTORYSTOCKSETTLEMENTHISTORY"),
    VALIDATEFIELD_INVENTORYSTOCKSETTLEMENTHISTORY(3605, "VALIDATEFIELD_INVENTORYSTOCKSETTLEMENTHISTORY"),
    //InventoryStocktakeRegister
    INSERT_INVENTORYSTOCKTAKEREGISTER(3620, "INSERT_INVENTORYSTOCKTAKEREGISTER"),
    UPDATE_INVENTORYSTOCKTAKEREGISTER(3621, "UPDATE_INVENTORYSTOCKTAKEREGISTER"),
    DELETE_INVENTORYSTOCKTAKEREGISTER(3622, "DELETE_INVENTORYSTOCKTAKEREGISTER"),
    GETNUMROWS_INVENTORYSTOCKTAKEREGISTER(3623, "GETNUMROWS_INVENTORYSTOCKTAKEREGISTER"),
    GETDATA_INVENTORYSTOCKTAKEREGISTER(3624, "GETDATA_INVENTORYSTOCKTAKEREGISTER"),
    VALIDATEFIELD_INVENTORYSTOCKTAKEREGISTER(3625, "VALIDATEFIELD_INVENTORYSTOCKTAKEREGISTER"),
    GET_ST_REGISTER_COLUMNS(3626, "GET_ST_REGISTER_COLUMNS"),
    //StocktakeReports
    PRINT_STOCK_TAKE_VARIANCE(3640, "PRINT_STOCK_TAKE_VARIANCE"),
    PRINT_STOCK_TAKE_REPORT(3641, "PRINT_STOCK_TAKE_REPORT"),
    PRINT_STOCK_TAKE_RECOUNT_REPORT(3642, "PRINT_STOCK_TAKE_RECOUNT_REPORT"),
    //InventoryStocktakeCaptureDS
    INSERT_INVENTORYSTOCKTAKECAPTUREDS(3660, "INSERT_INVENTORYSTOCKTAKECAPTUREDS"),
    UPDATE_INVENTORYSTOCKTAKECAPTUREDS(3661, "UPDATE_INVENTORYSTOCKTAKECAPTUREDS"),
    DELETE_INVENTORYSTOCKTAKECAPTUREDS(3662, "DELETE_INVENTORYSTOCKTAKECAPTUREDS"),
    GETNUMROWS_INVENTORYSTOCKTAKECAPTUREDS(3663, "GETNUMROWS_INVENTORYSTOCKTAKECAPTUREDS"),
    GETDATA_INVENTORYSTOCKTAKECAPTUREDS(3664, "GETDATA_INVENTORYSTOCKTAKECAPTUREDS"),
    VALIDATEFIELD_INVENTORYSTOCKTAKECAPTUREDS(3665, "VALIDATEFIELD_INVENTORYSTOCKTAKECAPTUREDS"),
    //Inventory Dimension 1 Lines
    INSERT_INVENTORYDIMENSION1LINES(3700, "INSERT_INVENTORYDIMENSION1LINES"),
    UPDATE_INVENTORYDIMENSION1LINES(3701, "UPDATE_INVENTORYDIMENSION1LINES"),
    DELETE_INVENTORYDIMENSION1LINES(3702, "DELETE_INVENTORYDIMENSION1LINES"),
    GETNUMROWS_INVENTORYDIMENSION1LINES(3703, "GETNUMROWS_INVENTORYDIMENSION1LINES"),
    GETDATA_INVENTORYDIMENSION1LINES(3704, "GETDATA_INVENTORYDIMENSION1LINES"),
    VALIDATEFIELD_INVENTORYDIMENSION1LINES(3705, "VALIDATEFIELD_INVENTORYDIMENSION1LINES"),
    //Inventory Dimension 1 Lines DS
    INSERT_INVENTORYDIMENSION1LINESDS(3720, "INSERT_INVENTORYDIMENSION1LINESDS"),
    UPDATE_INVENTORYDIMENSION1LINESDS(3721, "UPDATE_INVENTORYDIMENSION1LINESDS"),
    DELETE_INVENTORYDIMENSION1LINESDS(3722, "DELETE_INVENTORYDIMENSION1LINESDS"),
    GETNUMROWS_INVENTORYDIMENSION1LINESDS(3723, "GETNUMROWS_INVENTORYDIMENSION1LINESDS"),
    GETDATA_INVENTORYDIMENSION1LINESDS(3724, "GETDATA_INVENTORYDIMENSION1LINESDS"),
    VALIDATEFIELD_INVENTORYDIMENSION1LINESDS(3725, "VALIDATEFIELD_INVENTORYDIMENSION1LINESDS"),
    //Inventory Customer Reference
    INSERT_INVENTORYCUSTOMERREFERENCE(3740, "INSERT_INVENTORYCUSTOMERREFERENCE"),
    UPDATE_INVENTORYCUSTOMERREFERENCE(3741, "UPDATE_INVENTORYCUSTOMERREFERENCE"),
    DELETE_INVENTORYCUSTOMERREFERENCE(3742, "DELETE_INVENTORYCUSTOMERREFERENCE"),
    GETNUMROWS_INVENTORYCUSTOMERREFERENCE(3743, "GETNUMROWS_INVENTORYCUSTOMERREFERENCE"),
    GETDATA_INVENTORYCUSTOMERREFERENCE(3744, "GETDATA_INVENTORYCUSTOMERREFERENCE"),
    VALIDATEFIELD_INVENTORYCUSTOMERREFERENCE(3745, "VALIDATEFIELD_INVENTORYCUSTOMERREFERENCE"),
    //Inventory Customer Reference DS
    INSERT_INVENTORYCUSTOMERREFERENCEDS(3760, "INSERT_INVENTORYCUSTOMERREFERENCEDS"),
    UPDATE_INVENTORYCUSTOMERREFERENCEDS(3761, "UPDATE_INVENTORYCUSTOMERREFERENCEDS"),
    DELETE_INVENTORYCUSTOMERREFERENCEDS(3762, "DELETE_INVENTORYCUSTOMERREFERENCEDS"),
    GETNUMROWS_INVENTORYCUSTOMERREFERENCEDS(3763, "GETNUMROWS_INVENTORYCUSTOMERREFERENCEDS"),
    GETDATA_INVENTORYCUSTOMERREFERENCEDS(3764, "GETDATA_INVENTORYCUSTOMERREFERENCEDS"),
    VALIDATEFIELD_INVENTORYCUSTOMERREFERENCEDS(3765, "VALIDATEFIELD_INVENTORYCUSTOMERREFERENCEDS"),
    //InventoryProductGroup
    INSERT_INVENTORYPRODUCTGROUP(3780, "INSERT_INVENTORYPRODUCTGROUP"),
    UPDATE_INVENTORYPRODUCTGROUP(3781, "UPDATE_INVENTORYPRODUCTGROUP"),
    DELETE_INVENTORYPRODUCTGROUP(3782, "DELETE_INVENTORYPRODUCTGROUP"),
    GETNUMROWS_INVENTORYPRODUCTGROUP(3783, "GETNUMROWS_INVENTORYPRODUCTGROUP"),
    GETDATA_INVENTORYPRODUCTGROUP(3784, "GETDATA_INVENTORYPRODUCTGROUP"),
    VALIDATEFIELD_INVENTORYPRODUCTGROUP(3785, "VALIDATEFIELD_INVENTORYPRODUCTGROUP"),
    //Dimension1 Report
    PRINT_DIMENSION1_REPORT(3800, "PRINT_DIMENSION1_REPORT"),
    //InventoryDimension1WhereUsed
    INSERT_INVENTORYDIMENSION1WHEREUSED(3820, "INSERT_INVENTORYDIMENSION1WHEREUSED"),
    UPDATE_INVENTORYDIMENSION1WHEREUSED(3821, "UPDATE_INVENTORYDIMENSION1WHEREUSED"),
    DELETE_INVENTORYDIMENSION1WHEREUSED(3822, "DELETE_INVENTORYDIMENSION1WHEREUSED"),
    GETNUMROWS_INVENTORYDIMENSION1WHEREUSED(3823, "GETNUMROWS_INVENTORYDIMENSION1WHEREUSED"),
    GETDATA_INVENTORYDIMENSION1WHEREUSED(3824, "GETDATA_INVENTORYDIMENSION1WHEREUSED"),
    VALIDATEFIELD_INVENTORYDIMENSION1WHEREUSED(3825, "VALIDATEFIELD_INVENTORYDIMENSION1WHEREUSED"),
    //InventoryRequirementsPlanningDS
    INSERT_INVENTORYREQUIREMENTSPLANNINGDS(3840, "INSERT_INVENTORYREQUIREMENTSPLANNINGDS"),
    UPDATE_INVENTORYREQUIREMENTSPLANNINGDS(3841, "UPDATE_INVENTORYREQUIREMENTSPLANNINGDS"),
    DELETE_INVENTORYREQUIREMENTSPLANNINGDS(3842, "DELETE_INVENTORYREQUIREMENTSPLANNINGDS"),
    GETNUMROWS_INVENTORYREQUIREMENTSPLANNINGDS(3843, "GETNUMROWS_INVENTORYREQUIREMENTSPLANNINGDS"),
    GETDATA_INVENTORYREQUIREMENTSPLANNINGDS(3844, "GETDATA_INVENTORYREQUIREMENTSPLANNINGDS"),
    VALIDATEFIELD_INVENTORYREQUIREMENTSPLANNINGDS(3845, "VALIDATEFIELD_INVENTORYREQUIREMENTSPLANNINGDS"),
    //InventoryRequirementsPlanningHistoryDS
    INSERT_INVENTORYREQUIREMENTSPLANNINGHISTORYDS(3860, "INSERT_INVENTORYREQUIREMENTSPLANNINGHISTORYDS"),
    UPDATE_INVENTORYREQUIREMENTSPLANNINGHISTORYDS(3861, "UPDATE_INVENTORYREQUIREMENTSPLANNINGHISTORYDS"),
    DELETE_INVENTORYREQUIREMENTSPLANNINGHISTORYDS(3862, "DELETE_INVENTORYREQUIREMENTSPLANNINGHISTORYDS"),
    GETNUMROWS_INVENTORYREQUIREMENTSPLANNINGHISTORYDS(3863, "GETNUMROWS_INVENTORYREQUIREMENTSPLANNINGHISTORYDS"),
    GETDATA_INVENTORYREQUIREMENTSPLANNINGHISTORYDS(3864, "GETDATA_INVENTORYREQUIREMENTSPLANNINGHISTORYDS"),
    VALIDATEFIELD_INVENTORYREQUIREMENTSPLANNINGHISTORYDS(3865, "VALIDATEFIELD_INVENTORYREQUIREMENTSPLANNINGHISTORYDS"),
  
    //Open Dispatch Orders
    PRINT_OPEN_DISPATCH_ORDERS(4001, "PRINT_OPEN_DISPATCH_ORDERS"),
    //InventoryWarehouseStockEnquiry
    INSERT_INVENTORYWAREHOUSESTOCKENQUIRY(4020, "INSERT_INVENTORYWAREHOUSESTOCKENQUIRY"),
    UPDATE_INVENTORYWAREHOUSESTOCKENQUIRY(4021, "UPDATE_INVENTORYWAREHOUSESTOCKENQUIRY"),
    DELETE_INVENTORYWAREHOUSESTOCKENQUIRY(4022, "DELETE_INVENTORYWAREHOUSESTOCKENQUIRY"),
    GETNUMROWS_INVENTORYWAREHOUSESTOCKENQUIRY(4023, "GETNUMROWS_INVENTORYWAREHOUSESTOCKENQUIRY"),
    GETDATA_INVENTORYWAREHOUSESTOCKENQUIRY(4024, "GETDATA_INVENTORYWAREHOUSESTOCKENQUIRY"),
    VALIDATEFIELD_INVENTORYWAREHOUSESTOCKENQUIRY(4025, "VALIDATEFIELD_INVENTORYWAREHOUSESTOCKENQUIRY"),
    POPULATE_INVENTORYWAREHOUSESTOCKENQUIRY(4026, "POPULATE_INVENTORYWAREHOUSESTOCKENQUIRY"),
  
    //InventoryWarehouseStockEnquiryBySize
    INSERT_INVENTORYWAREHOUSESTOCKENQUIRYBYSIZE(4060, "INSERT_INVENTORYWAREHOUSESTOCKENQUIRYBYSIZE"),
    UPDATE_INVENTORYWAREHOUSESTOCKENQUIRYBYSIZE(4061, "UPDATE_INVENTORYWAREHOUSESTOCKENQUIRYBYSIZE"),
    DELETE_INVENTORYWAREHOUSESTOCKENQUIRYBYSIZE(4062, "DELETE_INVENTORYWAREHOUSESTOCKENQUIRYBYSIZE"),
    GETNUMROWS_INVENTORYWAREHOUSESTOCKENQUIRYBYSIZE(4063, "GETNUMROWS_INVENTORYWAREHOUSESTOCKENQUIRYBYSIZE"),
    GETDATA_INVENTORYWAREHOUSESTOCKENQUIRYBYSIZE(4064, "GETDATA_INVENTORYWAREHOUSESTOCKENQUIRYBYSIZE"),
    VALIDATEFIELD_INVENTORYWAREHOUSESTOCKENQUIRYBYSIZE(4065, "VALIDATEFIELD_INVENTORYWAREHOUSESTOCKENQUIRYBYSIZE"),
    POPULATE_INVENTORYWAREHOUSESTOCKENQUIRYBYSIZE(4066, "POPULATE_INVENTORYWAREHOUSESTOCKENQUIRYBYSIZE"),
    //Inventory With No Demand
    PRINT_INVENTORY_WITH_NO_DEMANS(4080, "PRINT_INVENTORY_WITH_NO_DEMANS"),
    //InventoryPegging
    ORDER_DEMAND_SUPPLY(4100, "ORDER_DEMAND_SUPPLY"),
    ITEM_DEMAND_SUPPLY(4101, "ITEM_DEMAND_SUPPLY"),
    //InventoryStockTakeLogger
    INSERT_INVENTORYSTOCKTAKELOGGER(4120, "INSERT_INVENTORYSTOCKTAKELOGGER"),
    UPDATE_INVENTORYSTOCKTAKELOGGER(4121, "UPDATE_INVENTORYSTOCKTAKELOGGER"),
    DELETE_INVENTORYSTOCKTAKELOGGER(4122, "DELETE_INVENTORYSTOCKTAKELOGGER"),
    GETNUMROWS_INVENTORYSTOCKTAKELOGGER(4123, "GETNUMROWS_INVENTORYSTOCKTAKELOGGER"),
    GETDATA_INVENTORYSTOCKTAKELOGGER(4124, "GETDATA_INVENTORYSTOCKTAKELOGGER"),
    VALIDATEFIELD_INVENTORYSTOCKTAKELOGGER(4125, "VALIDATEFIELD_INVENTORYSTOCKTAKELOGGER"),
    //InventoryDimension3WhereUsed
    INSERT_INVENTORYDIMENSION3WHEREUSED(4140, "INSERT_INVENTORYDIMENSION3WHEREUSED"),
    UPDATE_INVENTORYDIMENSION3WHEREUSED(4141, "UPDATE_INVENTORYDIMENSION3WHEREUSED"),
    DELETE_INVENTORYDIMENSION3WHEREUSED(4142, "DELETE_INVENTORYDIMENSION3WHEREUSED"),
    GETNUMROWS_INVENTORYDIMENSION3WHEREUSED(4143, "GETNUMROWS_INVENTORYDIMENSION3WHEREUSED"),
    GETDATA_INVENTORYDIMENSION3WHEREUSED(4144, "GETDATA_INVENTORYDIMENSION3WHEREUSED"),
    VALIDATEFIELD_INVENTORYDIMENSION3WHEREUSED(4145, "VALIDATEFIELD_INVENTORYDIMENSION3WHEREUSED"),
    //InventoryStocktakeUnreserved
    INSERT_INVENTORYSTOCKTAKEUNRESERVED(4160, "INSERT_INVENTORYSTOCKTAKEUNRESERVED"),
    UPDATE_INVENTORYSTOCKTAKEUNRESERVED(4161, "UPDATE_INVENTORYSTOCKTAKEUNRESERVED"),
    DELETE_INVENTORYSTOCKTAKEUNRESERVED(4162, "DELETE_INVENTORYSTOCKTAKEUNRESERVED"),
    GETNUMROWS_INVENTORYSTOCKTAKEUNRESERVED(4163, "GETNUMROWS_INVENTORYSTOCKTAKEUNRESERVED"),
    GETDATA_INVENTORYSTOCKTAKEUNRESERVED(4164, "GETDATA_INVENTORYSTOCKTAKEUNRESERVED"),
    VALIDATEFIELD_INVENTORYSTOCKTAKEUNRESERVED(4165, "VALIDATEFIELD_INVENTORYSTOCKTAKEUNRESERVED"),
    CLEAR_STOCKTAKEUNRESERVED(4166, "CLEAR_STOCKTAKEUNRESERVED"),
    //InventoryStocktakeUnreservedDS
    INSERT_INVENTORYSTOCKTAKEUNRESERVEDDS(4180, "INSERT_INVENTORYSTOCKTAKEUNRESERVEDDS"),
    UPDATE_INVENTORYSTOCKTAKEUNRESERVEDDS(4181, "UPDATE_INVENTORYSTOCKTAKEUNRESERVEDDS"),
    DELETE_INVENTORYSTOCKTAKEUNRESERVEDDS(4182, "DELETE_INVENTORYSTOCKTAKEUNRESERVEDDS"),
    GETNUMROWS_INVENTORYSTOCKTAKEUNRESERVEDDS(4183, "GETNUMROWS_INVENTORYSTOCKTAKEUNRESERVEDDS"),
    GETDATA_INVENTORYSTOCKTAKEUNRESERVEDDS(4184, "GETDATA_INVENTORYSTOCKTAKEUNRESERVEDDS"),
    VALIDATEFIELD_INVENTORYSTOCKTAKEUNRESERVEDDS(4185, "VALIDATEFIELD_INVENTORYSTOCKTAKEUNRESERVEDDS"),
    //Factory Shop Report
    PRINT_FACTORY_SHOP_REPORT(4200, "PRINT_FACTORY_SHOP_REPORT"),
    //InventorySafetyStock
    INSERT_INVENTORYSAFETYSTOCK(4220, "INSERT_INVENTORYSAFETYSTOCK"),
    UPDATE_INVENTORYSAFETYSTOCK(4221, "UPDATE_INVENTORYSAFETYSTOCK"),
    DELETE_INVENTORYSAFETYSTOCK(4222, "DELETE_INVENTORYSAFETYSTOCK"),
    GETNUMROWS_INVENTORYSAFETYSTOCK(4223, "GETNUMROWS_INVENTORYSAFETYSTOCK"),
    GETDATA_INVENTORYSAFETYSTOCK(4224, "GETDATA_INVENTORYSAFETYSTOCK"),
    VALIDATEFIELD_INVENTORYSAFETYSTOCK(4225, "VALIDATEFIELD_INVENTORYSAFETYSTOCK"),
    GENERATE_SAFETY_STOCK(4226, "GENERATE_SAFETY_STOCK"),
    DELETE_SAFETY_STOCK(4227, "DELETE_SAFETY_STOCK"),
    //InventorySafetyStockDS
    INSERT_INVENTORYSAFETYSTOCKDS(4240, "INSERT_INVENTORYSAFETYSTOCKDS"),
    UPDATE_INVENTORYSAFETYSTOCKDS(4241, "UPDATE_INVENTORYSAFETYSTOCKDS"),
    DELETE_INVENTORYSAFETYSTOCKDS(4242, "DELETE_INVENTORYSAFETYSTOCKDS"),
    GETNUMROWS_INVENTORYSAFETYSTOCKDS(4243, "GETNUMROWS_INVENTORYSAFETYSTOCKDS"),
    GETDATA_INVENTORYSAFETYSTOCKDS(4244, "GETDATA_INVENTORYSAFETYSTOCKDS"),
    VALIDATEFIELD_INVENTORYSAFETYSTOCKDS(4245, "VALIDATEFIELD_INVENTORYSAFETYSTOCKDS"),
    //InventorySafetyStockGenerationRules
    INSERT_INVENTORYSAFETYSTOCKGENERATIONRULES(4260, "INSERT_INVENTORYSAFETYSTOCKGENERATIONRULES"),
    UPDATE_INVENTORYSAFETYSTOCKGENERATIONRULES(4261, "UPDATE_INVENTORYSAFETYSTOCKGENERATIONRULES"),
    DELETE_INVENTORYSAFETYSTOCKGENERATIONRULES(4262, "DELETE_INVENTORYSAFETYSTOCKGENERATIONRULES"),
    GETNUMROWS_INVENTORYSAFETYSTOCKGENERATIONRULES(4263, "GETNUMROWS_INVENTORYSAFETYSTOCKGENERATIONRULES"),
    GETDATA_INVENTORYSAFETYSTOCKGENERATIONRULES(4264, "GETDATA_INVENTORYSAFETYSTOCKGENERATIONRULES"),
    VALIDATEFIELD_INVENTORYSAFETYSTOCKGENERATIONRULES(4265, "VALIDATEFIELD_INVENTORYSAFETYSTOCKGENERATIONRULES"),
    //InventoryPeggingTable
    INSERT_INVENTORYPEGGINGTABLE(4280, "INSERT_INVENTORYPEGGINGTABLE"),
    UPDATE_INVENTORYPEGGINGTABLE(4281, "UPDATE_INVENTORYPEGGINGTABLE"),
    DELETE_INVENTORYPEGGINGTABLE(4282, "DELETE_INVENTORYPEGGINGTABLE"),
    GETNUMROWS_INVENTORYPEGGINGTABLE(4283, "GETNUMROWS_INVENTORYPEGGINGTABLE"),
    GETDATA_INVENTORYPEGGINGTABLE(4284, "GETDATA_INVENTORYPEGGINGTABLE"),
    VALIDATEFIELD_INVENTORYPEGGINGTABLE(4285, "VALIDATEFIELD_INVENTORYPEGGINGTABLE"),
    //InventoryConfigurationEnquiry
    INSERT_INVENTORYDIMENSION1ENQUIRY(4300, "INSERT_INVENTORYDIMENSION1ENQUIRY"),
    UPDATE_INVENTORYDIMENSION1ENQUIRY(4301, "UPDATE_INVENTORYDIMENSION1ENQUIRY"),
    DELETE_INVENTORYDIMENSION1ENQUIRY(4302, "DELETE_INVENTORYDIMENSION1ENQUIRY"),
    GETNUMROWS_INVENTORYDIMENSION1ENQUIRY(4303, "GETNUMROWS_INVENTORYDIMENSION1ENQUIRY"),
    GETDATA_INVENTORYDIMENSION1ENQUIRY(4304, "GETDATA_INVENTORYDIMENSION1ENQUIRY"),
    VALIDATEFIELD_INVENTORYDIMENSION1ENQUIRY(4305, "VALIDATEFIELD_INVENTORYDIMENSION1ENQUIRY"),
    POPULATE_INVENTORYDIMENSION1ENQUIRY(4306, "POPULATE_INVENTORYDIMENSION1ENQUIRY"),
    CLEAR_DIMENSION1ENQUIRYSESSION(4307, "CLEAR_DIMENSION1ENQUIRYSESSION"),
     //InventoryBatchConsolidationMaster
    INSERT_INVENTORYBATCHCONSOLIDATIONMASTER(4340, "INSERT_INVENTORYBATCHCONSOLIDATIONMASTER"),
    UPDATE_INVENTORYBATCHCONSOLIDATIONMASTER(4341, "UPDATE_INVENTORYBATCHCONSOLIDATIONMASTER"),
    DELETE_INVENTORYBATCHCONSOLIDATIONMASTER(4342, "DELETE_INVENTORYBATCHCONSOLIDATIONMASTER"),
    GETNUMROWS_INVENTORYBATCHCONSOLIDATIONMASTER(4343, "GETNUMROWS_INVENTORYBATCHCONSOLIDATIONMASTER"),
    GETDATA_INVENTORYBATCHCONSOLIDATIONMASTER(4344, "GETDATA_INVENTORYBATCHCONSOLIDATIONMASTER"),
    VALIDATEFIELD_INVENTORYBATCHCONSOLIDATIONMASTER(4345, "VALIDATEFIELD_INVENTORYBATCHCONSOLIDATIONMASTER"),
    CREATE_BATCH_CONSOLIDATION(4346, "CREATE_BATCH_CONSOLIDATION"),
    FETCH_MOVEMENT_JOURNAL_FOR_CONSOLIDATION_APPROVAL(4347, "FETCH_MOVEMENT_JOURNAL_FOR_CONSOLIDATION_APPROVAL"),
    FETCH_TRANSFER_JOURNAL_FOR_CONSOLIDATION_APPROVAL(4348, "FETCH_TRANSFER_JOURNAL_FOR_CONSOLIDATION_APPROVAL"),
    APPROVE_CONSOLIDATION(4349, "APPROVE_CONSOLIDATION"),
    FETCH_MOVEMENT_JOURNAL_FOR_CONSOLIDATION_POSTING(4350, "FETCH_MOVEMENT_JOURNAL_FOR_CONSOLIDATION_POSTING"),
    FETCH_TRANSFER_JOURNAL_FOR_CONSOLIDATION_POSTING(4351, "FETCH_TRANSFER_JOURNAL_FOR_CONSOLIDATION_POSTING"),
    POST_CONSOLIDATION(4352, "POST_CONSOLIDATION"),
    FETCH_MOVEMENT_JOURNAL_FOR_CONSOLIDATION_UN_APPROVAL(4353, "FETCH_MOVEMENT_JOURNAL_FOR_CONSOLIDATION_UN_APPROVAL"),
    FETCH_TRANSFER_JOURNAL_FOR_CONSOLIDATION_UN_APPROVAL(4354, "FETCH_TRANSFER_JOURNAL_FOR_CONSOLIDATION_UN_APPROVAL"),
    UN_APPROVE_CONSOLIDATION(4355, "UN_APPROVE_CONSOLIDATION"),
    //InventoryBatchConsolidationLines
    INSERT_INVENTORYBATCHCONSOLIDATIONLINES(4360, "INSERT_INVENTORYBATCHCONSOLIDATIONLINES"),
    UPDATE_INVENTORYBATCHCONSOLIDATIONLINES(4361, "UPDATE_INVENTORYBATCHCONSOLIDATIONLINES"),
    DELETE_INVENTORYBATCHCONSOLIDATIONLINES(4362, "DELETE_INVENTORYBATCHCONSOLIDATIONLINES"),
    GETNUMROWS_INVENTORYBATCHCONSOLIDATIONLINES(4363, "GETNUMROWS_INVENTORYBATCHCONSOLIDATIONLINES"),
    GETDATA_INVENTORYBATCHCONSOLIDATIONLINES(4364, "GETDATA_INVENTORYBATCHCONSOLIDATIONLINES"),
    VALIDATEFIELD_INVENTORYBATCHCONSOLIDATIONLINES(4365, "VALIDATEFIELD_INVENTORYBATCHCONSOLIDATIONLINES"),
    //InventoryBatchConsolidationLinesDS
    INSERT_INVENTORYBATCHCONSOLIDATIONLINESDS(4380, "INSERT_INVENTORYBATCHCONSOLIDATIONLINESDS"),
    UPDATE_INVENTORYBATCHCONSOLIDATIONLINESDS(4381, "UPDATE_INVENTORYBATCHCONSOLIDATIONLINESDS"),
    DELETE_INVENTORYBATCHCONSOLIDATIONLINESDS(4382, "DELETE_INVENTORYBATCHCONSOLIDATIONLINESDS"),
    GETNUMROWS_INVENTORYBATCHCONSOLIDATIONLINESDS(4383, "GETNUMROWS_INVENTORYBATCHCONSOLIDATIONLINESDS"),
    GETDATA_INVENTORYBATCHCONSOLIDATIONLINESDS(4384, "GETDATA_INVENTORYBATCHCONSOLIDATIONLINESDS"),
    VALIDATEFIELD_INVENTORYBATCHCONSOLIDATIONLINESDS(4385, "VALIDATEFIELD_INVENTORYBATCHCONSOLIDATIONLINESDS"),
    //InventoryBatchConsolidation Picking List
    PRINT_BATCH_CONSOLIDATION_PICKING_LIST(4386, "PRINT_BATCH_CONSOLIDATION_PICKING_LIST"),
    //Warehouse/Location Transfer
    PRINT_WAREHOUSE_LOCATION_TRANSFER(4400, "PRINT_WAREHOUSE_LOCATION_TRANSFER"),
    //InventoryReqPlanAudit
    INSERT_INVENTORYREQPLANAUDIT(4420, "INSERT_INVENTORYREQPLANAUDIT"),
    UPDATE_INVENTORYREQPLANAUDIT(4421, "UPDATE_INVENTORYREQPLANAUDIT"),
    DELETE_INVENTORYREQPLANAUDIT(4422, "DELETE_INVENTORYREQPLANAUDIT"),
    GETNUMROWS_INVENTORYREQPLANAUDIT(4423, "GETNUMROWS_INVENTORYREQPLANAUDIT"),
    GETDATA_INVENTORYREQPLANAUDIT(4424, "GETDATA_INVENTORYREQPLANAUDIT"),
    VALIDATEFIELD_INVENTORYREQPLANAUDIT(4425, "VALIDATEFIELD_INVENTORYREQPLANAUDIT"),
    
    GET_FILTERED_INVENTORY_ITEMS_FOR_WEB(4439, "GET_FILTERED_INVENTORY_ITEMS_FOR_WEB"),
    GET_INVENTORY_GROUPS(4440, "GET_INVENTORY_GROUPS"),
    GET_INVENTORY_ITEMS_FOR_WEB(4441, "GET_INVENTORY_ITEMS_FOR_WEB"),
    GET_ITEM_WEB_TYPE(4442,"GET_ITEM_WEB_TYPE");
    //Enum variables
    final int id;
    final String label;

    /**
     * Creates a new instance of ServerCreditorsMethods
     */
    ServerInventoryMethods(final int id, final String label) {
        this.id = id;
        this.label = label;
    }

    public int getId() {
        return id;
    }

    @Override
    public String toString() {
        return label;
    }

    public static ServerInventoryMethods fromString(
            final String str) {
        for (ServerInventoryMethods e : ServerInventoryMethods.values()) {
            if (e.toString().equalsIgnoreCase(str)) {
                return e;
            }

        }
        return null;
    }

    public static ServerInventoryMethods fromId(
            final int id) {
        for (ServerInventoryMethods e : ServerInventoryMethods.values()) {
            if (e.id == id) {
                return e;
            }

        }
        return null;
    }

    public enumEMCModules getEMCModule() {
        return enumEMCModules.INVENTORY;
    }
}
