/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package emc.methods.workflow;

import emc.enums.modules.enumEMCModules;
import emc.methods.EMCMethodEnum;

/**
 *
 * @author rico
 */
public enum ServerWorkFlowMethods implements EMCMethodEnum {

    //Skills
    INSERT_WORKFLOWSKILL(0, "INSERT_WORKFLOWSKILL"),
    UPDATE_WORKFLOWSKILL(1, "UPDATE_WORKFLOWSKILL"),
    DELETE_WORKFLOWSKILL(2, "DELETE_WORKFLOWSKILL"),
    GETNUMROWS_WORKFLOWSKILL(3, "GETNUMROWS_WORKFLOWSKILL"),
    GETDATA_WORKFLOWSKILL(4, "GETDATA_WORKFLOWSKILL"),
    VALIDATEFIELD_WORKFLOWSKILL(5, "VALIDATEFIELD_WORKFLOWSKILL"),
    //Ratings
    INSERT_WORKFLOWRATING(20, "INSERT_WORKFLOWRATING"),
    UPDATE_WORKFLOWRATING(21, "UPDATE_WORKFLOWRATING"),
    DELETE_WORKFLOWRATING(22, "DELETE_WORKFLOWRATING"),
    GETNUMROWS_WORKFLOWRATING(23, "GETNUMROWS_WORKFLOWRATING"),
    GETDATA_WORKFLOWRATING(24, "GETDATA_WORKFLOWRATING"),
    VALIDATEFIELD_WORKFLOWRATING(25, "VALIDATEFIELD_WORKFLOWRATING"),
    //JobTitles
    INSERT_WORKFLOWJOBTITLES(40, "INSERT_WORKFLOWJOBTITLES"),
    UPDATE_WORKFLOWJOBTITLES(41, "UPDATE_WORKFLOWJOBTITLES"),
    DELETE_WORKFLOWJOBTITLES(42, "DELETE_WORKFLOWJOBTITLES"),
    GETNUMROWS_WORKFLOWJOBTITLES(43, "GETNUMROWS_WORKFLOWJOBTITLES"),
    GETDATA_WORKFLOWJOBTITLES(44, "GETDATA_WORKFLOWJOBTITLES"),
    VALIDATEFIELD_WORKFLOWJOBTITLES(45, "VALIDATEFIELD_WORKFLOWJOBTITLES"),
    //Employee Types
    INSERT_WORKFLOWEMPLOYEETYPE(60, "INSERT_WORKFLOWEMPLOYEETYPE"),
    UPDATE_WORKFLOWEMPLOYEETYPE(61, "UPDATE_WORKFLOWEMPLOYEETYPE"),
    DELETE_WORKFLOWEMPLOYEETYPE(62, "DELETE_WORKFLOWEMPLOYEETYPE"),
    GETNUMROWS_WORKFLOWEMPLOYEETYPE(63, "GETNUMROWS_WORKFLOWEMPLOYEETYPE"),
    GETDATA_WORKFLOWEMPLOYEETYPE(64, "GETDATA_WORKFLOWEMPLOYEETYPE"),
    VALIDATEFIELD_WORKFLOWEMPLOYEETYPE(65, "VALIDATEFIELD_WORKFLOWEMPLOYEETYPE"),
    //Employee Skills
    INSERT_WORKFLOWEMPLOYEESKILLS(80, "INSERT_WORKFLOWEMPLOYEESKILLS"),
    UPDATE_WORKFLOWEMPLOYEESKILLS(82, "UPDATE_WORKFLOWEMPLOYEESKILLS"),
    DELETE_WORKFLOWEMPLOYEESKILLS(83, "DELETE_WORKFLOWEMPLOYEESKILLS"),
    GETNUMROWS_WORKFLOWEMPLOYEESKILLS(84, "GETNUMROWS_WORKFLOWEMPLOYEESKILLS"),
    GETDATA_WORKFLOWEMPLOYEESKILLS(85, "GETDATA_WORKFLOWEMPLOYEESKILLS"),
    VALIDATEFIELD_WORKFLOWEMPLOYEESKILLS(86, "VALIDATEFIELD_WORKFLOWEMPLOYEESKILLS"),
    //Activity Categories
    INSERT_WORKFLOWACTIVITYCATE(100, "INSERT_WORKFLOWACTIVITYCATE"),
    UPDATE_WORKFLOWACTIVITYCATE(101, "UPDATE_WORKFLOWACTIVITYCATE"),
    DELETE_WORKFLOWACTIVITYCATE(102, "DELETE_WORKFLOWACTIVITYCATE"),
    GETNUMROWS_WORKFLOWACTIVITYCATE(103, "GETNUMROWS_WORKFLOWACTIVITYCATE"),
    GETDATA_WORKFLOWACTIVITYCATE(104, "GETDATA_WORKFLOWACTIVITYCATE"),
    VALIDATEFIELD_WORKFLOWACTIVITYCATE(105, "VALIDATEFIELD_WORKFLOWACTIVITYCATE"),
    //Activity Categories
    INSERT_WORKFLOWACTIVITYGROUPS(120, "INSERT_WORKFLOWACTIVITYGROUPS"),
    UPDATE_WORKFLOWACTIVITYGROUPS(121, "UPDATE_WORKFLOWACTIVITYGROUPS"),
    DELETE_WORKFLOWACTIVITYGROUPS(122, "DELETE_WORKFLOWACTIVITYGROUPS"),
    GETNUMROWS_WORKFLOWACTIVITYGROUPS(123, "GETNUMROWS_WORKFLOWACTIVITYGROUPS"),
    GETDATA_WORKFLOWACTIVITYGROUPS(124, "GETDATA_WORKFLOWACTIVITYGROUPS"),
    VALIDATEFIELD_WORKFLOWACTIVITYGROUPS(125, "VALIDATEFIELD_WORKFLOWACTIVITYGROUPS"),
    //Activity priority
    INSERT_WORKFLOWACTIVITYPRIORITY(140, "INSERT_WORKFLOWACTIVITYPRIORITY"),
    UPDATE_WORKFLOWACTIVITYPRIORITY(141, "UPDATE_WORKFLOWACTIVITYPRIORITY"),
    DELETE_WORKFLOWACTIVITYPRIORITY(142, "DELETE_WORKFLOWACTIVITYPRIORITY"),
    GETNUMROWS_WORKFLOWACTIVITYPRIORITY(143, "GETNUMROWS_WORKFLOWACTIVITYPRIORITY"),
    GETDATA_WORKFLOWACTIVITYPRIORITY(144, "GETDATA_WORKFLOWACTIVITYPRIORITY"),
    VALIDATEFIELD_WORKFLOWACTIVITYPRIORITY(145, "VALIDATEFIELD_WORKFLOWACTIVITYPRIORITY"),
    //Activity status
    INSERT_WORKFLOWACTIVITYSTATUS(160, "INSERT_WORKFLOWACTIVITYSTATUS"),
    UPDATE_WORKFLOWACTIVITYSTATUS(161, "UPDATE_WORKFLOWACTIVITYSTATUS"),
    DELETE_WORKFLOWACTIVITYSTATUS(162, "DELETE_WORKFLOWACTIVITYSTATUS"),
    GETNUMROWS_WORKFLOWACTIVITYSTATUS(163, "GETNUMROWS_WORKFLOWACTIVITYSTATUS"),
    GETDATA_WORKFLOWACTIVITYSTATUS(164, "GETDATA_WORKFLOWACTIVITYSTATUS"),
    VALIDATEFIELD_WORKFLOWACTIVITYSTATUS(165, "VALIDATEFIELD_WORKFLOWACTIVITYSTATUS"),
    //Department
    INSERT_WORKFLOWDEPARTMENT(180, "INSERT_WORKFLOWDEPARTMENT"),
    UPDATE_WORKFLOWDEPARTMENT(181, "UPDATE_WORKFLOWDEPARTMENT"),
    DELETE_WORKFLOWDEPARTMENT(182, "DELETE_WORKFLOWDEPARTMENT"),
    GETNUMROWS_WORKFLOWDEPARTMENT(183, "GETNUMROWS_WORKFLOWDEPARTMENT"),
    GETDATA_WORKFLOWDEPARTMENT(184, "GETDATA_WORKFLOWDEPARTMENT"),
    VALIDATEFIELD_WORKFLOWDEPARTMENT(185, "VALIDATEFIELD_WORKFLOWDEPARTMENT"),
    //Activity Types
    INSERT_WORKFLOWACTIVITYTYPES(200, "INSERT_WORKFLOWACTIVITYTYPES"),
    UPDATE_WORKFLOWACTIVITYTYPES(201, "UPDATE_WORKFLOWACTIVITYTYPES"),
    DELETE_WORKFLOWACTIVITYTYPES(202, "DELETE_WORKFLOWACTIVITYTYPES"),
    GETNUMROWS_WORKFLOWACTIVITYTYPES(203, "GETNUMROWS_WORKFLOWACTIVITYTYPES"),
    GETDATA_WORKFLOWACTIVITYTYPES(204, "GETDATA_WORKFLOWACTIVITYTYPES"),
    VALIDATEFIELD_WORKFLOWACTIVITYTYPES(205, "VALIDATEFIELD_WORKFLOWACTIVITYTYPES"),
    //Activity Group Employees
    INSERT_WORKFLOWACTIVITYGROUPEMP(220, "INSERT_WORKFLOWACTIVITYGROUPEMP"),
    UPDATE_WORKFLOWACTIVITYGROUPEMP(221, "UPDATE_WORKFLOWACTIVITYGROUPEMP"),
    DELETE_WORKFLOWACTIVITYGROUPEMP(222, "DELETE_WORKFLOWACTIVITYGROUPEMP"),
    GETNUMROWS_WORKFLOWACTIVITYGROUPEMP(223, "GETNUMROWS_WORKFLOWACTIVITYGROUPEMP"),
    GETDATA_WORKFLOWACTIVITYGROUPEMP(224, "GETDATA_WORKFLOWACTIVITYGROUPEMP"),
    VALIDATEFIELD_WORKFLOWACTIVITYGROUPEMP(225, "VALIDATEFIELD_WORKFLOWACTIVITYGROUPEMP"),
    //Activities
    INSERT_WORKFLOWACTIVITY(240, "INSERT_WORKFLOWACTIVITY"),
    UPDATE_WORKFLOWACTIVITY(241, "UPDATE_WORKFLOWACTIVITY"),
    DELETE_WORKFLOWACTIVITY(242, "DELETE_WORKFLOWACTIVITY"),
    GETNUMROWS_WORKFLOWACTIVITY(243, "GETNUMROWS_WORKFLOWACTIVITY"),
    GETDATA_WORKFLOWACTIVITY(244, "GETDATA_WORKFLOWACTIVITY"),
    VALIDATEFIELD_WORKFLOWACTIVITY(245, "VALIDATEFIELD_WORKFLOWACTIVITY"),
    COPY_WFJOBLINE_ACTIVITY_PERSIST(251, "COPY_WFJOBLINE_ACTIVITY_PERSIST"),
    SEND_ACTIVITY_REMINDER(252, "SEND_ACTIVITY_REMINDER"),
    //Job Lines
    INSERT_WORKFLOWJOBLINES(260, "INSERT_WORKFLOWJOBLINES"),
    UPDATE_WORKFLOWJOBLINES(261, "UPDATE_WORKFLOWJOBLINES"),
    DELETE_WORKFLOWJOBLINES(262, "DELETE_WORKFLOWJOBLINES"),
    GETNUMROWS_WORKFLOWJOBLINES(263, "GETNUMROWS_WORKFLOWJOBLINES"),
    GETDATA_WORKFLOWJOBLINES(264, "GETDATA_WORKFLOWJOBLINES"),
    VALIDATEFIELD_WORKFLOWJOBLINES(265, "VALIDATEFIELD_WORKFLOWJOBLINES"),
    //Job Master
    INSERT_WORKFLOWJOBMASTER(280, "INSERT_WORKFLOWJOBMASTER"),
    UPDATE_WORKFLOWJOBMASTER(281, "UPDATE_WORKFLOWJOBMASTER"),
    DELETE_WORKFLOWJOBMASTER(282, "DELETE_WORKFLOWJOBMASTER"),
    GETNUMROWS_WORKFLOWJOBMASTER(283, "GETNUMROWS_WORKFLOWJOBMASTER"),
    GETDATA_WORKFLOWJOBMASTER(284, "GETDATA_WORKFLOWJOBMASTER"),
    VALIDATEFIELD_WORKFLOWJOBMASTER(285, "VALIDATEFIELD_WORKFLOWJOBMASTER"),
    ALL_DOCUMENTS_ATTATCHED(286, "ALL_DOCUMENTS_ATTATCHED"),
    //Workflow Master
    INSERT_WORKFLOWMASTER(300, "INSERT_WORKFLOWMASTER"),
    UPDATE_WORKFLOWMASTER(301, "UPDATE_WORKFLOWMASTER"),
    DELETE_WORKFLOWMASTER(302, "DELETE_WORKFLOWMASTER"),
    GETNUMROWS_WORKFLOWMASTER(303, "GETNUMROWS_WORKFLOWMASTER"),
    GETDATA_WORKFLOWMASTER(304, "GETDATA_WORKFLOWMASTER"),
    VALIDATEFIELD_WORKFLOWMASTER(305, "VALIDATEFIELD_WORKFLOWMASTER"),
    EVALUATE_WFJOBLINES(306, "EVALUATE_WFJOBLINES"),
    REDO_WFJOBLINES(307, "REDO_WFJOBLINES"),
    ALL_DOCUMENTS_ATTATCHED_WFMASTER(308, "ALL_DOCUMENTS_ATTATCHED_WFMASTER"),
    COPY_WORKFLOW(309, "COPY_WORKFLOW"),
    CREATE_TASK(310, "CREATE_TASK"),
    EVALUATE_WFMASTER_LINES(312, "EVALUATE_WFMASTER_LINES"),
    //Job Lines
    INSERT_WORKFLOWLINES(320, "INSERT_WORKFLOWLINES"),
    UPDATE_WORKFLOWLINES(321, "UPDATE_WORKFLOWLINES"),
    DELETE_WORKFLOWLINES(322, "DELETE_WORKFLOWLINES"),
    GETNUMROWS_WORKFLOWLINES(323, "GETNUMROWS_WORKFLOWLINES"),
    GETDATA_WORKFLOWLINES(324, "GETDATA_WORKFLOWLINES"),
    VALIDATEFIELD_WORKFLOWLINES(325, "VALIDATEFIELD_WORKFLOWLINES"),
    //WorkFlowActivityDS
    INSERT_WORKFLOWACTIVITYDS(340, "INSERT_WORKFLOWACTIVITYDS"),
    UPDATE_WORKFLOWACTIVITYDS(341, "UPDATE_WORKFLOWACTIVITYDS"),
    DELETE_WORKFLOWACTIVITYDS(342, "DELETE_WORKFLOWACTIVITYDS"),
    GETNUMROWS_WORKFLOWACTIVITYDS(343, "GETNUMROWS_WORKFLOWACTIVITYDS"),
    GETDATA_WORKFLOWACTIVITYDS(344, "GETDATA_WORKFLOWACTIVITYDS"),
    VALIDATEFIELD_WORKFLOWACTIVITYDS(345, "VALIDATEFIELD_WORKFLOWACTIVITYDS"),
    //WorkFlowActivityGroupEmpDS
    INSERT_WORKFLOWACTIVITYGROUPEMPDS(360, "INSERT_WORKFLOWACTIVITYGROUPEMPDS"),
    UPDATE_WORKFLOWACTIVITYGROUPEMPDS(361, "UPDATE_WORKFLOWACTIVITYGROUPEMPDS"),
    DELETE_WORKFLOWACTIVITYGROUPEMPDS(362, "DELETE_WORKFLOWACTIVITYGROUPEMPDS"),
    GETNUMROWS_WORKFLOWACTIVITYGROUPEMPDS(363, "GETNUMROWS_WORKFLOWACTIVITYGROUPEMPDS"),
    GETDATA_WORKFLOWACTIVITYGROUPEMPDS(364, "GETDATA_WORKFLOWACTIVITYGROUPEMPDS"),
    VALIDATEFIELD_WORKFLOWACTIVITYGROUPEMPDS(365, "VALIDATEFIELD_WORKFLOWACTIVITYGROUPEMPDS"),
    //MyActivitiesDataManager
    GET_MY_ACTIVITIES_INFO(380, "GET_MY_ACTIVITIES_INFO"),
    //WFActivityAlerts
    INSERT_WFACTIVITYALERTS(400, "INSERT_WFACTIVITYALERTS"),
    UPDATE_WFACTIVITYALERTS(401, "UPDATE_WFACTIVITYALERTS"),
    DELETE_WFACTIVITYALERTS(402, "DELETE_WFACTIVITYALERTS"),
    GETNUMROWS_WFACTIVITYALERTS(403, "GETNUMROWS_WFACTIVITYALERTS"),
    GETDATA_WFACTIVITYALERTS(404, "GETDATA_WFACTIVITYALERTS"),
    VALIDATEFIELD_WFACTIVITYALERTS(405, "VALIDATEFIELD_WFACTIVITYALERTS"),
    //WorkFlowSkillsEnquiry
    INSERT_WORKFLOWSKILLSENQUIRY(420, "INSERT_WORKFLOWSKILLSENQUIRY"),
    UPDATE_WORKFLOWSKILLSENQUIRY(421, "UPDATE_WORKFLOWSKILLSENQUIRY"),
    DELETE_WORKFLOWSKILLSENQUIRY(422, "DELETE_WORKFLOWSKILLSENQUIRY"),
    GETNUMROWS_WORKFLOWSKILLSENQUIRY(423, "GETNUMROWS_WORKFLOWSKILLSENQUIRY"),
    GETDATA_WORKFLOWSKILLSENQUIRY(424, "GETDATA_WORKFLOWSKILLSENQUIRY"),
    VALIDATEFIELD_WORKFLOWSKILLSENQUIRY(425, "VALIDATEFIELD_WORKFLOWSKILLSENQUIRY"),
    CREATE_NEW_ACTIVITY(446, "CREATE_NEW_ACTIVITY"),
    LAUNCH_WORK_FLOW(447, "LAUNCH_WORK_FLOW"),
    REASSIGN_ACTIVITY(448, "REASSIGN_ACTIVITY");
    private final int id;
    private final String label;

    ServerWorkFlowMethods(final int id, final String label) {
        this.id = id;
        this.label = label;
    }

    public int getId() {
        return id;
    }

    @Override
    public String toString() {
        return label;
    }

    public static ServerWorkFlowMethods fromString(final String str) {
        for (ServerWorkFlowMethods e : ServerWorkFlowMethods.values()) {
            if (e.toString().equalsIgnoreCase(str)) {
                return e;
            }
        }
        return null;
    }

    public static ServerWorkFlowMethods fromId(final int id) {
        for (ServerWorkFlowMethods e : ServerWorkFlowMethods.values()) {
            if (e.id == id) {
                return e;
            }
        }
        return null;
    }

    public enumEMCModules getEMCModule() {
        return enumEMCModules.WORKFLOW;
    }
}
