/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package emc.methods.crm;

import emc.enums.modules.enumEMCModules;
import emc.methods.EMCMethodEnum;

/**
 *
 * @author wikus
 */
public enum ServerCRMMethods implements EMCMethodEnum {

    //CRMInterest
    INSERT_CRMINTEREST(20, "INSERT_CRMINTEREST"),
    UPDATE_CRMINTEREST(21, "UPDATE_CRMINTEREST"),
    DELETE_CRMINTEREST(22, "DELETE_CRMINTEREST"),
    GETNUMROWS_CRMINTEREST(23, "GETNUMROWS_CRMINTEREST"),
    GETDATA_CRMINTEREST(24, "GETDATA_CRMINTEREST"),
    VALIDATEFIELD_CRMINTEREST(25, "VALIDATEFIELD_CRMINTEREST"),
    //CRMProspect
    INSERT_CRMPROSPECT(40, "INSERT_CRMPROSPECT"),
    UPDATE_CRMPROSPECT(41, "UPDATE_CRMPROSPECT"),
    DELETE_CRMPROSPECT(42, "DELETE_CRMPROSPECT"),
    GETNUMROWS_CRMPROSPECT(43, "GETNUMROWS_CRMPROSPECT"),
    GETDATA_CRMPROSPECT(44, "GETDATA_CRMPROSPECT"),
    VALIDATEFIELD_CRMPROSPECT(45, "VALIDATEFIELD_CRMPROSPECT"),
    VALIDATE_DOCUMENT(46, "VALIDATE_DOCUMENT"),
    CREATE_PROSPECT_JOB(50, "CREATE_PROSPECT_JOB"),
    //CRMDocuments
    INSERT_CRMDOCUMENTS(60, "INSERT_CRMDOCUMENTS"),
    UPDATE_CRMDOCUMENTS(61, "UPDATE_CRMDOCUMENTS"),
    DELETE_CRMDOCUMENTS(62, "DELETE_CRMDOCUMENTS"),
    GETNUMROWS_CRMDOCUMENTS(63, "GETNUMROWS_CRMDOCUMENTS"),
    GETDATA_CRMDOCUMENTS(64, "GETDATA_CRMDOCUMENTS"),
    VALIDATEFIELD_CRMDOCUMENTS(65, "VALIDATEFIELD_CRMDOCUMENTS"),
    //CRMParameters
    INSERT_CRMPARAMETERS(80, "INSERT_CRMPARAMETERS"),
    UPDATE_CRMPARAMETERS(81, "UPDATE_CRMPARAMETERS"),
    DELETE_CRMPARAMETERS(82, "DELETE_CRMPARAMETERS"),
    GETNUMROWS_CRMPARAMETERS(83, "GETNUMROWS_CRMPARAMETERS"),
    GETDATA_CRMPARAMETERS(84, "GETDATA_CRMPARAMETERS"),
    VALIDATEFIELD_CRMPARAMETERS(85, "VALIDATEFIELD_CRMPARAMETERS"),
    //CRMCorrespondenceLog
    INSERT_CRMCORRESPONDENCELOG(100, "INSERT_CRMCORRESPONDENCELOG"),
    UPDATE_CRMCORRESPONDENCELOG(101, "UPDATE_CRMCORRESPONDENCELOG"),
    DELETE_CRMCORRESPONDENCELOG(102, "DELETE_CRMCORRESPONDENCELOG"),
    GETNUMROWS_CRMCORRESPONDENCELOG(103, "GETNUMROWS_CRMCORRESPONDENCELOG"),
    GETDATA_CRMCORRESPONDENCELOG(104, "GETDATA_CRMCORRESPONDENCELOG"),
    VALIDATEFIELD_CRMCORRESPONDENCELOG(105, "VALIDATEFIELD_CRMCORRESPONDENCELOG"),
    //CRMInterestGroup
    INSERT_CRMINTERESTGROUP(120, "INSERT_CRMINTERESTGROUP"),
    UPDATE_CRMINTERESTGROUP(121, "UPDATE_CRMINTERESTGROUP"),
    DELETE_CRMINTERESTGROUP(122, "DELETE_CRMINTERESTGROUP"),
    GETNUMROWS_CRMINTERESTGROUP(123, "GETNUMROWS_CRMINTERESTGROUP"),
    GETDATA_CRMINTERESTGROUP(124, "GETDATA_CRMINTERESTGROUP"),
    VALIDATEFIELD_CRMINTERESTGROUP(125, "VALIDATEFIELD_CRMINTERESTGROUP"),
    //CRMProspectCloseReason
    INSERT_CRMPROSPECTCLOSEREASON(140, "INSERT_CRMPROSPECTCLOSEREASON"),
    UPDATE_CRMPROSPECTCLOSEREASON(141, "UPDATE_CRMPROSPECTCLOSEREASON"),
    DELETE_CRMPROSPECTCLOSEREASON(142, "DELETE_CRMPROSPECTCLOSEREASON"),
    GETNUMROWS_CRMPROSPECTCLOSEREASON(143, "GETNUMROWS_CRMPROSPECTCLOSEREASON"),
    GETDATA_CRMPROSPECTCLOSEREASON(144, "GETDATA_CRMPROSPECTCLOSEREASON"),
    VALIDATEFIELD_CRMPROSPECTCLOSEREASON(145, "VALIDATEFIELD_CRMPROSPECTCLOSEREASON"),
    VALIDATE_CLOSE_REASON(146, "VALIDATE_CLOSE_REASON"),
    //CRMClassification1
    INSERT_CRMCLASSIFICATION1(160, "INSERT_CRMCLASSIFICATION1"),
    UPDATE_CRMCLASSIFICATION1(161, "UPDATE_CRMCLASSIFICATION1"),
    DELETE_CRMCLASSIFICATION1(162, "DELETE_CRMCLASSIFICATION1"),
    GETNUMROWS_CRMCLASSIFICATION1(163, "GETNUMROWS_CRMCLASSIFICATION1"),
    GETDATA_CRMCLASSIFICATION1(164, "GETDATA_CRMCLASSIFICATION1"),
    VALIDATEFIELD_CRMCLASSIFICATION1(165, "VALIDATEFIELD_CRMCLASSIFICATION1"),
    //CRMClassification2
    INSERT_CRMCLASSIFICATION2(180, "INSERT_CRMCLASSIFICATION2"),
    UPDATE_CRMCLASSIFICATION2(181, "UPDATE_CRMCLASSIFICATION2"),
    DELETE_CRMCLASSIFICATION2(182, "DELETE_CRMCLASSIFICATION2"),
    GETNUMROWS_CRMCLASSIFICATION2(183, "GETNUMROWS_CRMCLASSIFICATION2"),
    GETDATA_CRMCLASSIFICATION2(184, "GETDATA_CRMCLASSIFICATION2"),
    VALIDATEFIELD_CRMCLASSIFICATION2(185, "VALIDATEFIELD_CRMCLASSIFICATION2"),
    //CRMClassification3
    INSERT_CRMCLASSIFICATION3(200, "INSERT_CRMCLASSIFICATION3"),
    UPDATE_CRMCLASSIFICATION3(201, "UPDATE_CRMCLASSIFICATION3"),
    DELETE_CRMCLASSIFICATION3(202, "DELETE_CRMCLASSIFICATION3"),
    GETNUMROWS_CRMCLASSIFICATION3(203, "GETNUMROWS_CRMCLASSIFICATION3"),
    GETDATA_CRMCLASSIFICATION3(204, "GETDATA_CRMCLASSIFICATION3"),
    VALIDATEFIELD_CRMCLASSIFICATION3(205, "VALIDATEFIELD_CRMCLASSIFICATION3");
    //Enum variables
    final int id;
    final String label;

    /** Creates a new instance of  ServerCRMMethods*/
    ServerCRMMethods(final int id, final String label) {
        this.id = id;
        this.label = label;
    }

    public int getId() {
        return id;
    }

    @Override
    public String toString() {
        return label;
    }

    public static ServerCRMMethods fromString(final String str) {
        for (ServerCRMMethods e : ServerCRMMethods.values()) {
            if (e.toString().equalsIgnoreCase(str)) {
                return e;
            }
        }
        return null;
    }

    public static ServerCRMMethods fromId(final int id) {
        for (ServerCRMMethods e : ServerCRMMethods.values()) {
            if (e.id == id) {
                return e;
            }
        }
        return null;
    }

    public enumEMCModules getEMCModule() {
        return enumEMCModules.CRM;
    }
}
