/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package emc.methods.hr;

import emc.enums.modules.enumEMCModules;
import emc.methods.EMCMethodEnum;

/**
 *
 * @author wikus
 */
public enum ServerHRMethods implements EMCMethodEnum {

    //HRNationality
    INSERT_HRNATIONALITY(0, "INSERT_HRNATIONALITY"),
    UPDATE_HRNATIONALITY(1, "UPDATE_HRNATIONALITY"),
    DELETE_HRNATIONALITY(2, "DELETE_HRNATIONALITY"),
    GETNUMROWS_HRNATIONALITY(3, "GETNUMROWS_HRNATIONALITY"),
    GETDATA_HRNATIONALITY(4, "GETDATA_HRNATIONALITY"),
    VALIDATEFIELD_HRNATIONALITY(5, "VALIDATEFIELD_HRNATIONALITY"),
    //HREmploymentType
    INSERT_HREMPLOYMENTTYPE(20, "INSERT_HREMPLOYMENTTYPE"),
    UPDATE_HREMPLOYMENTTYPE(21, "UPDATE_HREMPLOYMENTTYPE"),
    DELETE_HREMPLOYMENTTYPE(22, "DELETE_HREMPLOYMENTTYPE"),
    GETNUMROWS_HREMPLOYMENTTYPE(23, "GETNUMROWS_HREMPLOYMENTTYPE"),
    GETDATA_HREMPLOYMENTTYPE(24, "GETDATA_HREMPLOYMENTTYPE"),
    VALIDATEFIELD_HREMPLOYMENTTYPE(25, "VALIDATEFIELD_HREMPLOYMENTTYPE"),
    //HRRace
    INSERT_HRRACE(40, "INSERT_HRRACE"),
    UPDATE_HRRACE(41, "UPDATE_HRRACE"),
    DELETE_HRRACE(42, "DELETE_HRRACE"),
    GETNUMROWS_HRRACE(43, "GETNUMROWS_HRRACE"),
    GETDATA_HRRACE(44, "GETDATA_HRRACE"),
    VALIDATEFIELD_HRRACE(45, "VALIDATEFIELD_HRRACE"),
    //HRGrade
    INSERT_HRGRADE(60, "INSERT_HRGRADE"),
    UPDATE_HRGRADE(61, "UPDATE_HRGRADE"),
    DELETE_HRGRADE(62, "DELETE_HRGRADE"),
    GETNUMROWS_HRGRADE(63, "GETNUMROWS_HRGRADE"),
    GETDATA_HRGRADE(64, "GETDATA_HRGRADE"),
    VALIDATEFIELD_HRGRADE(65, "VALIDATEFIELD_HRGRADE"),
    //HRInstitution
    INSERT_HRINSTITUTION(80, "INSERT_HRINSTITUTION"),
    UPDATE_HRINSTITUTION(81, "UPDATE_HRINSTITUTION"),
    DELETE_HRINSTITUTION(82, "DELETE_HRINSTITUTION"),
    GETNUMROWS_HRINSTITUTION(83, "GETNUMROWS_HRINSTITUTION"),
    GETDATA_HRINSTITUTION(84, "GETDATA_HRINSTITUTION"),
    VALIDATEFIELD_HRINSTITUTION(85, "VALIDATEFIELD_HRINSTITUTION"),
    //HRLeaveType
    INSERT_HRLEAVETYPE(100, "INSERT_HRLEAVETYPE"),
    UPDATE_HRLEAVETYPE(101, "UPDATE_HRLEAVETYPE"),
    DELETE_HRLEAVETYPE(102, "DELETE_HRLEAVETYPE"),
    GETNUMROWS_HRLEAVETYPE(103, "GETNUMROWS_HRLEAVETYPE"),
    GETDATA_HRLEAVETYPE(104, "GETDATA_HRLEAVETYPE"),
    VALIDATEFIELD_HRLEAVETYPE(105, "VALIDATEFIELD_HRLEAVETYPE"),
    //HRTerminationType
    INSERT_HRTERMINATIONTYPE(120, "INSERT_HRTERMINATIONTYPE"),
    UPDATE_HRTERMINATIONTYPE(121, "UPDATE_HRTERMINATIONTYPE"),
    DELETE_HRTERMINATIONTYPE(122, "DELETE_HRTERMINATIONTYPE"),
    GETNUMROWS_HRTERMINATIONTYPE(123, "GETNUMROWS_HRTERMINATIONTYPE"),
    GETDATA_HRTERMINATIONTYPE(124, "GETDATA_HRTERMINATIONTYPE"),
    VALIDATEFIELD_HRTERMINATIONTYPE(125, "VALIDATEFIELD_HRTERMINATIONTYPE"),
    //HRSection
    INSERT_HRSECTION(140, "INSERT_HRSECTION"),
    UPDATE_HRSECTION(141, "UPDATE_HRSECTION"),
    DELETE_HRSECTION(142, "DELETE_HRSECTION"),
    GETNUMROWS_HRSECTION(143, "GETNUMROWS_HRSECTION"),
    GETDATA_HRSECTION(144, "GETDATA_HRSECTION"),
    VALIDATEFIELD_HRSECTION(145, "VALIDATEFIELD_HRSECTION"),
    //HRBranch
    INSERT_HRBRANCH(160, "INSERT_HRBRANCH"),
    UPDATE_HRBRANCH(161, "UPDATE_HRBRANCH"),
    DELETE_HRBRANCH(162, "DELETE_HRBRANCH"),
    GETNUMROWS_HRBRANCH(163, "GETNUMROWS_HRBRANCH"),
    GETDATA_HRBRANCH(164, "GETDATA_HRBRANCH"),
    VALIDATEFIELD_HRBRANCH(165, "VALIDATEFIELD_HRBRANCH"),
    //HRTerminationLog
    INSERT_HRTERMINATIONLOG(180, "INSERT_HRTERMINATIONLOG"),
    UPDATE_HRTERMINATIONLOG(181, "UPDATE_HRTERMINATIONLOG"),
    DELETE_HRTERMINATIONLOG(182, "DELETE_HRTERMINATIONLOG"),
    GETNUMROWS_HRTERMINATIONLOG(183, "GETNUMROWS_HRTERMINATIONLOG"),
    GETDATA_HRTERMINATIONLOG(184, "GETDATA_HRTERMINATIONLOG"),
    VALIDATEFIELD_HRTERMINATIONLOG(185, "VALIDATEFIELD_HRTERMINATIONLOG"),
    //HRTerminationLogDS
    INSERT_HRTERMINATIONLOGDS(200, "INSERT_HRTERMINATIONLOGDS"),
    UPDATE_HRTERMINATIONLOGDS(201, "UPDATE_HRTERMINATIONLOGDS"),
    DELETE_HRTERMINATIONLOGDS(202, "DELETE_HRTERMINATIONLOGDS"),
    GETNUMROWS_HRTERMINATIONLOGDS(203, "GETNUMROWS_HRTERMINATIONLOGDS"),
    GETDATA_HRTERMINATIONLOGDS(204, "GETDATA_HRTERMINATIONLOGDS"),
    VALIDATEFIELD_HRTERMINATIONLOGDS(205, "VALIDATEFIELD_HRTERMINATIONLOGDS"),
    //HRLeaveLog
    INSERT_HRLEAVELOG(220, "INSERT_HRLEAVELOG"),
    UPDATE_HRLEAVELOG(221, "UPDATE_HRLEAVELOG"),
    DELETE_HRLEAVELOG(222, "DELETE_HRLEAVELOG"),
    GETNUMROWS_HRLEAVELOG(223, "GETNUMROWS_HRLEAVELOG"),
    GETDATA_HRLEAVELOG(224, "GETDATA_HRLEAVELOG"),
    VALIDATEFIELD_HRLEAVELOG(225, "VALIDATEFIELD_HRLEAVELOG"),
    //HREmployeeDependants
    INSERT_HREMPLOYEEDEPENDANTS(300, "INSERT_HREMPLOYEEDEPENDANTS"),
    UPDATE_HREMPLOYEEDEPENDANTS(301, "UPDATE_HREMPLOYEEDEPENDANTS"),
    DELETE_HREMPLOYEEDEPENDANTS(302, "DELETE_HREMPLOYEEDEPENDANTS"),
    GETNUMROWS_HREMPLOYEEDEPENDANTS(303, "GETNUMROWS_HREMPLOYEEDEPENDANTS"),
    GETDATA_HREMPLOYEEDEPENDANTS(304, "GETDATA_HREMPLOYEEDEPENDANTS"),
    VALIDATEFIELD_HREMPLOYEEDEPENDANTS(305, "VALIDATEFIELD_HREMPLOYEEDEPENDANTS"),
    //HREmployeeEducation
    INSERT_HREMPLOYEEEDUCATION(340, "INSERT_HREMPLOYEEEDUCATION"),
    UPDATE_HREMPLOYEEEDUCATION(341, "UPDATE_HREMPLOYEEEDUCATION"),
    DELETE_HREMPLOYEEEDUCATION(342, "DELETE_HREMPLOYEEEDUCATION"),
    GETNUMROWS_HREMPLOYEEEDUCATION(343, "GETNUMROWS_HREMPLOYEEEDUCATION"),
    GETDATA_HREMPLOYEEEDUCATION(344, "GETDATA_HREMPLOYEEEDUCATION"),
    VALIDATEFIELD_HREMPLOYEEEDUCATION(345, "VALIDATEFIELD_HREMPLOYEEEDUCATION"),
    //HREmployeeTraining
    INSERT_HREMPLOYEETRAINING(380, "INSERT_HREMPLOYEETRAINING"),
    UPDATE_HREMPLOYEETRAINING(381, "UPDATE_HREMPLOYEETRAINING"),
    DELETE_HREMPLOYEETRAINING(382, "DELETE_HREMPLOYEETRAINING"),
    GETNUMROWS_HREMPLOYEETRAINING(383, "GETNUMROWS_HREMPLOYEETRAINING"),
    GETDATA_HREMPLOYEETRAINING(384, "GETDATA_HREMPLOYEETRAINING"),
    VALIDATEFIELD_HREMPLOYEETRAINING(385, "VALIDATEFIELD_HREMPLOYEETRAINING"),
    //HRDiciplaneryActions
    INSERT_HRDICIPLANERYACTIONS(420, "INSERT_HRDICIPLANERYACTIONS"),
    UPDATE_HRDICIPLANERYACTIONS(421, "UPDATE_HRDICIPLANERYACTIONS"),
    DELETE_HRDICIPLANERYACTIONS(422, "DELETE_HRDICIPLANERYACTIONS"),
    GETNUMROWS_HRDICIPLANERYACTIONS(423, "GETNUMROWS_HRDICIPLANERYACTIONS"),
    GETDATA_HRDICIPLANERYACTIONS(424, "GETDATA_HRDICIPLANERYACTIONS"),
    VALIDATEFIELD_HRDICIPLANERYACTIONS(425, "VALIDATEFIELD_HRDICIPLANERYACTIONS"),
    //HRGrievences
    INSERT_HRGRIEVENCES(460, "INSERT_HRGRIEVENCES"),
    UPDATE_HRGRIEVENCES(461, "UPDATE_HRGRIEVENCES"),
    DELETE_HRGRIEVENCES(462, "DELETE_HRGRIEVENCES"),
    GETNUMROWS_HRGRIEVENCES(463, "GETNUMROWS_HRGRIEVENCES"),
    GETDATA_HRGRIEVENCES(464, "GETDATA_HRGRIEVENCES"),
    VALIDATEFIELD_HRGRIEVENCES(465, "VALIDATEFIELD_HRGRIEVENCES"),
    //HRPreviousEmploymentHistory
    INSERT_HRPREVIOUSEMPLOYMENTHISTORY(540, "INSERT_HRPREVIOUSEMPLOYMENTHISTORY"),
    UPDATE_HRPREVIOUSEMPLOYMENTHISTORY(541, "UPDATE_HRPREVIOUSEMPLOYMENTHISTORY"),
    DELETE_HRPREVIOUSEMPLOYMENTHISTORY(542, "DELETE_HRPREVIOUSEMPLOYMENTHISTORY"),
    GETNUMROWS_HRPREVIOUSEMPLOYMENTHISTORY(543, "GETNUMROWS_HRPREVIOUSEMPLOYMENTHISTORY"),
    GETDATA_HRPREVIOUSEMPLOYMENTHISTORY(544, "GETDATA_HRPREVIOUSEMPLOYMENTHISTORY"),
    VALIDATEFIELD_HRPREVIOUSEMPLOYMENTHISTORY(545, "VALIDATEFIELD_HRPREVIOUSEMPLOYMENTHISTORY"),
    //HRInternalEmploymentHistory
    INSERT_HRINTERNALEMPLOYMENTHISTORY(580, "INSERT_HRINTERNALEMPLOYMENTHISTORY"),
    UPDATE_HRINTERNALEMPLOYMENTHISTORY(581, "UPDATE_HRINTERNALEMPLOYMENTHISTORY"),
    DELETE_HRINTERNALEMPLOYMENTHISTORY(582, "DELETE_HRINTERNALEMPLOYMENTHISTORY"),
    GETNUMROWS_HRINTERNALEMPLOYMENTHISTORY(583, "GETNUMROWS_HRINTERNALEMPLOYMENTHISTORY"),
    GETDATA_HRINTERNALEMPLOYMENTHISTORY(584, "GETDATA_HRINTERNALEMPLOYMENTHISTORY"),
    VALIDATEFIELD_HRINTERNALEMPLOYMENTHISTORY(585, "VALIDATEFIELD_HRINTERNALEMPLOYMENTHISTORY"),
    //HRActionResults
    INSERT_HRACTIONRESULTS(600, "INSERT_HRACTIONRESULTS"),
    UPDATE_HRACTIONRESULTS(601, "UPDATE_HRACTIONRESULTS"),
    DELETE_HRACTIONRESULTS(602, "DELETE_HRACTIONRESULTS"),
    GETNUMROWS_HRACTIONRESULTS(603, "GETNUMROWS_HRACTIONRESULTS"),
    GETDATA_HRACTIONRESULTS(604, "GETDATA_HRACTIONRESULTS"),
    VALIDATEFIELD_HRACTIONRESULTS(605, "VALIDATEFIELD_HRACTIONRESULTS"),
    //HRMedicalAid
    INSERT_HRMEDICALAID(620, "INSERT_HRMEDICALAID"),
    UPDATE_HRMEDICALAID(621, "UPDATE_HRMEDICALAID"),
    DELETE_HRMEDICALAID(622, "DELETE_HRMEDICALAID"),
    GETNUMROWS_HRMEDICALAID(623, "GETNUMROWS_HRMEDICALAID"),
    GETDATA_HRMEDICALAID(624, "GETDATA_HRMEDICALAID"),
    VALIDATEFIELD_HRMEDICALAID(625, "VALIDATEFIELD_HRMEDICALAID"),
    //HRUnions
    INSERT_HRUNIONS(640, "INSERT_HRUNIONS"),
    UPDATE_HRUNIONS(641, "UPDATE_HRUNIONS"),
    DELETE_HRUNIONS(642, "DELETE_HRUNIONS"),
    GETNUMROWS_HRUNIONS(643, "GETNUMROWS_HRUNIONS"),
    GETDATA_HRUNIONS(644, "GETDATA_HRUNIONS"),
    VALIDATEFIELD_HRUNIONS(645, "VALIDATEFIELD_HRUNIONS"),
    //HRCourses
    INSERT_HRCOURSES(660, "INSERT_HRCOURSES"),
    UPDATE_HRCOURSES(661, "UPDATE_HRCOURSES"),
    DELETE_HRCOURSES(662, "DELETE_HRCOURSES"),
    GETNUMROWS_HRCOURSES(663, "GETNUMROWS_HRCOURSES"),
    GETDATA_HRCOURSES(664, "GETDATA_HRCOURSES"),
    VALIDATEFIELD_HRCOURSES(665, "VALIDATEFIELD_HRCOURSES"),
    //HRQualification
    INSERT_HRQUALIFICATION(680, "INSERT_HRQUALIFICATION"),
    UPDATE_HRQUALIFICATION(681, "UPDATE_HRQUALIFICATION"),
    DELETE_HRQUALIFICATION(682, "DELETE_HRQUALIFICATION"),
    GETNUMROWS_HRQUALIFICATION(683, "GETNUMROWS_HRQUALIFICATION"),
    GETDATA_HRQUALIFICATION(684, "GETDATA_HRQUALIFICATION"),
    VALIDATEFIELD_HRQUALIFICATION(685, "VALIDATEFIELD_HRQUALIFICATION"),
    //HRDisciplinaryLevel
    INSERT_HRDISCIPLINARYLEVEL(800, "INSERT_HRDISCIPLINARYLEVEL"),
    UPDATE_HRDISCIPLINARYLEVEL(801, "UPDATE_HRDISCIPLINARYLEVEL"),
    DELETE_HRDISCIPLINARYLEVEL(802, "DELETE_HRDISCIPLINARYLEVEL"),
    GETNUMROWS_HRDISCIPLINARYLEVEL(803, "GETNUMROWS_HRDISCIPLINARYLEVEL"),
    GETDATA_HRDISCIPLINARYLEVEL(804, "GETDATA_HRDISCIPLINARYLEVEL"),
    VALIDATEFIELD_HRDISCIPLINARYLEVEL(805, "VALIDATEFIELD_HRDISCIPLINARYLEVEL"),
    //HRMedicalLog
    INSERT_HRMEDICALLOG(820, "INSERT_HRMEDICALLOG"),
    UPDATE_HRMEDICALLOG(821, "UPDATE_HRMEDICALLOG"),
    DELETE_HRMEDICALLOG(822, "DELETE_HRMEDICALLOG"),
    GETNUMROWS_HRMEDICALLOG(823, "GETNUMROWS_HRMEDICALLOG"),
    GETDATA_HRMEDICALLOG(824, "GETDATA_HRMEDICALLOG"),
    VALIDATEFIELD_HRMEDICALLOG(825, "VALIDATEFIELD_HRMEDICALLOG"),
    //HRDisabilityTypes
    INSERT_HRDISABILITYTYPES(840, "INSERT_HRDISABILITYTYPES"),
    UPDATE_HRDISABILITYTYPES(841, "UPDATE_HRDISABILITYTYPES"),
    DELETE_HRDISABILITYTYPES(842, "DELETE_HRDISABILITYTYPES"),
    GETNUMROWS_HRDISABILITYTYPES(843, "GETNUMROWS_HRDISABILITYTYPES"),
    GETDATA_HRDISABILITYTYPES(844, "GETDATA_HRDISABILITYTYPES"),
    VALIDATEFIELD_HRDISABILITYTYPES(845, "VALIDATEFIELD_HRDISABILITYTYPES"),
    //HREducationPriority
    INSERT_HREDUCATIONPRIORITY(860, "INSERT_HREDUCATIONPRIORITY"),
    UPDATE_HREDUCATIONPRIORITY(861, "UPDATE_HREDUCATIONPRIORITY"),
    DELETE_HREDUCATIONPRIORITY(862, "DELETE_HREDUCATIONPRIORITY"),
    GETNUMROWS_HREDUCATIONPRIORITY(863, "GETNUMROWS_HREDUCATIONPRIORITY"),
    GETDATA_HREDUCATIONPRIORITY(864, "GETDATA_HREDUCATIONPRIORITY"),
    VALIDATEFIELD_HREDUCATIONPRIORITY(865, "VALIDATEFIELD_HREDUCATIONPRIORITY"),
    //HRJobLevel
    INSERT_HRJOBLEVEL(880, "INSERT_HRJOBLEVEL"),
    UPDATE_HRJOBLEVEL(881, "UPDATE_HRJOBLEVEL"),
    DELETE_HRJOBLEVEL(882, "DELETE_HRJOBLEVEL"),
    GETNUMROWS_HRJOBLEVEL(883, "GETNUMROWS_HRJOBLEVEL"),
    GETDATA_HRJOBLEVEL(884, "GETDATA_HRJOBLEVEL"),
    VALIDATEFIELD_HRJOBLEVEL(885, "VALIDATEFIELD_HRJOBLEVEL"),
    //HRJobCatagory
    INSERT_HRJOBCATAGORY(900, "INSERT_HRJOBCATAGORY"),
    UPDATE_HRJOBCATAGORY(901, "UPDATE_HRJOBCATAGORY"),
    DELETE_HRJOBCATAGORY(902, "DELETE_HRJOBCATAGORY"),
    GETNUMROWS_HRJOBCATAGORY(903, "GETNUMROWS_HRJOBCATAGORY"),
    GETDATA_HRJOBCATAGORY(904, "GETDATA_HRJOBCATAGORY"),
    VALIDATEFIELD_HRJOBCATAGORY(905, "VALIDATEFIELD_HRJOBCATAGORY"),
    //HROFOCodes
    INSERT_HROFOCODES(920, "INSERT_HROFOCODES"),
    UPDATE_HROFOCODES(921, "UPDATE_HROFOCODES"),
    DELETE_HROFOCODES(922, "DELETE_HROFOCODES"),
    GETNUMROWS_HROFOCODES(923, "GETNUMROWS_HROFOCODES"),
    GETDATA_HROFOCODES(924, "GETDATA_HROFOCODES"),
    VALIDATEFIELD_HROFOCODES(925, "VALIDATEFIELD_HROFOCODES"),
    //HRAbsenteeismType
    INSERT_HRABSENTEEISMTYPE(940, "INSERT_HRABSENTEEISMTYPE"),
    UPDATE_HRABSENTEEISMTYPE(941, "UPDATE_HRABSENTEEISMTYPE"),
    DELETE_HRABSENTEEISMTYPE(942, "DELETE_HRABSENTEEISMTYPE"),
    GETNUMROWS_HRABSENTEEISMTYPE(943, "GETNUMROWS_HRABSENTEEISMTYPE"),
    GETDATA_HRABSENTEEISMTYPE(944, "GETDATA_HRABSENTEEISMTYPE"),
    VALIDATEFIELD_HRABSENTEEISMTYPE(945, "VALIDATEFIELD_HRABSENTEEISMTYPE"),
    //HRAbsenteeismLog
    INSERT_HRABSENTEEISMLOG(960, "INSERT_HRABSENTEEISMLOG"),
    UPDATE_HRABSENTEEISMLOG(961, "UPDATE_HRABSENTEEISMLOG"),
    DELETE_HRABSENTEEISMLOG(962, "DELETE_HRABSENTEEISMLOG"),
    GETNUMROWS_HRABSENTEEISMLOG(963, "GETNUMROWS_HRABSENTEEISMLOG"),
    GETDATA_HRABSENTEEISMLOG(964, "GETDATA_HRABSENTEEISMLOG"),
    VALIDATEFIELD_HRABSENTEEISMLOG(965, "VALIDATEFIELD_HRABSENTEEISMLOG"),
    //HRAbsenteeismLogDS
    INSERT_HRABSENTEEISMLOGDS(980, "INSERT_HRABSENTEEISMLOGDS"),
    UPDATE_HRABSENTEEISMLOGDS(981, "UPDATE_HRABSENTEEISMLOGDS"),
    DELETE_HRABSENTEEISMLOGDS(982, "DELETE_HRABSENTEEISMLOGDS"),
    GETNUMROWS_HRABSENTEEISMLOGDS(983, "GETNUMROWS_HRABSENTEEISMLOGDS"),
    GETDATA_HRABSENTEEISMLOGDS(984, "GETDATA_HRABSENTEEISMLOGDS"),
    VALIDATEFIELD_HRABSENTEEISMLOGDS(985, "VALIDATEFIELD_HRABSENTEEISMLOGDS"),
    //PRINT DISCIPLINARY ACTION
    PRINT_DISCIPLINARY_ACTION(1000, "PRINT_DISCIPLINARY_ACTION"),
    PRINT_EMPLOYMENT_SUMMARY(1001, "PRINT_EMPLOYMENT_SUMMARY"),
    //HRCitizenStatus
    INSERT_HRCITIZENSTATUS(1020, "INSERT_HRCITIZENSTATUS"),
    UPDATE_HRCITIZENSTATUS(1021, "UPDATE_HRCITIZENSTATUS"),
    DELETE_HRCITIZENSTATUS(1022, "DELETE_HRCITIZENSTATUS"),
    GETNUMROWS_HRCITIZENSTATUS(1023, "GETNUMROWS_HRCITIZENSTATUS"),
    GETDATA_HRCITIZENSTATUS(1024, "GETDATA_HRCITIZENSTATUS"),
    VALIDATEFIELD_HRCITIZENSTATUS(1025, "VALIDATEFIELD_HRCITIZENSTATUS"),
    //HREducationLevel
    INSERT_HREDUCATIONLEVEL(1040, "INSERT_HREDUCATIONLEVEL"),
    UPDATE_HREDUCATIONLEVEL(1041, "UPDATE_HREDUCATIONLEVEL"),
    DELETE_HREDUCATIONLEVEL(1042, "DELETE_HREDUCATIONLEVEL"),
    GETNUMROWS_HREDUCATIONLEVEL(1043, "GETNUMROWS_HREDUCATIONLEVEL"),
    GETDATA_HREDUCATIONLEVEL(1044, "GETDATA_HREDUCATIONLEVEL"),
    VALIDATEFIELD_HREDUCATIONLEVEL(1045, "VALIDATEFIELD_HREDUCATIONLEVEL"),
    //HREquityCode
    INSERT_HREQUITYCODE(1060, "INSERT_HREQUITYCODE"),
    UPDATE_HREQUITYCODE(1061, "UPDATE_HREQUITYCODE"),
    DELETE_HREQUITYCODE(1062, "DELETE_HREQUITYCODE"),
    GETNUMROWS_HREQUITYCODE(1063, "GETNUMROWS_HREQUITYCODE"),
    GETDATA_HREQUITYCODE(1064, "GETDATA_HREQUITYCODE"),
    VALIDATEFIELD_HREQUITYCODE(1065, "VALIDATEFIELD_HREQUITYCODE"),
    //HRExperienceLevel
    INSERT_HREXPERIENCELEVEL(1080, "INSERT_HREXPERIENCELEVEL"),
    UPDATE_HREXPERIENCELEVEL(1081, "UPDATE_HREXPERIENCELEVEL"),
    DELETE_HREXPERIENCELEVEL(1082, "DELETE_HREXPERIENCELEVEL"),
    GETNUMROWS_HREXPERIENCELEVEL(1083, "GETNUMROWS_HREXPERIENCELEVEL"),
    GETDATA_HREXPERIENCELEVEL(1084, "GETDATA_HREXPERIENCELEVEL"),
    VALIDATEFIELD_HREXPERIENCELEVEL(1085, "VALIDATEFIELD_HREXPERIENCELEVEL"),
    //HRJobStatus
    INSERT_HRJOBSTATUS(1100, "INSERT_HRJOBSTATUS"),
    UPDATE_HRJOBSTATUS(1101, "UPDATE_HRJOBSTATUS"),
    DELETE_HRJOBSTATUS(1102, "DELETE_HRJOBSTATUS"),
    GETNUMROWS_HRJOBSTATUS(1103, "GETNUMROWS_HRJOBSTATUS"),
    GETDATA_HRJOBSTATUS(1104, "GETDATA_HRJOBSTATUS"),
    VALIDATEFIELD_HRJOBSTATUS(1105, "VALIDATEFIELD_HRJOBSTATUS"),
    //HRSocioEcoStatus
    INSERT_HRSOCIOECOSTATUS(1120, "INSERT_HRSOCIOECOSTATUS"),
    UPDATE_HRSOCIOECOSTATUS(1121, "UPDATE_HRSOCIOECOSTATUS"),
    DELETE_HRSOCIOECOSTATUS(1122, "DELETE_HRSOCIOECOSTATUS"),
    GETNUMROWS_HRSOCIOECOSTATUS(1123, "GETNUMROWS_HRSOCIOECOSTATUS"),
    GETDATA_HRSOCIOECOSTATUS(1124, "GETDATA_HRSOCIOECOSTATUS"),
    VALIDATEFIELD_HRSOCIOECOSTATUS(1125, "VALIDATEFIELD_HRSOCIOECOSTATUS"),
    //HRAlternativeIdType
    INSERT_HRALTERNATIVEIDTYPE(1140, "INSERT_HRALTERNATIVEIDTYPE"),
    UPDATE_HRALTERNATIVEIDTYPE(1141, "UPDATE_HRALTERNATIVEIDTYPE"),
    DELETE_HRALTERNATIVEIDTYPE(1142, "DELETE_HRALTERNATIVEIDTYPE"),
    GETNUMROWS_HRALTERNATIVEIDTYPE(1143, "GETNUMROWS_HRALTERNATIVEIDTYPE"),
    GETDATA_HRALTERNATIVEIDTYPE(1144, "GETDATA_HRALTERNATIVEIDTYPE"),
    VALIDATEFIELD_HRALTERNATIVEIDTYPE(1145, "VALIDATEFIELD_HRALTERNATIVEIDTYPE"),
    //HRLevelOfExperience
    INSERT_HRLEVELOFEXPERIENCE(1160, "INSERT_HRLEVELOFEXPERIENCE"),
    UPDATE_HRLEVELOFEXPERIENCE(1161, "UPDATE_HRLEVELOFEXPERIENCE"),
    DELETE_HRLEVELOFEXPERIENCE(1162, "DELETE_HRLEVELOFEXPERIENCE"),
    GETNUMROWS_HRLEVELOFEXPERIENCE(1163, "GETNUMROWS_HRLEVELOFEXPERIENCE"),
    GETDATA_HRLEVELOFEXPERIENCE(1164, "GETDATA_HRLEVELOFEXPERIENCE"),
    VALIDATEFIELD_HRLEVELOFEXPERIENCE(1165, "VALIDATEFIELD_HRLEVELOFEXPERIENCE"),
    //HRRemunerantionType
    INSERT_HRREMUNERANTIONTYPE(1180, "INSERT_HRREMUNERANTIONTYPE"),
    UPDATE_HRREMUNERANTIONTYPE(1181, "UPDATE_HRREMUNERANTIONTYPE"),
    DELETE_HRREMUNERANTIONTYPE(1182, "DELETE_HRREMUNERANTIONTYPE"),
    GETNUMROWS_HRREMUNERANTIONTYPE(1183, "GETNUMROWS_HRREMUNERANTIONTYPE"),
    GETDATA_HRREMUNERANTIONTYPE(1184, "GETDATA_HRREMUNERANTIONTYPE"),
    VALIDATEFIELD_HRREMUNERANTIONTYPE(1185, "VALIDATEFIELD_HRREMUNERANTIONTYPE"),
    //HRScarceCritSkills
    INSERT_HRSCARCECRITSKILLS(1200, "INSERT_HRSCARCECRITSKILLS"),
    UPDATE_HRSCARCECRITSKILLS(1201, "UPDATE_HRSCARCECRITSKILLS"),
    DELETE_HRSCARCECRITSKILLS(1202, "DELETE_HRSCARCECRITSKILLS"),
    GETNUMROWS_HRSCARCECRITSKILLS(1203, "GETNUMROWS_HRSCARCECRITSKILLS"),
    GETDATA_HRSCARCECRITSKILLS(1204, "GETDATA_HRSCARCECRITSKILLS"),
    VALIDATEFIELD_HRSCARCECRITSKILLS(1205, "VALIDATEFIELD_HRSCARCECRITSKILLS"),
    //HRTrainingReason
    INSERT_HRTRAININGREASON(1220, "INSERT_HRTRAININGREASON"),
    UPDATE_HRTRAININGREASON(1221, "UPDATE_HRTRAININGREASON"),
    DELETE_HRTRAININGREASON(1222, "DELETE_HRTRAININGREASON"),
    GETNUMROWS_HRTRAININGREASON(1223, "GETNUMROWS_HRTRAININGREASON"),
    GETDATA_HRTRAININGREASON(1224, "GETDATA_HRTRAININGREASON"),
    VALIDATEFIELD_HRTRAININGREASON(1225, "VALIDATEFIELD_HRTRAININGREASON"),
    //HRTrainingLevel
    INSERT_HRTRAININGLEVEL(1240, "INSERT_HRTRAININGLEVEL"),
    UPDATE_HRTRAININGLEVEL(1241, "UPDATE_HRTRAININGLEVEL"),
    DELETE_HRTRAININGLEVEL(1242, "DELETE_HRTRAININGLEVEL"),
    GETNUMROWS_HRTRAININGLEVEL(1243, "GETNUMROWS_HRTRAININGLEVEL"),
    GETDATA_HRTRAININGLEVEL(1244, "GETDATA_HRTRAININGLEVEL"),
    VALIDATEFIELD_HRTRAININGLEVEL(1245, "VALIDATEFIELD_HRTRAININGLEVEL"),
    //HRTrainingType
    INSERT_HRTRAININGTYPE(1260, "INSERT_HRTRAININGTYPE"),
    UPDATE_HRTRAININGTYPE(1261, "UPDATE_HRTRAININGTYPE"),
    DELETE_HRTRAININGTYPE(1262, "DELETE_HRTRAININGTYPE"),
    GETNUMROWS_HRTRAININGTYPE(1263, "GETNUMROWS_HRTRAININGTYPE"),
    GETDATA_HRTRAININGTYPE(1264, "GETDATA_HRTRAININGTYPE"),
    VALIDATEFIELD_HRTRAININGTYPE(1265, "VALIDATEFIELD_HRTRAININGTYPE"),
    //HRQualType
    INSERT_HRQUALTYPE(1280, "INSERT_HRQUALTYPE"),
    UPDATE_HRQUALTYPE(1281, "UPDATE_HRQUALTYPE"),
    DELETE_HRQUALTYPE(1282, "DELETE_HRQUALTYPE"),
    GETNUMROWS_HRQUALTYPE(1283, "GETNUMROWS_HRQUALTYPE"),
    GETDATA_HRQUALTYPE(1284, "GETDATA_HRQUALTYPE"),
    VALIDATEFIELD_HRQUALTYPE(1285, "VALIDATEFIELD_HRQUALTYPE"),
    //HRPivotStudyField
    INSERT_HRPIVOTALSTUDYFIELD(1300, "INSERT_HRPIVOTALSTUDYFIELD"),
    UPDATE_HRPIVOTALSTUDYFIELD(1301, "UPDATE_HRPIVOTALSTUDYFIELD"),
    DELETE_HRPIVOTALSTUDYFIELD(1302, "DELETE_HRPIVOTALSTUDYFIELD"),
    GETNUMROWS_HRPIVOTALSTUDYFIELD(1303, "GETNUMROWS_HRPIVOTALSTUDYFIELD"),
    GETDATA_HRPIVOTALSTUDYFIELD(1304, "GETDATA_HRPIVOTALSTUDYFIELD"),
    VALIDATEFIELD_HRPIVOTALSTUDYFIELD(1305, "VALIDATEFIELD_HRPIVOTALSTUDYFIELD"),
    //HRPivotalProgram
    INSERT_HRPIVOTALPROGRAM(1360, "INSERT_HRPIVOTALPROGRAM"),
    UPDATE_HRPIVOTALPROGRAM(1361, "UPDATE_HRPIVOTALPROGRAM"),
    DELETE_HRPIVOTALPROGRAM(1362, "DELETE_HRPIVOTALPROGRAM"),
    GETNUMROWS_HRPIVOTALPROGRAM(1363, "GETNUMROWS_HRPIVOTALPROGRAM"),
    GETDATA_HRPIVOTALPROGRAM(1364, "GETDATA_HRPIVOTALPROGRAM"),
    VALIDATEFIELD_HRPIVOTALPROGRAM(1365, "VALIDATEFIELD_HRPIVOTALPROGRAM"),
    //HRPivotalInst
    INSERT_HRPIVOTALINST(1340, "INSERT_HRPIVOTALINST"),
    UPDATE_HRPIVOTALINST(1341, "UPDATE_HRPIVOTALINST"),
    DELETE_HRPIVOTALINST(1342, "DELETE_HRPIVOTALINST"),
    GETNUMROWS_HRPIVOTALINST(1343, "GETNUMROWS_HRPIVOTALINST"),
    GETDATA_HRPIVOTALINST(1344, "GETDATA_HRPIVOTALINST"),
    VALIDATEFIELD_HRPIVOTALINST(1345, "VALIDATEFIELD_HRPIVOTALINST"),
    //HRLearningProgram
    INSERT_HRLEARNINGPROGRAM(1380, "INSERT_HRLEARNINGPROGRAM"),
    UPDATE_HRLEARNINGPROGRAM(1381, "UPDATE_HRLEARNINGPROGRAM"),
    DELETE_HRLEARNINGPROGRAM(1382, "DELETE_HRLEARNINGPROGRAM"),
    GETNUMROWS_HRLEARNINGPROGRAM(1383, "GETNUMROWS_HRLEARNINGPROGRAM"),
    GETDATA_HRLEARNINGPROGRAM(1384, "GETDATA_HRLEARNINGPROGRAM"),
    VALIDATEFIELD_HRLEARNINGPROGRAM(1385, "VALIDATEFIELD_HRLEARNINGPROGRAM"),
    //HRAbsScarcity
    INSERT_HRABSSCARCITY(1400, "INSERT_HRABSSCARCITY"),
    UPDATE_HRABSSCARCITY(1401, "UPDATE_HRABSSCARCITY"),
    DELETE_HRABSSCARCITY(1402, "DELETE_HRABSSCARCITY"),
    GETNUMROWS_HRABSSCARCITY(1403, "GETNUMROWS_HRABSSCARCITY"),
    GETDATA_HRABSSCARCITY(1404, "GETDATA_HRABSSCARCITY"),
    VALIDATEFIELD_HRABSSCARCITY(1405, "VALIDATEFIELD_HRABSSCARCITY"),
    //HRScarcePriority
    INSERT_HRSCARCEPRIORITY(1420, "INSERT_HRSCARCEPRIORITY"),
    UPDATE_HRSCARCEPRIORITY(1421, "UPDATE_HRSCARCEPRIORITY"),
    DELETE_HRSCARCEPRIORITY(1422, "DELETE_HRSCARCEPRIORITY"),
    GETNUMROWS_HRSCARCEPRIORITY(1423, "GETNUMROWS_HRSCARCEPRIORITY"),
    GETDATA_HRSCARCEPRIORITY(1424, "GETDATA_HRSCARCEPRIORITY"),
    VALIDATEFIELD_HRSCARCEPRIORITY(1425, "VALIDATEFIELD_HRSCARCEPRIORITY");
    //Enum variables
    final int id;
    final String label;

    /**
     * Creates a new instance of  ServerHRMethods
     */
    ServerHRMethods(final int id, final String label) {
        this.id = id;
        this.label = label;
    }

    public int getId() {
        return id;
    }

    @Override
    public String toString() {
        return label;
    }

    public static ServerHRMethods fromString(final String str) {
        for (ServerHRMethods e : ServerHRMethods.values()) {
            if (e.toString().equalsIgnoreCase(str)) {
                return e;
            }
        }
        return null;
    }

    public static ServerHRMethods fromId(final int id) {
        for (ServerHRMethods e : ServerHRMethods.values()) {
            if (e.id == id) {
                return e;
            }
        }
        return null;
    }

    public enumEMCModules getEMCModule() {
        return enumEMCModules.HR;
    }
}
